-- Datos para la tabla TESTS para los test de Ciencias Naturales del tipo tipo 1 de pregunta con respuesta unica
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(5, 'Ciencias Naturales 01', 'Test 01 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 02', 'Test 02 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 03', 'Test 03 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 04', 'Test 04 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 05', 'Test 05 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 06', 'Test 06 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 07', 'Test 07 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 08', 'Test 08 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 09', 'Test 09 sobre la materia de Ciencias Naturales con respuesta única.', 1),
(5, 'Ciencias Naturales 10', 'Test 10 sobre la materia de Ciencias Naturales con respuesta única.', 1);

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Ciencias Naturales" para el tipo 1 de pregunta con respuesta unica

-- Preguntas para el test 1 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(11, 1, "¿Qué es la fotosíntesis?", '{"respuestas": ["Un proceso mediante el cual las plantas producen su propio alimento a partir de la luz del sol", "Un proceso mediante el cual las plantas absorben nutrientes del suelo", "Un proceso mediante el cual las plantas eliminan oxígeno al ambiente", "Un proceso mediante el cual las plantas convierten oxígeno en dióxido de carbono"], "respuestas_correctas": "Un proceso mediante el cual las plantas producen su propio alimento a partir de la luz del sol"}', "La fotosíntesis es un proceso mediante el cual las plantas producen su propio alimento a partir de la luz del sol."),
(11, 1, "¿Cuál es la capa más externa de la Tierra?", '{"respuestas": ["La corteza", "El núcleo", "El manto", "La astenosfera"], "respuestas_correctas": "La corteza"}', "La corteza es la capa más externa de la Tierra."),
(11, 1, "¿Qué tipo de energía se produce a partir de la fisión nuclear?", '{"respuestas": ["Energía nuclear", "Energía eólica", "Energía solar", "Energía hidráulica"], "respuestas_correctas": "Energía nuclear"}', "La fisión nuclear produce energía nuclear."),
(11, 1, "¿Cuál es la unidad básica de la vida?", '{"respuestas": ["La célula", "El átomo", "El virus", "El protón"], "respuestas_correctas": "La célula"}', "La célula es la unidad básica de la vida."),
(11, 1, "¿Qué es la evolución?", '{"respuestas": ["Un proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo", "Un proceso mediante el cual las especies se mantienen inmutables a través del tiempo", "Un proceso mediante el cual las especies se extinguen", "Un proceso mediante el cual las especies se desplazan a otras regiones geográficas"], "respuestas_correctas": "Un proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo"}', "La evolución es un proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo."),
(11, 1, "¿Qué es un gen?", '{"respuestas": ["Un segmento de ADN que contiene la información para una proteína específica", "Un tipo de célula especializada en la producción de hormonas", "Un tipo de molécula que almacena energía", "Un tipo de molécula que participa en la digestión"], "respuestas_correctas": "Un segmento de ADN que contiene la información para una proteína específica"}', "Un gen es un segmento de ADN que contiene la información para una proteína específica."),
(11, 1, "¿Cuál es la función del sistema nervioso?", '{"respuestas": ["Recibir, interpretar y enviar información para coordinar las funciones del cuerpo", "Eliminar los desechos del cuerpo", "Producir y transportar la sangre", "Proteger al cuerpo de agentes patógenos"], "respuestas_correctas": "Recibir, interpretar y enviar información para coordinar las funciones del cuerpo"}', "La función del sistema nervioso es recibir, interpretar y enviar información para coordinar las funciones del cuerpo."),
(11, 1, "¿Cuál es la función principal del sistema nervioso?", '{"respuestas": ["Recibir y transmitir información", "Producir hormonas", "Regular la temperatura corporal", "Ayudar en la digestión"], "respuestas_correctas": "Recibir y transmitir información"}', "La función principal del sistema nervioso es recibir y transmitir información, permitiendo la comunicación entre diferentes partes del cuerpo y con el entorno."),
(11, 1, "¿Qué es la evolución?", '{"respuestas": ["El cambio gradual de los seres vivos a lo largo del tiempo", "El proceso de formación de nuevas especies", "La selección natural de los individuos más fuertes", "La teoría de que los seres vivos surgieron de la nada"], "respuestas_correctas": "El cambio gradual de los seres vivos a lo largo del tiempo"}', "La evolución es el cambio gradual de los seres vivos a lo largo del tiempo, impulsado por la selección natural y otros factores."),
(11, 1, "¿Qué es una célula?", '{"respuestas": ["La unidad básica de la vida", "Una partícula subatómica", "Un tipo de tejido en el cuerpo", "Una estructura geológica"], "respuestas_correctas": "La unidad básica de la vida"}', "Una célula es la unidad básica de la vida, y puede ser unicelular (como en bacterias) o multicelular (como en animales y plantas).");

-- Preguntas para el test 2 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(12, 1, "¿Qué órgano es responsable de producir la insulina?", '{"respuestas": ["Páncreas", "Hígado", "Riñones", "Estómago"], "respuestas_correctas": "Páncreas"}', "El páncreas es el órgano responsable de producir la insulina, una hormona que regula los niveles de azúcar en la sangre."),
(12, 1, "¿Qué proceso químico es fundamental para la fotosíntesis?", '{"respuestas": ["La absorción de luz", "La respiración celular", "La síntesis de proteínas", "La replicación del ADN"], "respuestas_correctas": "La absorción de luz"}', "La absorción de luz es fundamental para la fotosíntesis, ya que es la energía de la luz la que se convierte en energía química para la planta."),
(12, 1, "¿Qué es un ácido?", '{"respuestas": ["Una sustancia con un pH menor de 7", "Una sustancia con un pH mayor de 7", "Una sustancia que no tiene pH", "Una sustancia que no es soluble en agua"], "respuestas_correctas": "Una sustancia con un pH menor de 7"}', "Un ácido es una sustancia con un pH menor de 7, que se caracteriza por tener un exceso de protones."),
(12, 1, "¿Cuál es el elemento químico más abundante en el universo?", '{"respuestas": ["Hidrógeno", "Oxígeno", "Hierro", "Helio"], "respuestas_correctas": "Hidrógeno"}', "El hidrógeno es el elemento químico más abundante en el universo, constituyendo alrededor del 75% de la masa total del universo."),
(12, 1, "¿Qué es la homeostasis?", '{"respuestas": ["El equilibrio interno del cuerpo", "El proceso de digestión", "La producción de hormonas", "La transmisión de impulsos nerviosos"], "respuestas_correctas": "El equilibrio interno del cuerpo"}', "La homeostasis es el equilibrio interno del cuerpo, mantenido a través de diversos procesos fisiológicos y hormonales."),
(12, 1, "¿Cuál es la función principal de las mitocondrias?", '{"respuestas": ["Generar energía para la célula", "Almacenar agua y nutrientes", "Producir proteínas", "Procesar y degradar desechos celulares"], "respuestas_correctas": "Generar energía para la célula"}', "Las mitocondrias son los orgánulos encargados de generar la mayor parte de la energía necesaria para el funcionamiento celular."),
(12, 1, "¿Qué tipo de células se encargan de la producción de anticuerpos?", '{"respuestas": ["Células plasmáticas", "Células nerviosas", "Células musculares", "Células epiteliales"], "respuestas_correctas": "Células plasmáticas"}', "Las células plasmáticas son un tipo de célula del sistema inmunológico que se encargan de producir anticuerpos para defender al organismo de infecciones y enfermedades."),
(12, 1, "¿Qué es la fotosíntesis?", '{"respuestas": ["El proceso mediante el cual las plantas transforman la energía solar en energía química", "El proceso mediante el cual las células producen proteínas", "El proceso mediante el cual se descomponen los alimentos en el estómago", "El proceso mediante el cual se realiza la respiración celular"], "respuestas_correctas": "El proceso mediante el cual las plantas transforman la energía solar en energía química"}', "La fotosíntesis es el proceso mediante el cual las plantas y otros organismos fotosintéticos transforman la energía solar en energía química para su uso."),
(12, 1, "¿Cuál es la unidad básica de la vida?", '{"respuestas": ["La célula", "El átomo", "El organismo", "El tejido"], "respuestas_correctas": "La célula"}', "La célula es la unidad básica de la vida, ya que es la estructura más pequeña capaz de realizar todas las funciones necesarias para la supervivencia de un ser vivo."),
(12, 1, "¿Qué es un ecosistema?", '{"respuestas": ["Un sistema formado por los seres vivos y los factores abióticos de un ambiente", "Un conjunto de órganos que trabajan juntos para llevar a cabo una función", "Un grupo de organismos de la misma especie que viven en un área determinada", "Una comunidad de organismos que interactúan entre sí"], "respuestas_correctas": "Un sistema formado por los seres vivos y los factores abióticos de un ambiente"}', "Un ecosistema es un sistema formado por los seres vivos y los factores abióticos de un ambiente que interactúan entre sí.");

-- Preguntas para el test 3 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(13, 1, "¿Qué es un fósil?", '{"respuestas": ["Restos de un organismo prehistórico", "Una piedra preciosa", "Un mineral raro", "Un metal radioactivo"], "respuestas_correctas": "Restos de un organismo prehistórico"}', "Un fósil es el resto o huella de un organismo que vivió en tiempos geológicos pasados."),
(13, 1, "¿Qué es la fotosíntesis?", '{"respuestas": ["Proceso por el cual las plantas producen su propio alimento", "Proceso por el cual los animales obtienen su alimento", "Proceso por el cual las bacterias se reproducen", "Proceso por el cual las células se dividen"], "respuestas_correctas": "Proceso por el cual las plantas producen su propio alimento"}', "La fotosíntesis es el proceso por el cual las plantas producen su propio alimento a partir de la luz solar."),
(13, 1, "¿Cuál es la capa más externa de la Tierra?", '{"respuestas": ["La corteza terrestre", "El núcleo terrestre", "El manto terrestre", "La atmósfera"], "respuestas_correctas": "La corteza terrestre"}', "La corteza terrestre es la capa más externa de la Tierra."),
(13, 1, "¿Qué órgano del cuerpo humano produce la insulina?", '{"respuestas": ["Páncreas", "Hígado", "Riñones", "Corazón"], "respuestas_correctas": "Páncreas"}', "La insulina es producida por el páncreas."),
(13, 1, "¿Cuál es el animal más grande del mundo?", '{"respuestas": ["Ballena azul", "Elefante africano", "Jirafa", "Tiburón blanco"], "respuestas_correctas": "Ballena azul"}', "La ballena azul es el animal más grande del mundo."),
(13, 1, "¿Qué es un átomo?", '{"respuestas": ["La unidad básica de la materia", "Un tipo de molécula", "Un tipo de célula", "Un tipo de órgano"], "respuestas_correctas": "La unidad básica de la materia"}', "Un átomo es la unidad básica de la materia."),
(13, 1, "¿Qué es la mitosis?", '{"respuestas": ["Proceso por el cual las células se dividen", "Proceso por el cual las células se fusionan", "Proceso por el cual las células producen energía", "Proceso por el cual las células se comunican entre sí"], "respuestas_correctas": "Proceso por el cual las células se dividen"}', "La mitosis es el proceso por el cual las células se dividen para formar nuevas células."),
(13, 1, "¿Qué es el ADN?", '{"respuestas": ["Material genético que contiene la información hereditaria de un organismo", "Una proteína esencial para la vida", "Un tipo de célula especializada", "Una molécula de azúcar"], "respuestas_correctas": "Proceso por el cual las células se dividen"}', "El ADN es el material genético que contiene la información hereditaria de un organismo."),
(13, 1, "¿Qué es un ecosistema?", '{"respuestas": ["Un conjunto de seres vivos y su ambiente", "Un grupo de células trabajando juntas", "Un conjunto de órganos que realizan una función específica", "Un conjunto de moléculas que forman una célula"], "respuestas_correctas": "Un conjunto de seres vivos y su ambiente"}', "Un ecosistema es un conjunto de seres vivos y su ambiente."),
(13, 1, "¿Qué es la biodiversidad?", '{"respuestas": ["La variedad de seres vivos que existen en la Tierra", "La cantidad de agua disponible en un ambiente", "El número de organismos que pueden vivir en un ambiente determinado", "La cantidad de nutrientes que hay en un ambiente"], "respuestas_correctas": "La variedad de seres vivos que existen en la Tierra"}', "La biodiversidad se refiere a la variedad de seres vivos que existen en la Tierra y a la diversidad de ecosistemas que estos forman.");

-- Preguntas para el test 4 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(14, 1, "¿Qué es la fotosíntesis?", '{"respuestas": ["Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual las plantas eliminan el oxígeno al ambiente", "Proceso mediante el cual las plantas absorben el agua del suelo", "Proceso mediante el cual las plantas producen semillas"], "respuestas_correctas": "Proceso mediante el cual las plantas convierten la luz solar en energía"}', "La fotosíntesis es el proceso mediante el cual las plantas convierten la luz solar en energía química que utilizan para crecer y mantener sus funciones vitales."),
(14, 1, "¿Qué son los ácidos nucleicos?", '{"respuestas": ["Moléculas que contienen la información genética de los seres vivos", "Moléculas que transportan oxígeno en la sangre", "Moléculas que forman parte de las células musculares", "Moléculas que ayudan a la digestión de los alimentos"], "respuestas_correctas": "Moléculas que contienen la información genética de los seres vivos"}', "Los ácidos nucleicos son moléculas que contienen la información genética de los seres vivos, como el ADN y el ARN."),
(14, 1, "¿Cuál es la función del sistema nervioso?", '{"respuestas": ["Recibir y procesar información para coordinar la actividad del cuerpo", "Transportar oxígeno y nutrientes a las células del cuerpo", "Eliminar los desechos del cuerpo", "Producir hormonas que regulan el crecimiento y el desarrollo"], "respuestas_correctas": "Recibir y procesar información para coordinar la actividad del cuerpo"}', "La función del sistema nervioso es recibir y procesar información para coordinar la actividad del cuerpo y mantener su equilibrio interno."),
(14, 1, "¿Qué es la mitosis?", '{"respuestas": ["Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las células se unen para formar tejidos y órganos", "Proceso mediante el cual las células se diferencian y se especializan", "Proceso mediante el cual las células mueren y son reemplazadas por células nuevas"], "respuestas_correctas": "Proceso mediante el cual las células se dividen para crear nuevas células idénticas"}', "La mitosis es el proceso mediante el cual las células se dividen para crear nuevas células idénticas a la célula madre."),
(14, 1, "¿Qué es un ecosistema?", '{"respuestas": ["Comunidad de seres vivos que interactúan entre sí y con su entorno", "Organismo que se alimenta de otros organismos", "Región de la Tierra con un clima y vegetación característicos", "Grupo de animales de una misma especie que comparten un territorio"], "respuestas_correctas": "Comunidad de seres vivos que interactúan entre sí y con su entorno"}', "Un ecosistema es una comunidad de seres vivos que interactúan entre sí y con su entorno, incluyendo los factores bióticos y abióticos que los rodean."),
(14, 1, "¿Qué es la evolución?", '{"respuestas": ["Proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo"}', "La evolución es el proceso mediante el cual las especies cambian y se adaptan a su entorno con el tiempo, a través de la selección natural y la mutación genética."),
(14, 1, "¿Qué son los genes?", '{"respuestas": ["Unidades de información genética que determinan las características hereditarias de los seres vivos", "Moléculas que transportan oxígeno en la sangre", "Moléculas que forman parte de las células musculares", "Moléculas que ayudan a la digestión de los alimentos"], "respuestas_correctas": "Unidades de información genética que determinan las características hereditarias de los seres vivos"}', "Los genes son unidades de información genética que determinan las características hereditarias de los seres vivos."),
(14, 1, "¿Cuál es la función del sistema circulatorio?", '{"respuestas": ["Transportar oxígeno y nutrientes a las células del cuerpo", "Recibir y procesar información para coordinar la actividad del cuerpo", "Eliminar los desechos del cuerpo", "Producir hormonas que regulan el crecimiento y el desarrollo"], "respuestas_correctas": "Transportar oxígeno y nutrientes a las células del cuerpo"}', "La función del sistema circulatorio es transportar oxígeno y nutrientes a las células del cuerpo y eliminar los desechos metabólicos."),
(14, 1, "¿Qué es la meiosis?", '{"respuestas": ["Proceso mediante el cual se produce la formación de gametos (óvulos y espermatozoides)", "Proceso mediante el cual las células se diferencian y se especializan", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las células mueren y son reemplazadas por células nuevas"], "respuestas_correctas": "Proceso mediante el cual se produce la formación de gametos (óvulos y espermatozoides)"}', "La meiosis es el proceso mediante el cual se produce la formación de gametos (óvulos y espermatozoides) a partir de células madre."),
(14, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos que se alimentan unos de otros en un ecosistema", "Comunidad de seres vivos que interactúan entre sí y con su entorno", "Región de la Tierra con un clima y vegetación característicos", "Proceso mediante el cual las plantas convierten la luz solar en energía"], "respuestas_correctas": "Serie de organismos que se alimentan unos de otros en un ecosistema"}', "La cadena alimentaria es una serie de organismos que se alimentan unos de otros en un ecosistema, mostrando la relación de dependencia y transferencia de energía entre ellos.");

-- Preguntas para el test 5 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(15, 1, "¿Qué es el ciclo del agua?", '{"respuestas": ["Proceso mediante el cual el agua se evapora de la superficie de la Tierra y luego regresa a ella a través de la precipitación", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Proceso mediante el cual el agua se evapora de la superficie de la Tierra y luego regresa a ella a través de la precipitación"}', "El ciclo del agua es el proceso mediante el cual el agua se evapora de la superficie de la Tierra y luego regresa a ella a través de la precipitación, manteniendo el equilibrio del agua en el planeta."),
(15, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos que se alimentan unos de otros en un ecosistema", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Serie de organismos que se alimentan unos de otros en un ecosistema"}', "La cadena alimentaria es la serie de organismos que se alimentan unos de otros en un ecosistema, demostrando la interdependencia de los seres vivos en la naturaleza."),
(15, 1, "¿Qué es la respiración celular?", '{"respuestas": ["Proceso mediante el cual las células producen energía a partir de la glucosa y el oxígeno", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Proceso mediante el cual las células producen energía a partir de la glucosa y el oxígeno"}', "La respiración celular es el proceso mediante el cual las células producen energía a partir de la glucosa y el oxígeno, mediante una serie de reacciones químicas."),
(15, 1, "¿Qué es la energía solar?", '{"respuestas": ["Energía que proviene de la radiación solar", "Energía que proviene de los combustibles fósiles", "Energía que proviene de la energía nuclear", "Energía que proviene de la energía hidroeléctrica"], "respuestas_correctas": "Energía que proviene de la radiación solar"}', "La energía solar es la energía que proviene de la radiación solar, que se puede utilizar para generar electricidad y calentar el agua."),
(15, 1, "¿Qué son los seres autótrofos?", '{"respuestas": ["Organismos que producen su propio alimento a través de la fotosíntesis", "Organismos que obtienen su alimento de otros organismos", "Organismos que se alimentan exclusivamente de plantas", "Organismos que se alimentan exclusivamente de carne"], "respuestas_correctas": "Organismos que producen su propio alimento a través de la fotosíntesis"}', "Los seres autótrofos son organismos que producen su propio alimento a través de la fotosíntesis, utilizando la energía del sol para convertir el dióxido de carbono y el agua en glucosa y oxígeno."),
(15, 1, "¿Cuál es la función de los pulmones?", '{"respuestas": ["Tomar oxígeno del aire y expulsar dióxido de carbono", "Transportar oxígeno a las células del cuerpo", "Producir hormonas que regulan el crecimiento y el desarrollo", "Eliminar los desechos del cuerpo"], "respuestas_correctas": "Tomar oxígeno del aire y expulsar dióxido de carbono"}', "Los pulmones son los órganos responsables de tomar oxígeno del aire y expulsar dióxido de carbono del cuerpo."),
(15, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Mantenimiento del equilibrio interno del cuerpo", "Proceso mediante el cual se produce la fotosíntesis", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual los organismos se adaptan al entorno"], "respuestas_correctas": "Mantenimiento del equilibrio interno del cuerpo"}', "La homeostasis es el mantenimiento del equilibrio interno del cuerpo, regulando las condiciones como la temperatura, el pH y el nivel de líquidos corporales."),
(15, 1, "¿Qué es la energía?", '{"respuestas": ["Capacidad de realizar trabajo", "Sustancia que se consume para obtener nutrientes", "Propiedad de los objetos que les permite tener masa", "Fuerza que actúa sobre los cuerpos en movimiento"], "respuestas_correctas": "Capacidad de realizar trabajo"}', "La energía es la capacidad de realizar trabajo, como mover objetos o producir calor."),
(15, 1, "¿Cuál es el proceso mediante el cual las células obtienen energía de los nutrientes?", '{"respuestas": ["Respiración celular", "Fotosíntesis", "Mitosis", "Meiosis"], "respuestas_correctas": "Respiración celular"}', "La respiración celular es el proceso mediante el cual las células obtienen energía de los nutrientes, liberando dióxido de carbono y agua como subproductos."),
(15, 1, "¿Cuál es la diferencia entre un gen y un alelo?", '{"respuestas": ["Un gen es una secuencia de ADN que codifica para una proteína, mientras que un alelo es una variante de un gen", "Un gen es una variante de un alelo, mientras que un alelo es una secuencia de ADN que codifica para una proteína", "Un gen es una proteína, mientras que un alelo es un tipo de célula", "Un gen y un alelo son lo mismo"], "respuestas_correctas": "Un gen es una secuencia de ADN que codifica para una proteína, mientras que un alelo es una variante de un gen"}', "Un gen es una secuencia de ADN que codifica para una proteína específica, mientras que un alelo es una variante de un gen que puede tener efectos diferentes en la expresión de ese gen.");

-- Preguntas para el test 6 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(16, 1, "¿Qué es la célula?", '{"respuestas": ["Unidad básica de la vida", "Grupo de órganos que realizan una función específica", "Molécula que almacena la información genética", "Parte del sistema nervioso encargada de procesar información"], "respuestas_correctas": "Unidad básica de la vida"}', "La célula es la unidad básica de la vida, es decir, la estructura más pequeña que puede considerarse viva y que realiza todas las funciones necesarias para la supervivencia y reproducción de los seres vivos."),
(16, 1, "¿Qué es la genética?", '{"respuestas": ["Rama de la biología que estudia la herencia y la variación de los caracteres de los seres vivos", "Rama de la biología que estudia los seres vivos y su relación con el medio ambiente", "Rama de la biología que estudia los procesos metabólicos de los seres vivos", "Rama de la biología que estudia la evolución de las especies"], "respuestas_correctas": "Rama de la biología que estudia la herencia y la variación de los caracteres de los seres vivos"}', "La genética es la rama de la biología que estudia la herencia y la variación de los caracteres de los seres vivos, incluyendo la transmisión de información genética de una generación a otra y la expresión de los genes."),
(16, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Capacidad de los seres vivos para mantener su equilibrio interno frente a los cambios del ambiente", "Proceso mediante el cual las plantas producen semillas", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía"], "respuestas_correctas": "Capacidad de los seres vivos para mantener su equilibrio interno frente a los cambios del ambiente"}', "La homeostasis es la capacidad de los seres vivos para mantener su equilibrio interno frente a los cambios del ambiente, regulando sus procesos fisiológicos y adaptándose a las condiciones cambiantes."),
(16, 1, "¿Qué es un ecosistema acuático?", '{"respuestas": ["Comunidad de seres vivos que habitan en un ambiente acuático y sus interacciones con el agua y el sustrato", "Comunidad de seres vivos que habitan en un ambiente terrestre y sus interacciones con el suelo y el clima", "Comunidad de seres vivos que habitan en un ambiente desértico y sus interacciones con el sol y el aire", "Comunidad de seres vivos que habitan en un ambiente polar y sus interacciones con el hielo y la nieve"], "respuestas_correctas": "Comunidad de seres vivos que habitan en un ambiente acuático y sus interacciones con el agua y el sustrato"}', "Un ecosistema acuático es una comunidad de seres vivos que habitan en un ambiente acuático y sus interacciones con el agua y el sustrato, incluyendo desde pequeños organismos como plancton y algas hasta grandes depredadores como tiburones y ballenas."),
(16, 1, "¿Qué son los lípidos?", '{"respuestas": ["Moléculas orgánicas compuestas principalmente por carbono e hidrógeno", "Moléculas que transportan oxígeno en la sangre", "Moléculas que contienen la información genética de los seres vivos", "Moléculas que ayudan a la digestión de los alimentos"], "respuestas_correctas": "Moléculas orgánicas compuestas principalmente por carbono e hidrógeno"}', "Los lípidos son moléculas orgánicas compuestas principalmente por carbono e hidrógeno, que desempeñan diversas funciones en los seres vivos, como el almacenamiento de energía, la formación de membranas celulares y la regulación de procesos metabólicos."),
(16, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Mantenimiento del equilibrio interno del cuerpo en condiciones cambiantes", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas absorben el agua del suelo", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Mantenimiento del equilibrio interno del cuerpo en condiciones cambiantes"}', "La homeostasis es el mantenimiento del equilibrio interno del cuerpo en condiciones cambiantes, mediante la regulación de diversos parámetros fisiológicos como la temperatura, el pH y la concentración de sustancias químicas."),
(16, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos que se alimentan unos de otros en un ecosistema", "Serie de reacciones químicas que producen energía en las células", "Serie de procesos mediante los cuales las plantas crecen y se desarrollan", "Serie de cambios que ocurren en el clima y la atmósfera de la Tierra"], "respuestas_correctas": "Serie de organismos que se alimentan unos de otros en un ecosistema"}', "La cadena alimentaria es la serie de organismos que se alimentan unos de otros en un ecosistema, comenzando por los productores (plantas) y continuando con los consumidores primarios, secundarios y terciarios."),
(16, 1, "¿Qué es la célula?", '{"respuestas": ["Unidad básica de la vida", "Molécula que transporta oxígeno en la sangre", "Molécula que contiene la información genética de los seres vivos", "Molécula que ayuda a la digestión de los alimentos"], "respuestas_correctas": "Unidad básica de la vida"}', "La célula es la unidad básica de la vida, constituida por una membrana plasmática que la separa del ambiente externo, y un conjunto de orgánulos y estructuras que realizan diversas funciones vitales."),
(16, 1, "¿Qué son los virus?", '{"respuestas": ["Agentes infecciosos que necesitan invadir células para reproducirse", "Moléculas que forman parte de las células musculares", "Moléculas que contienen la información genética de los seres vivos", "Moléculas que ayudan a la digestión de los alimentos"], "respuestas_correctas": "Agentes infecciosos que necesitan invadir células para reproducirse"}', "Los virus son agentes infecciosos que necesitan invadir células para reproducirse, y pueden causar diversas enfermedades en los seres vivos, incluyendo humanos, animales y plantas."),
(16, 1, "¿Cuál es la diferencia entre una célula animal y una célula vegetal?", '{"respuestas": ["La célula vegetal tiene pared celular y cloroplastos, la célula animal no", "La célula animal tiene pared celular y cloroplastos, la célula vegetal no", "La célula vegetal tiene núcleo, la célula animal no", "La célula animal tiene núcleo, la célula vegetal no"], "respuestas_correctas": "La célula vegetal tiene pared celular y cloroplastos, la célula animal no"}', "La célula vegetal tiene pared celular y cloroplastos, lo que le da soporte y la capacidad de realizar la fotosíntesis, mientras que la célula animal no tiene estas estructuras y depende de otras formas de sostén y nutrición.");

-- Preguntas para el test 7 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(17, 1, "¿Qué son los arrecifes de coral?", '{"respuestas": ["Ecosistemas marinos formados por corales y otros organismos", "Formaciones rocosas en la costa formadas por la erosión del mar", "Especies de algas que crecen en la superficie del agua", "Zonas del océano con grandes corrientes marinas"], "respuestas_correctas": "Ecosistemas marinos formados por corales y otros organismos"}', "Los arrecifes de coral son ecosistemas marinos formados por colonias de corales y otros organismos que construyen estructuras calcáreas."),
(17, 1, "¿Qué es un cromosoma?", '{"respuestas": ["Estructura que contiene el material genético de un ser vivo", "Órgano del cuerpo que secreta hormonas", "Célula especializada en la defensa del organismo", "Tejido que recubre la superficie de los órganos internos"], "respuestas_correctas": "Estructura que contiene el material genético de un ser vivo"}', "Un cromosoma es una estructura que contiene el material genético de un ser vivo, como el ADN."),
(17, 1, "¿Cuál es la función de la clorofila en la fotosíntesis?", '{"respuestas": ["Absorber la luz solar y convertirla en energía química", "Transportar los nutrientes producidos por la fotosíntesis a las células", "Eliminar el oxígeno al ambiente", "Absorber el agua y los nutrientes del suelo"], "respuestas_correctas": "Absorber la luz solar y convertirla en energía química"}', "La clorofila es un pigmento que absorbe la luz solar y la convierte en energía química que se utiliza en la fotosíntesis."),
(17, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos interconectados por sus relaciones de alimentación", "Proceso mediante el cual las plantas convierten la luz solar en energía química", "Mecanismo que permite a las células generar energía a partir de la glucosa", "Sistema que regula la temperatura corporal y la circulación sanguínea"], "respuestas_correctas": "Serie de organismos interconectados por sus relaciones de alimentación"}', "La cadena alimentaria es una serie de organismos interconectados por sus relaciones de alimentación, desde los productores que convierten la energía solar en materia orgánica hasta los consumidores que se alimentan de otros organismos."),
(17, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Mantenimiento del equilibrio interno del cuerpo frente a los cambios externos", "Capacidad de los organismos para adaptarse a su entorno", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Mantenimiento del equilibrio interno del cuerpo frente a los cambios externos"}', "La homeostasis es el mantenimiento del equilibrio interno del cuerpo frente a los cambios externos, mediante la regulación de funciones como la temperatura corporal, el pH y el nivel de nutrientes en la sangre."),
(17, 1, "¿Qué son las células?", '{"respuestas": ["Unidades básicas de la vida", "Pequeñas partículas que forman los átomos", "Moléculas que transportan oxígeno en la sangre", "Moléculas que forman los tejidos y órganos del cuerpo"], "respuestas_correctas": "Unidades básicas de la vida"}', "Las células son las unidades básicas de la vida, y son capaces de realizar todas las funciones necesarias para mantenerla."),
(17, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Equilibrio interno del cuerpo que se mantiene a través de mecanismos de regulación", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Equilibrio interno del cuerpo que se mantiene a través de mecanismos de regulación"}', "La homeostasis es el equilibrio interno del cuerpo que se mantiene a través de mecanismos de regulación, como la regulación de la temperatura corporal y los niveles de glucosa en la sangre."),
(17, 1, "¿Qué son los genes?", '{"respuestas": ["Secuencias de ADN que contienen información genética", "Proteínas que ayudan a la digestión de los alimentos", "Moléculas que forman parte de las células musculares", "Moléculas que transportan oxígeno en la sangre"], "respuestas_correctas": "Secuencias de ADN que contienen información genética"}', "Los genes son secuencias de ADN que contienen información genética y determinan las características físicas y funcionales de un organismo."),
(17, 1, "¿Cuál es la función de las enzimas?", '{"respuestas": ["Facilitar las reacciones químicas en el cuerpo", "Transportar nutrientes y oxígeno a través del cuerpo", "Producir hormonas que regulan el crecimiento y el desarrollo", "Eliminar los desechos del cuerpo"], "respuestas_correctas": "Facilitar las reacciones químicas en el cuerpo"}', "La función de las enzimas es facilitar las reacciones químicas en el cuerpo al reducir la energía de activación necesaria para que ocurran."),
(17, 1, "¿Qué es la célula?", '{"respuestas": ["Unidad básica de la vida", "Unidad básica de la materia", "Unidad básica del movimiento", "Unidad básica de la luz"], "respuestas_correctas": "Unidad básica de la vida"}', "La célula es la unidad básica de la vida y la estructura más pequeña capaz de realizar todas las funciones vitales de los seres vivos.");

-- Preguntas para el test 8 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(18, 1, "¿Qué es la capa de ozono?", '{"respuestas": ["Capa de gas que protege la Tierra de los rayos ultravioleta del sol", "Capa de gas que mantiene el equilibrio térmico de la Tierra", "Capa de gas que produce la lluvia ácida", "Capa de gas que es responsable del efecto invernadero"], "respuestas_correctas": "Capa de gas que protege la Tierra de los rayos ultravioleta del sol"}', "La capa de ozono es una capa de gas en la atmósfera que protege la Tierra de los rayos ultravioleta dañinos del sol."),
(18, 1, "¿Cuál es el proceso por el cual el agua cambia de líquido a gas?", '{"respuestas": ["Ebullición", "Condensación", "Solidificación", "Fusión"], "respuestas_correctas": "Ebullición"}', "El proceso por el cual el agua cambia de líquido a gas se llama ebullición."),
(18, 1, "¿Qué es la biodegradabilidad?", '{"respuestas": ["Capacidad de un material para descomponerse naturalmente por la acción de microorganismos", "Capacidad de un material para ser reciclado", "Capacidad de un material para mantener su forma original después de ser sometido a presión", "Capacidad de un material para conducir electricidad"], "respuestas_correctas": "Capacidad de un material para descomponerse naturalmente por la acción de microorganismos"}', "La biodegradabilidad es la capacidad de un material para descomponerse naturalmente por la acción de microorganismos."),
(18, 1, "¿Qué es la célula?", '{"respuestas": ["Unidad básica de la vida", "Unidad básica de la materia", "Unidad básica del movimiento", "Unidad básica de la energía"], "respuestas_correctas": "Unidad básica de la vida"}', "La célula es la unidad básica de la vida."),
(18, 1, "¿Cuál es la principal función de la clorofila en las plantas?", '{"respuestas": ["Capturar la energía de la luz solar para la fotosíntesis", "Eliminar los desechos del metabolismo celular", "Transportar agua y nutrientes a las hojas", "Producir hormonas de crecimiento"], "respuestas_correctas": "Capturar la energía de la luz solar para la fotosíntesis"}', "La principal función de la clorofila en las plantas es capturar la energía de la luz solar para la fotosíntesis."),
(18, 1, "¿Qué es la ley de conservación de la materia?", '{"respuestas": ["Principio que establece que la materia no puede crearse ni destruirse, solo transformarse", "Principio que establece que la energía no puede crearse ni destruirse, solo transformarse", "Principio que establece que la masa de un objeto es igual a su volumen", "Principio que establece que la aceleración de un objeto es igual a la fuerza que actúa sobre él"], "respuestas_correctas": "Principio que establece que la materia no puede crearse ni destruirse, solo transformarse"}', "La ley de conservación de la materia es un principio que establece que la materia no puede crearse ni destruirse, solo transformarse."),
(18, 1, "¿Qué es la energía renovable?", '{"respuestas": ["Energía que proviene de fuentes naturales que se regeneran continuamente", "Energía que proviene de combustibles fósiles", "Energía que proviene de la fisión nuclear", "Energía que proviene de la combustión de biomasa"], "respuestas_correctas": "Energía que proviene de fuentes naturales que se regeneran continuamente"}', "La energía renovable es aquella que proviene de fuentes naturales que se regeneran continuamente, como la energía solar, eólica o hidráulica."),
(18, 1, "¿Qué es un ser vivo?", '{"respuestas": ["Un organismo que tiene células y puede realizar funciones vitales", "Un organismo que no tiene células y no puede realizar funciones vitales", "Un organismo que no tiene células pero puede realizar funciones vitales", "Un organismo que tiene células pero no puede realizar funciones vitales"], "respuestas_correctas": "Un organismo que tiene células y puede realizar funciones vitales"}', "Un ser vivo es un organismo que tiene células y puede realizar funciones vitales, como la respiración, la nutrición, el crecimiento y la reproducción."),
(18, 1, "¿Cuál es la función del sistema circulatorio?", '{"respuestas": ["Transportar nutrientes, oxígeno y desechos a través del cuerpo", "Regular el crecimiento y el desarrollo del cuerpo", "Producir hormonas que regulan el metabolismo", "Proteger el cuerpo contra infecciones y enfermedades"], "respuestas_correctas": "Transportar nutrientes, oxígeno y desechos a través del cuerpo"}', "La función del sistema circulatorio es transportar nutrientes, oxígeno y desechos a través del cuerpo para mantener el funcionamiento adecuado de las células y órganos."),
(18, 1, "¿Qué es el ADN?", '{"respuestas": ["Molécula que contiene la información genética de los seres vivos", "Molécula que transporta oxígeno en la sangre", "Molécula que forma parte de las células musculares", "Molécula que ayuda a la digestión de los alimentos"], "respuestas_correctas": "Molécula que contiene la información genética de los seres vivos"}', "El ADN es una molécula que contiene la información genética de los seres vivos y se encuentra en el núcleo de las células.");

-- Preguntas para el test 9 de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(19, 1, "¿Qué es la capa de ozono?", '{"respuestas": ["Una capa de gas que protege la Tierra de los rayos ultravioleta del sol", "Una capa de nubes que mantiene la temperatura de la Tierra", "Una capa de hielo que cubre los polos de la Tierra", "Una capa de aire caliente que rodea la Tierra"], "respuestas_correctas": "Una capa de gas que protege la Tierra de los rayos ultravioleta del sol"}', "La capa de ozono es una capa de gas que se encuentra en la atmósfera superior de la Tierra y protege al planeta de los rayos ultravioleta del sol."),
(19, 1, "¿Qué son las células?", '{"respuestas": ["Unidades básicas de la vida", "Órganos que realizan funciones específicas en el cuerpo", "Moléculas que forman parte de los alimentos que consumimos", "Partículas que se encuentran en el aire que respiramos"], "respuestas_correctas": "Unidades básicas de la vida"}', "Las células son las unidades básicas de la vida y forman la estructura de todos los organismos."),
(19, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos interconectados por lo que cada uno se alimenta del anterior", "Serie de reacciones químicas que producen energía en las células", "Serie de cambios en el clima que afectan a los ecosistemas", "Serie de movimientos que realizan los animales para encontrar alimento"], "respuestas_correctas": "Serie de organismos interconectados por lo que cada uno se alimenta del anterior"}', "La cadena alimentaria es una serie de organismos que se interconectan en un ecosistema, donde cada uno se alimenta del organismo que está debajo de él en la cadena."),
(19, 1, "¿Qué es la respiración celular?", '{"respuestas": ["Proceso mediante el cual las células obtienen energía a partir de los nutrientes", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las células producen oxígeno a partir del dióxido de carbono", "Proceso mediante el cual las células se deshacen de los desechos del metabolismo"], "respuestas_correctas": "Proceso mediante el cual las células obtienen energía a partir de los nutrientes"}', "La respiración celular es el proceso mediante el cual las células obtienen energía a partir de los nutrientes, utilizando el oxígeno y produciendo dióxido de carbono y agua como productos de desecho."),
(19, 1, "¿Cuál es la función de los riñones?", '{"respuestas": ["Filtrar la sangre para eliminar los desechos y mantener el equilibrio de líquidos en el cuerpo", "Producir y secretar la insulina para regular el azúcar en la sangre", "Producir y secretar la bilis para digerir las grasas", "Transportar oxígeno a los tejidos del cuerpo"], "respuestas_correctas": "Filtrar la sangre para eliminar los desechos y mantener el equilibrio de líquidos en el cuerpo"}', "La función de los riñones es filtrar la sangre para eliminar los desechos y mantener el equilibrio de líquidos y electrolitos en el cuerpo."),
(19, 1, "¿Qué es la ley de la conservación de la energía?", '{"respuestas": ["Principio que establece que la energía no se crea ni se destruye, solo se transforma de una forma a otra", "Principio que establece que la energía se puede crear a partir de la materia", "Principio que establece que la energía se puede destruir para crear materia", "Principio que establece que la energía se mueve en línea recta"], "respuestas_correctas": "Principio que establece que la energía no se crea ni se destruye, solo se transforma de una forma a otra"}', "La ley de la conservación de la energía establece que la energía no se crea ni se destruye, solo se transforma de una forma a otra."),
(19, 1, "¿Qué es el sistema endocrino?", '{"respuestas": ["Sistema de glándulas que producen y secretan hormonas para regular el funcionamiento del cuerpo", "Sistema de órganos que se encarga de la digestión y absorción de nutrientes", "Sistema de órganos que se encarga del intercambio de gases entre el cuerpo y el ambiente", "Sistema de órganos que se encarga de la locomoción y el movimiento del cuerpo"], "respuestas_correctas": "Sistema de glándulas que producen y secretan hormonas para regular el funcionamiento del cuerpo"}', "El sistema endocrino es un sistema de glándulas que producen y secretan hormonas para regular el funcionamiento del cuerpo, incluyendo procesos como el crecimiento, el metabolismo y la reproducción."),
(19, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Mantenimiento del equilibrio interno del cuerpo a pesar de los cambios en el ambiente externo", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Mantenimiento del equilibrio interno del cuerpo a pesar de los cambios en el ambiente externo"}', "La homeostasis es el mantenimiento del equilibrio interno del cuerpo a pesar de los cambios en el ambiente externo, logrado mediante la coordinación de diferentes sistemas y procesos fisiológicos."),
(19, 1, "¿Qué son los antibióticos?", '{"respuestas": ["Medicamentos que matan o detienen el crecimiento de bacterias", "Medicamentos que alivian el dolor", "Medicamentos que reducen la inflamación", "Medicamentos que disminuyen la fiebre"], "respuestas_correctas": "Medicamentos que matan o detienen el crecimiento de bacterias"}', "Los antibióticos son medicamentos que matan o detienen el crecimiento de bacterias, utilizados para tratar infecciones bacterianas en humanos y animales."),
(19, 1, "¿Cuál es el proceso de respiración en los seres humanos?", '{"respuestas": ["Inhalación de oxígeno y exhalación de dióxido de carbono", "Inhalación de dióxido de carbono y exhalación de oxígeno", "Ingesta de alimentos y expulsión de residuos", "Transporte de nutrientes a través del sistema circulatorio"], "respuestas_correctas": "Inhalación de oxígeno y exhalación de dióxido de carbono"}', "El proceso de respiración en los seres humanos es la inhalación de oxígeno y la exhalación de dióxido de carbono.");

-- Preguntas para el test  de CIENCIAS NATURALES
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(20, 1, "¿Qué es la genética?", '{"respuestas": ["Estudio de la herencia y la variación de los rasgos en los seres vivos", "Estudio de los procesos químicos en los seres vivos", "Estudio de las interacciones entre los seres vivos y su entorno", "Estudio de la estructura y función de las células"], "respuestas_correctas": "Estudio de la herencia y la variación de los rasgos en los seres vivos"}', "La genética es el estudio de la herencia y la variación de los rasgos en los seres vivos, y se enfoca en la información contenida en los genes."),
(20, 1, "¿Qué son los seres autótrofos?", '{"respuestas": ["Organismos capaces de producir su propio alimento a través de la fotosíntesis", "Organismos que se alimentan de otros organismos", "Organismos que descomponen la materia orgánica para obtener energía", "Organismos que obtienen su energía directamente del sol"], "respuestas_correctas": "Organismos capaces de producir su propio alimento a través de la fotosíntesis"}', "Los seres autótrofos son organismos capaces de producir su propio alimento a través de la fotosíntesis, como las plantas."),
(20, 1, "¿Qué es la biodiversidad?", '{"respuestas": ["Variedad de seres vivos y ecosistemas en el planeta", "Cantidad de recursos naturales disponibles en un ecosistema", "Número de especies que habitan en una región", "Cantidad de agua disponible en un ecosistema"], "respuestas_correctas": "Variedad de seres vivos y ecosistemas en el planeta"}', "La biodiversidad se refiere a la variedad de seres vivos y ecosistemas que existen en el planeta, y es importante para mantener el equilibrio de los ecosistemas y la supervivencia de las especies."),
(20, 1, "¿Qué es la cadena alimentaria?", '{"respuestas": ["Serie de organismos que se alimentan unos de otros en un ecosistema", "Proceso mediante el cual las plantas convierten la luz solar en energía", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual se produce la fotosíntesis"], "respuestas_correctas": "Serie de organismos que se alimentan unos de otros en un ecosistema"}', "La cadena alimentaria es la serie de organismos que se alimentan unos de otros en un ecosistema, comenza20o por los productores (seres autótrofos) y terminando en los consumidores secundarios y terciarios."),
(20, 1, "¿Qué es el efecto invernadero?", '{"respuestas": ["Proceso natural que mantiene la temperatura del planeta habitable", "Aumento de la temperatura global debido a la emisión de gases de efecto invernadero", "Disminución de la temperatura global debido a la disminución de la capa de ozono", "Aumento de la temperatura local debido a la actividad humana"], "respuestas_correctas": "Aumento de la temperatura global debido a la emisión de gases de efecto invernadero"}', "El efecto invernadero se refiere al aumento de la temperatura global debido a la emisión de gases de efecto invernadero, como el dióxido de carbono y el metano, que retienen el calor del sol en la atmósfera."),
(20, 1, "¿Qué es la respiración celular?", '{"respuestas": ["Proceso mediante el cual las células liberan energía de los nutrientes", "Proceso mediante el cual las células producen nutrientes a partir de la luz solar", "Proceso mediante el cual las células se dividen para crear nuevas células", "Proceso mediante el cual las células absorben nutrientes del ambiente"], "respuestas_correctas": "Proceso mediante el cual las células liberan energía de los nutrientes"}', "La respiración celular es el proceso mediante el cual las células liberan energía de los nutrientes, para poder realizar todas sus funciones vitales."),
(20, 1, "¿Qué es la selección natural?", '{"respuestas": ["Mecanismo que explica cómo evolucionan las especies", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual se produce la fotosíntesis", "Proceso mediante el cual las plantas absorben agua del suelo"], "respuestas_correctas": "Mecanismo que explica cómo evolucionan las especies"}', "La selección natural es un mecanismo que explica cómo evolucionan las especies, mediante la supervivencia y reproducción de los individuos mejor adaptados a su entorno."),
(20, 1, "¿Qué es la homeostasis?", '{"respuestas": ["Mantenimiento del equilibrio interno del cuerpo", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual las células absorben nutrientes del ambiente", "Proceso mediante el cual las células producen energía a partir de la luz solar"], "respuestas_correctas": "Mantenimiento del equilibrio interno del cuerpo"}', "La homeostasis es el mantenimiento del equilibrio interno del cuerpo, que se logra mediante el control y regulación de diversa20funciones vitales."),
(20, 1, "¿Qué es la digestión?", '{"respuestas": ["Proceso mediante el cual los alimentos se descomponen y absorben en el cuerpo", "Proceso mediante el cual las células se dividen para crear nuevas células idénticas", "Proceso mediante el cual se produce la fotosíntesis", "Proceso mediante el cual las células producen energía a partir de los nutrientes"], "respuestas_correctas": "Proceso mediante el cual los alimentos se descomponen y absorben en el cuerpo"}', "La digestión es el proceso mediante el cual los alimentos se descomponen y absorben en el cuerpo, para poder ser utilizados como energía y nutrientes por las células."),
(20, 1, "¿Qué es la fuerza?", '{"respuestas": ["Efecto que un cuerpo ejerce sobre otro para cambiar su movimiento o forma", "Propiedad de los cuerpos que les permite atraerse entre sí", "Movimiento de un cuerpo alrededor de otro en una trayectoria fija", "Cantidad de espacio que ocupa un objeto"], "respuestas_correctas": "Efecto que un cuerpo ejerce sobre otro para cambiar su movimiento o forma"}', "La fuerza es el efecto que un cuerpo ejerce sobre otro para cambiar su movimiento o forma, y es una magnitud vectorial que se mide en newtons (N).");

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;


