
-- Datos para la tabla TESTS para los test de Matemáticas del tipo tipo 1 de pregunta con respuesta unica
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(18, 'Matemáticas 01', 'Test 01 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 02', 'Test 02 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 03', 'Test 03 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 04', 'Test 04 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 05', 'Test 05 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 06', 'Test 06 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 07', 'Test 07 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 08', 'Test 08 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 09', 'Test 09 sobre la materia de Matemáticas con respuesta única.', 1),
(18, 'Matemáticas 10', 'Test 10 sobre la materia de Matemáticas con respuesta única.', 1);

-- Renimera la tabla TESTS para que no haya problemas en las claves al insertar posteriormente las PREGUNTAS
SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Matemáticas" para el tipo 1 de pregunta con respuesta unica

-- Preguntas para el test 1 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(21, 1, "¿Cuál es la fórmula para calcular el área de un triángulo?", '{"respuestas": ["Base x Altura / 2", "Lado x Altura", "Base x Altura", "Lado x Lado"], "respuestas_correctas": "Base x Altura / 2"}', "La fórmula para calcular el área de un triángulo es base x altura / 2."),
(21, 1, "¿Cuál es la fórmula para calcular el perímetro de un cuadrado?", '{"respuestas": ["4 x Lado", "Lado x Lado", "2 x (Base + Altura)", "Base + Altura + Lado"], "respuestas_correctas": "4 x Lado"}', "La fórmula para calcular el perímetro de un cuadrado es 4 x lado."),
(21, 1, "¿Cuál es la fórmula para calcular el volumen de una esfera?", '{"respuestas": ["(4/3) x π x radio³", "π x radio²", "2 x π x radio", "(4/3) x π x radio²"], "respuestas_correctas": "(4/3) x π x radio³"}', "La fórmula para calcular el volumen de una esfera es (4/3) x π x radio³."),
(21, 1, "¿Cuál es la fórmula para calcular el área de un círculo?", '{"respuestas": ["π x radio²", "2 x π x radio", "(1/2) x π x radio²", "2 x radio"], "respuestas_correctas": "π x radio²"}', "La fórmula para calcular el área de un círculo es π x radio²."),
(21, 1, "¿Cuál es la fórmula para calcular el perímetro de un rectángulo?", '{"respuestas": ["2 x (Base + Altura)", "Lado x Lado", "4 x Lado", "Base + Altura + Lado"], "respuestas_correctas": "2 x (Base + Altura)"}', "La fórmula para calcular el perímetro de un rectángulo es 2 x (base + altura)."),
(21, 1, "¿Cuál es la fórmula para calcular la pendiente de una recta?", '{"respuestas": ["Variación en y / Variación en x", "Variación en x / Variación en y", "y = mx + b", "m = (y₂ - y₁) / (x₂ - x₁)"], "respuestas_correctas": "Variación en y / Variación en x"}', "La fórmula para calcular la pendiente de una recta es variación en y / variación en x."),
(21, 1, "¿Qué es un número racional?", '{"respuestas": ["Un número que se puede expresar como la razón de dos números enteros", "Un número que no se puede expresar como la razón de dos números enteros", "Un número entero positivo", "Un número entero negativo"], "respuestas_correctas": "Un número que se puede expresar como la razón de dos números enteros"}', "Un número racional es un número que se puede expresar como la razón de dos números enteros."),
(21, 1, "¿Qué es una función?", '{"respuestas": ["Una relación entre dos conjuntos, en la que a cada elemento del primer conjunto le corresponde uno y solo uno del segundo conjunto", "Un número que se puede escribir como la razón de dos números enteros", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo"], "respuestas_correctas": "Una relación entre dos conjuntos, en la que a cada elemento del primer conjunto le corresponde uno y solo uno del segundo conjunto"}', "Una función es una relación entre dos conjuntos, en la que a cada elemento del primer conjunto le corresponde uno y solo uno del segundo conjunto."),
(21, 1, "¿Qué es una matriz en álgebra lineal?", '{"respuestas": ["Un arreglo rectangular de números o expresiones algebraicas", "Un conjunto de ecuaciones lineales", "Una operación matemática que consiste en multiplicar dos o más números", "Una función que asigna a cada elemento de un conjunto un valor numérico"], "respuestas_correctas": "Un arreglo rectangular de números o expresiones algebraicas"}', "Una matriz en álgebra lineal es un arreglo rectangular de números o expresiones algebraicas, que se puede utilizar para representar una colección de ecuaciones lineales."),
(21, 1, "¿Qué es un vector en álgebra lineal?", '{"respuestas": ["Una cantidad que tiene magnitud y dirección", "Un número que se puede escribir como la razón de dos números enteros", "Una expresión matemática que relaciona dos o más cantidades", "Una función que asigna a cada elemento de un conjunto un valor numérico"], "respuestas_correctas": "Una cantidad que tiene magnitud y dirección"}', "Un vector en álgebra lineal es una cantidad que tiene magnitud y dirección, y se puede utilizar para representar físicamente objetos como la velocidad y la fuerza.");

-- Preguntas para el test 2 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(22, 1, "¿Qué es una fracción?", '{"respuestas": ["Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una expresión matemática que relaciona dos o más cantidades"], "respuestas_correctas": "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo"}', "Una fracción es una forma de representar una cantidad que no es un número entero, indicando una parte de un todo, y se expresa como un número dividido por otro número."),
(22, 1, "¿Qué es el mínimo común múltiplo?", '{"respuestas": ["El número más pequeño que es múltiplo de dos o más números", "El número más grande que divide a dos o más números sin dejar residuo", "El resultado de sumar dos o más números", "El resultado de multiplicar dos o más números"], "respuestas_correctas": "El número más pequeño que es múltiplo de dos o más números"}', "El mínimo común múltiplo es el número más pequeño que es múltiplo de dos o más números, es decir, es el número más pequeño que es divisible por todos los números que se quieren encontrar el múltiplo común."),
(22, 1, "¿Qué es el máximo común divisor?", '{"respuestas": ["El número más grande que divide a dos o más números sin dejar residuo", "El número más pequeño que es múltiplo de dos o más números", "El resultado de sumar dos o más números", "El resultado de multiplicar dos o más números"], "respuestas_correctas": "El número más grande que divide a dos o más números sin dejar residuo"}', "El máximo común divisor es el número más grande que divide a dos o más números sin dejar residuo, es decir, es el número más grande que es un factor común de los números que se quieren encontrar el divisor común."),
(22, 1, "¿Qué es una ecuación lineal?", '{"respuestas": ["Una expresión matemática que relaciona dos variables de manera lineal", "Una operación matemática que consiste en multiplicar dos o más números", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una expresión matemática que relaciona dos variables de manera lineal"}', "Una ecuación lineal es una expresión matemática que relaciona dos variables de manera lineal, es decir, que tiene la forma ax + b = c, donde a, b, y c son constantes y x es la variable."),
(22, 1, "¿Qué es un triángulo equilátero?", '{"respuestas": ["Un triángulo con tres lados iguales", "Un triángulo con dos lados iguales", "Un triángulo con todos sus ángulos agudos", "Un triángulo con todos sus ángulos rectos"], "respuestas_correctas": "Un triángulo con tres lados iguales"}', "Un triángulo equilátero es un triángulo con tres lados iguales y tres ángulos internos iguales de 60 grados cada uno."),
(22, 1, "¿Cómo se resuelve una ecuación de primer grado?", '{"respuestas": ["Realizando operaciones algebraicas para aislar la variable en un lado de la ecuación", "Realizando operaciones aritméticas para encontrar el valor numérico de la ecuación", "Resolviendo la ecuación mediante una gráfica", "Realizando operaciones de comparación para igualar las dos partes de la ecuación"], "respuestas_correctas": "Realizando operaciones algebraicas para aislar la variable en un lado de la ecuación"}', "Para resolver una ecuación de primer grado se deben realizar operaciones algebraicas para aislar la variable en un lado de la ecuación, dejando en el otro lado el valor numérico de la expresión. Se puede usar la propiedad distributiva, la propiedad conmutativa, la propiedad asociativa, entre otras, para simplificar la ecuación y llegar a la solución."),
(22, 1, "¿Qué es un sistema de ecuaciones?", '{"respuestas": ["Un conjunto de dos o más ecuaciones que se deben resolver simultáneamente", "Una sola ecuación que involucra varias variables", "Una operación matemática que consiste en elevar un número a una potencia", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo"], "respuestas_correctas": "Un conjunto de dos o más ecuaciones que se deben resolver simultáneamente"}', "Un sistema de ecuaciones es un conjunto de dos o más ecuaciones que se deben resolver simultáneamente para encontrar los valores de las variables que satisfacen todas las ecuaciones del sistema. Se pueden utilizar diversas técnicas para resolver sistemas de ecuaciones, como la sustitución, la eliminación, o el método gráfico."),
(22, 1, "¿Qué es una función?", '{"respuestas": ["Una relación matemática que asigna a cada elemento de un conjunto de partida un único elemento de un conjunto de llegada", "Una operación matemática que consiste en elevar un número a una potencia", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una relación matemática que asigna a cada elemento de un conjunto de partida un único elemento de un conjunto de llegada"}', "Una función es una relación matemática que asigna a cada elemento de un conjunto de partida un único elemento de un conjunto de llegada. Se puede representar mediante una fórmula, una tabla de valores, o una gráfica. Las funciones pueden ser lineales, cuadráticas, exponenciales, entre otras."),
(22, 1, "¿Cómo se grafica una función lineal?", '{"respuestas": ["Representando la función mediante una recta en un sistema de coordenadas", "Representando la función mediante una curva en un sistema de coordenadas", "Usando una tabla de valores para obtener puntos de la función y unirlos con rectas", "Usando la propiedad distributiva para encontrar el valor de la función en cada punto"], "respuestas_correctas": "Representando la función mediante una recta en un sistema de coordenadas"}', "Para graficar una función lineal se debe representar la función mediante una recta en un sistema de coordenadas. Para ello, se pueden usar dos puntos de la recta y la ecuación de la recta para trazar la línea que representa la función. También se pueden usar otras técnicas como la pendiente-intercepto o la forma general de la ecuación de la recta."),
(22, 1, "¿Qué es una derivada?", '{"respuestas": ["La tasa de cambio instantánea de una función en un punto dado", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Una expresión matemática que relaciona dos o más cantidades"], "respuestas_correctas": "La tasa de cambio instantánea de una función en un punto dado"}', "Una derivada es la tasa de cambio instantánea de una función en un punto dado, es decir, la pendiente de la recta tangente a la curva de la función en ese punto.");

-- Preguntas para el test 3 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(23, 1, "¿Qué es una función matemática?", '{"respuestas": ["Una relación entre dos conjuntos de números en la que cada número del primer conjunto se relaciona con uno y solo un número del segundo conjunto", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Una expresión matemática que relaciona dos o más cantidades"], "respuestas_correctas": "Una relación entre dos conjuntos de números en la que cada número del primer conjunto se relaciona con uno y solo un número del segundo conjunto"}', "Una función matemática es una relación entre dos conjuntos de números en la que cada número del primer conjunto se relaciona con uno y solo un número del segundo conjunto."),
(23, 1, "¿Qué es el valor absoluto de un número?", '{"respuestas": ["La distancia entre el número y cero en la recta numérica", "La suma de un número con su inverso aditivo", "La diferencia entre un número y su inverso multiplicativo", "La multiplicación de un número por sí mismo"], "respuestas_correctas": "La distancia entre el número y cero en la recta numérica"}', "El valor absoluto de un número es la distancia entre el número y cero en la recta numérica, y se representa como |x|."),
(23, 1, "¿Qué es un polinomio?", '{"respuestas": ["Una expresión matemática que consiste en la suma o resta de términos algebraicos", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Una expresión matemática que relaciona dos o más cantidades"], "respuestas_correctas": "Una expresión matemática que consiste en la suma o resta de términos algebraicos"}', "Un polinomio es una expresión matemática que consiste en la suma o resta de términos algebraicos, donde cada término es el producto de una constante y una o más variables elevadas a exponentes enteros no negativos."),
(23, 1, "¿Qué es una matriz?", '{"respuestas": ["Una tabla rectangular de números o variables", "Un número que se puede escribir como la razón de dos números enteros", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Una expresión matemática que relaciona dos o más cantidades"], "respuestas_correctas": "Una expresión matemática que consiste en la suma o resta de términos algebraicos"}', "Una matriz es una tabla rectangular de números o variables, dispuestos en filas y columnas."),
(23, 1, "¿Qué es el dominio de una función?", '{"respuestas": ["El conjunto de todos los valores de entrada posibles para una función", "El conjunto de todos los valores de salida posibles para una función", "El resultado de sumar dos o más números", "El resultado de multiplicar dos o más números"], "respuestas_correctas": "El conjunto de todos los valores de entrada posibles para una función"}', "El dominio de una función es el conjunto de todos los valores de entrada posibles para una función."),
(23, 1, "¿Qué es el rango de una función?", '{"respuestas": ["El conjunto de todos los valores de salida posibles para una función", "El conjunto de todos los valores de entrada posibles para una función", "El resultado de sumar dos o más números", "El resultado de multiplicar dos o más números"], "respuestas_correctas": "El conjunto de todos los valores de salida posibles para una función"}', "El rango de una función es el conjunto de todos los valores de salida posibles para una función."),
(23, 1, "¿Qué es la derivada de una función?", '{"respuestas": ["La tasa de cambio instantánea de una función en un punto específico", "La integral de una función", "Una función inversa", "Una función exponencial"], "respuestas_correctas": "La tasa de cambio instantánea de una función en un punto específico"}', "La derivada de una función es la tasa de cambio instantánea de una función en un punto específico, es decir, la pendiente de la recta tangente a la curva de la función en ese punto."),
(23, 1, "¿Qué es la integral de una función?", '{"respuestas": ["El área bajo la curva de una función", "La tasa de cambio instantánea de una función en un punto específico", "Una función inversa", "Una función exponencial"], "respuestas_correctas": "El área bajo la curva de una función"}', "La integral de una función es el área bajo la curva de una función, es decir, la suma de todas las áreas de los rectángulos infinitesimales que forman la curva de la función."),
(23, 1, "¿Qué es una matriz en álgebra lineal?", '{"respuestas": ["Un arreglo rectangular de números, organizados en filas y columnas", "Una función matemática que relaciona dos conjuntos", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Un arreglo rectangular de números, organizados en filas y columnas"}', "Una matriz en álgebra lineal es un arreglo rectangular de números, organizados en filas y columnas."),
(23, 1, "¿Qué es la transposición de una matriz?", '{"respuestas": ["Un cambio en la disposición de los elementos de una matriz, intercambiando sus filas y columnas", "La operación de multiplicar dos matrices", "La operación de sumar dos matrices", "La operación de restar dos matrices"], "respuestas_correctas": "Un cambio en la disposición de los elementos de una matriz, intercambiando sus filas y columnas"}', "La transposición de una matriz es un cambio en la disposición de los elementos de una matriz, intercambiando sus filas y columnas.");

-- Preguntas para el test 4 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(24, 1, "¿Qué son las funciones matemáticas?", '{"respuestas": ["Una relación entre dos conjuntos que asigna a cada elemento del primer conjunto exactamente un elemento del segundo conjunto", "Una operación matemática que consiste en multiplicar un número por sí mismo", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una relación entre dos conjuntos que asigna a cada elemento del primer conjunto exactamente un elemento del segundo conjunto"}', "Una función matemática es una relación entre dos conjuntos que asigna a cada elemento del primer conjunto exactamente un elemento del segundo conjunto."),
(24, 1, "¿Qué es una función matemática?", '{"respuestas": ["Una relación entre dos conjuntos en los que cada elemento del conjunto de partida se relaciona con un único elemento del conjunto de llegada", "Un conjunto de valores numéricos", "Una expresión matemática que relaciona dos o más cantidades", "Una operación matemática que consiste en multiplicar un número por sí mismo"], "respuestas_correctas": "Una relación entre dos conjuntos en los que cada elemento del conjunto de partida se relaciona con un único elemento del conjunto de llegada"}', "Una función matemática es una relación entre dos conjuntos en los que cada elemento del conjunto de partida se relaciona con un único elemento del conjunto de llegada."),
(24, 1, "¿Qué es una derivada en cálculo?", '{"respuestas": ["La tasa de cambio instantánea de una función en un punto dado", "La integral de una función", "La pendiente de una recta tangente a una curva en un punto dado", "La suma de una serie infinita de términos"], "respuestas_correctas": "La tasa de cambio instantánea de una función en un punto dado"}', "Una derivada en cálculo es la tasa de cambio instantánea de una función en un punto dado, es decir, es la pendiente de la recta tangente a la curva de la función en ese punto."),
(24, 1, "¿Qué es una integral en cálculo?", '{"respuestas": ["El área bajo la curva de una función entre dos puntos dados", "La tasa de cambio instantánea de una función en un punto dado", "La pendiente de una recta tangente a una curva en un punto dado", "La suma de una serie infinita de términos"], "respuestas_correctas": "El área bajo la curva de una función entre dos puntos dados"}', "Una integral en cálculo es el área bajo la curva de una función entre dos puntos dados, es decir, es el resultado de sumar infinitos elementos que se encuentran debajo de una curva en un intervalo dado."),
(24, 1, "¿Qué es una función matemática?", '{"respuestas": ["Una relación entre dos conjuntos en la que a cada elemento del primer conjunto le corresponde un único elemento del segundo conjunto", "Una operación matemática que consiste en sumar dos o más números", "Una expresión matemática que relaciona dos o más cantidades", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una relación entre dos conjuntos en la que a cada elemento del primer conjunto le corresponde un único elemento del segundo conjunto"}', "Una función matemática es una relación entre dos conjuntos en la que a cada elemento del primer conjunto le corresponde un único elemento del segundo conjunto. Se puede representar mediante una expresión matemática en la que se relacionan dos variables."),
(24, 1, "¿Qué es una derivada?", '{"respuestas": ["La tasa de cambio de una función en un punto específico", "El resultado de multiplicar dos o más números", "La inversa de la operación de suma", "Una fracción con un numerador y denominador iguales"], "respuestas_correctas": "La tasa de cambio de una función en un punto específico"}', "La derivada de una función es la tasa de cambio de la función en un punto específico. Es una medida de la pendiente de la función en ese punto."),
(24, 1, "¿Qué es una integral?", '{"respuestas": ["El área bajo la curva de una función en un intervalo específico", "Una operación matemática que consiste en multiplicar dos o más números", "La inversa de la operación de división", "Una fracción con un numerador y denominador iguales"], "respuestas_correctas": "El área bajo la curva de una función en un intervalo específico"}', "La integral de una función es el área bajo la curva de la función en un intervalo específico. Es una medida de la acumulación de la función en ese intervalo."),
(24, 1, "¿Qué es una matriz?", '{"respuestas": ["Una colección de números ordenados en filas y columnas", "Una operación matemática que consiste en elevar un número a una potencia", "Un número que se puede escribir como la razón de dos números enteros", "Una fracción con un numerador y denominador iguales"], "respuestas_correctas": "Una colección de números ordenados en filas y columnas"}', "Una matriz es una colección de números ordenados en filas y columnas. Se utiliza para representar datos y para realizar operaciones lineales."),
(24, 1, "¿Qué es un determinante?", '{"respuestas": ["Un número que se puede calcular a partir de los elementos de una matriz", "Una operación matemática que consiste en sumar dos o más números", "Una operación matemática que consiste en multiplicar dos o más números", "Una fracción con un numerador y denominador iguales"], "respuestas_correctas": "Un número que se puede calcular a partir de los elementos de una matriz"}', "El determinante de una matriz es un número que se puede calcular a partir de los elementos de la matriz. Es una medida de la orientación y el tamaño de la matriz."),
(24, 1, "¿Qué es un vector?", '{"respuestas": ["Una cantidad que tiene magnitud y dirección", "Una operación matemática que consiste en elevar un número a una potencia", "Una fracción con un numerador y denominador iguales", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una cantidad que tiene magnitud y dirección"}', "Un vector es una cantidad que tiene magnitud y dirección. Se utiliza para representar fuerzas, velocidades y otras cantidades físicas.");

-- Preguntas para el test 5 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(25, 1, "¿Qué es una función matemática?", '{"respuestas": ["Una relación entre dos conjuntos en la que cada elemento del primer conjunto se relaciona con un único elemento del segundo conjunto", "Una operación matemática que consiste en dividir dos números", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una relación entre dos conjuntos en la que cada elemento del primer conjunto se relaciona con un único elemento del segundo conjunto"}', "Una función matemática es una relación entre dos conjuntos en la que cada elemento del primer conjunto se relaciona con un único elemento del segundo conjunto."),
(25, 1, "¿Qué es el dominio de una función?", '{"respuestas": ["El conjunto de todos los valores de entrada de una función", "El conjunto de todos los valores de salida de una función", "El resultado de la operación de una función", "La representación gráfica de una función"], "respuestas_correctas": "El conjunto de todos los valores de entrada de una función"}', "El dominio de una función es el conjunto de todos los valores de entrada de una función, es decir, el conjunto de valores que se pueden ingresar en la función para obtener un resultado."),
(25, 1, "¿Qué es el rango de una función?", '{"respuestas": ["El conjunto de todos los valores de salida de una función", "El conjunto de todos los valores de entrada de una función", "El resultado de la operación de una función", "La representación gráfica de una función"], "respuestas_correctas": "El conjunto de todos los valores de salida de una función"}', "El rango de una función es el conjunto de todos los valores de salida de una función, es decir, el conjunto de valores que la función puede generar."),
(25, 1, "¿Qué es una función inversa?", '{"respuestas": ["La función que deshace la operación realizada por una función original", "La función que realiza la misma operación que una función original", "La función que eleva una variable a una potencia determinada", "La función que calcula el valor absoluto de un número"], "respuestas_correctas": "La función que deshace la operación realizada por una función original"}', "Una función inversa es la función que deshace la operación realizada por una función original, es decir, si f es una función, su función inversa es g tal que g(f(x)) = x."),
(25, 1, "¿Qué es una matriz?", '{"respuestas": ["Una tabla de números dispuestos en filas y columnas", "Una operación matemática que consiste en multiplicar dos o más números", "Una forma de representar una cantidad que no es un número entero, indicando una parte de un todo", "Un número que se puede escribir como la razón de dos números enteros"], "respuestas_correctas": "Una tabla de números dispuestos en filas y columnas"}', "Una matriz es una tabla de números dispuestos en filas y columnas."),
(25, 1, "¿Qué es la determinante de una matriz?", '{"respuestas": ["Un número que se obtiene a partir de los elementos de una matriz y que se utiliza para resolver sistemas de ecuaciones lineales", "La suma de los elementos de una matriz", "El producto de los elementos de una matriz", "La media de los elementos de una matriz"], "respuestas_correctas": "Un número que se obtiene a partir de los elementos de una matriz y que se utiliza para resolver sistemas de ecuaciones lineales"}', "La determinante de una matriz es un número que se obtiene a partir de los elementos de una matriz y que se utiliza para resolver sistemas de ecuaciones lineales."),
(25, 1, "¿Qué es la traza de una matriz?", '{"respuestas": ["La suma de los elementos de la diagonal principal de una matriz", "El producto de los elementos de una matriz", "El número de filas de una matriz", "El número de columnas de una matriz"], "respuestas_correctas": "La suma de los elementos de la diagonal principal de una matriz"}', "La traza de una matriz es la suma de los elementos de la diagonal principal de una matriz."),
(25, 1, "¿Qué es una función matemática?", '{"respuestas": ["Una relación que asigna a cada elemento de un conjunto, un único elemento de otro conjunto", "Un conjunto de números que se combinan mediante operaciones matemáticas", "Una representación gráfica de una ecuación matemática", "Una operación matemática que consiste en multiplicar un número por sí mismo varias veces"], "respuestas_correctas": "Una relación que asigna a cada elemento de un conjunto, un único elemento de otro conjunto"}', "Una función matemática es una relación que asigna a cada elemento de un conjunto, un único elemento de otro conjunto. Esta relación se puede expresar mediante una fórmula o mediante una tabla."),
(25, 1, "¿Qué es el teorema de Pitágoras?", '{"respuestas": ["Una relación matemática que se cumple en cualquier triángulo rectángulo", "Un método para resolver ecuaciones de segundo grado", "Un conjunto de números que se combinan mediante operaciones matemáticas", "Un principio de la geometría que establece que la suma de los ángulos de un triángulo es igual a 180 grados"], "respuestas_correctas": "Una relación matemática que se cumple en cualquier triángulo rectángulo"}', "El teorema de Pitágoras es una relación matemática que se cumple en cualquier triángulo rectángulo, y establece que el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos."),
(25, 1, "¿Qué son los números irracionales?", '{"respuestas": ["Números que no pueden ser expresados como una fracción o una razón de dos números enteros", "Números que se pueden expresar como una fracción o una razón de dos números enteros", "Números que se combinan mediante operaciones matemáticas", "Números que son múltiplos de un número natural"], "respuestas_correctas": "Números que no pueden ser expresados como una fracción o una razón de dos números enteros"}', "Los números irracionales son números que no pueden ser expresados como una fracción o una razón de dos números enteros. Ejemplos de números irracionales son la raíz cuadrada de 2 o el número pi.");

-- Preguntas para el test 6 de MATEMÁTICAS
INSERT INTO PREGUNTAS (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(26, 1, "¿Cuál es la fórmula para calcular el área de un círculo?", '{"respuestas": ["A = πr²", "A = 2πr", "A = 2πr²", "A = 2r"], "respuestas_correctas": "A = πr²"}', "La fórmula para calcular el área de un círculo es A = πr², donde r es el radio del círculo."),
(26, 1, "¿Cuál es la fórmula para calcular el volumen de una esfera?", '{"respuestas": ["V = (4/3)πr³", "V = πr²h", "V = 2πrh + 2πr²", "V = (1/2)bh"], "respuestas_correctas": "V = (4/3)πr³"}', "La fórmula para calcular el volumen de una esfera es V = (4/3)πr³, donde r es el radio de la esfera."),
(26, 1, "¿Cuál es la fórmula para calcular la hipotenusa de un triángulo rectángulo?", '{"respuestas": ["c = √(a² + b²)", "c = a + b", "c = ab", "c = a/b"], "respuestas_correctas": "c = √(a² + b²)"}', "La fórmula para calcular la hipotenusa de un triángulo rectángulo es c = √(a² + b²), donde a y b son los catetos del triángulo."),
(26, 1, "¿Cuál es la fórmula para calcular el área de un triángulo?", '{"respuestas": ["A = (bh)/2", "A = bh", "A = 2πr", "A = πr²"], "respuestas_correctas": "A = (bh)/2"}', "La fórmula para calcular el área de un triángulo es A = (base x altura)/2, donde la base es la medida de uno de los lados y la altura es la distancia perpendicular a la base desde el otro vértice."),
(26, 1, "¿Cuál es la fórmula para calcular el perímetro de un rectángulo?", '{"respuestas": ["P = 2l + 2w", "P = l + w", "P = lw", "P = (l+w)/2"], "respuestas_correctas": "P = 2l + 2w"}', "La fórmula para calcular el perímetro de un rectángulo es P = 2l + 2w, donde l y w son las medidas de los lados del rectángulo."),
(26, 1, "¿Cuál es la fórmula para calcular el volumen de un cubo?", '{"respuestas": ["V = a³", "V = πr²h", "V = (4/3)πr³", "V = (1/2)bh"], "respuestas_correctas": "V = a³"}', "La fórmula para calcular el volumen de un cubo es V = a³, donde a es la medida de uno de los lados del cubo."),
(26, 1, "¿Qué es la regla de tres simple?", '{"respuestas": ["Un método para resolver problemas que involucran dos magnitudes proporcionales", "Un principio de la geometría que establece que la razón entre los lados de un triángulo rectángulo es constante", "Una operación matemática que consiste en multiplicar un número por sí mismo varias veces", "Un conjunto de números que se combinan mediante operaciones matemáticas"], "respuestas_correctas": "Un método para resolver problemas que involucran dos magnitudes proporcionales"}', "La regla de tres simple es un método para resolver problemas que involucran dos magnitudes proporcionales, y consiste en establecer una proporción entre ellas para encontrar una tercera magnitud desconocida."),
(26, 1, "¿Qué es el cálculo diferencial?", '{"respuestas": ["Una rama de las matemáticas que se ocupa del estudio de las tasas de cambio y de cómo se relacionan con las funciones", "Un conjunto de números que se combinan mediante operaciones matemáticas", "Un método para resolver problemas que involucran dos magnitudes proporcionales", "Una operación matemática que consiste en multiplicar un número por sí mismo varias veces"], "respuestas_correctas": "Una rama de las matemáticas que se ocupa del estudio de las tasas de cambio y de cómo se relacionan con las funciones"}', "El cálculo diferencial es una rama de las matemáticas que se ocupa del estudio de las tasas de cambio y de cómo se relacionan con las funciones."),
(26, 1, "¿Qué es una matriz?", '{"respuestas": ["Una tabla rectangular de números o variables", "Una representación gráfica de una función", "Una ecuación que involucra una o más variables", "Una operación matemática que involucra la suma de términos"], "respuestas_correctas": "Una tabla rectangular de números o variables"}', "Una matriz es una tabla rectangular de números o variables, dispuestos en filas y columnas."),
(26, 1, "¿Qué es un determinante?", '{"respuestas": ["Un número que se puede calcular a partir de los elementos de una matriz cuadrada", "El resultado de sumar los elementos de una matriz", "El resultado de multiplicar los elementos de una matriz", "Un número que se puede calcular a partir de los elementos de una matriz rectangular"], "respuestas_correctas": "Un número que se puede calcular a partir de los elementos de una matriz cuadrada"}', "Un determinante es un número que se puede calcular a partir de los elementos de una matriz cuadrada, y que tiene propiedades importantes en el álgebra lineal y en el cálculo de sistemas de ecuaciones lineales.");

-- Preguntas para el test 7 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(27, 1, "¿Cuántos grados tiene un ángulo recto?", '{"respuestas": ["90", "45", "180", "360"], "respuestas_correctas": "90"}', "Un ángulo recto tiene 90 grados."),
(27, 1, "¿Cuál es el resultado de la operación (3x + 2) - (2x - 3)?", '{"respuestas": ["x + 5", "x - 1", "x + 1", "x - 5"], "respuestas_correctas": "x + 5"}', "El resultado de la operación es 3x + 5."),
(27, 1, "¿Cuál es el valor de pi?", '{"respuestas": ["3.14159265359", "3.14159265358", "3.14159265357", "3.14159265356"], "respuestas_correctas": "3.14159265359"}', "El valor de pi es aproximadamente 3.14159265359."),
(27, 1, "¿Cuál es la fórmula para calcular el área de un círculo?", '{"respuestas": ["pi x radio²", "2 x pi x radio", "pi x diametro", "(4/3) x pi x radio³"], "respuestas_correctas": "pi x radio²"}', "El área de un círculo se calcula como pi x radio²."),
(27, 1, "¿Cuál es la suma de los ángulos internos de un triángulo?", '{"respuestas": ["180 grados", "90 grados", "360 grados", "120 grados"], "respuestas_correctas": "180 grados"}', "La suma de los ángulos internos de un triángulo es siempre de 180 grados."),
(27, 1, "¿Cuántos lados tiene un hexágono?", '{"respuestas": ["6", "5", "7", "8"], "respuestas_correctas": "6"}', "Un hexágono tiene 6 lados."),
(27, 1, "¿Cuál es el valor de x en la ecuación 3x + 2 = 8?", '{"respuestas": ["2", "3", "4", "5"], "respuestas_correctas": "2"}', "El valor de x en la ecuación es 2."),
(27, 1, "¿Cuál es la fórmula para calcular la hipotenusa de un triángulo rectángulo?", '{"respuestas": ["√(cateto1² + cateto2²)", "cateto1 x cateto2", "cateto1 + cateto2", "√(cateto1² - cateto2²)"], "respuestas_correctas": "√(cateto1² + cateto2²)"}', "La hipotenusa de un triángulo rectángulo se calcula como la raíz cuadrada de la suma de los cuadrados de los catetos."),
(27, 1, "¿Cuál es la fórmula para calcular la distancia entre dos puntos en un plano cartesiano?", '{"respuestas": ["√((x2 - x1)² + (y2 - y1)²)", "x2 - x1 + y2 - y1", "(x2 - x1) / (y2 - y1)", "(y2 - y1) / (x2 - x1)"], "respuestas_correctas": "√((x2 - x1)² + (y2 - y1)²)"}', "La distancia entre dos puntos en un plano cartesiano se calcula como la raíz cuadrada de la suma de los cuadrados de las diferencias entre las coordenadas."),
(27, 1, "¿Cuál es la fórmula para calcular el área de un triángulo?", '{"respuestas": ["A = (b * h) / 2", "A = b * h", "A = (b + h) / 2", "A = (b * h) * 2"], "respuestas_correctas": "A = (b * h) / 2"}', "La fórmula para calcular el área de un triángulo es A = (base x altura) / 2, donde la base es uno de los lados del triángulo y la altura es la distancia desde la base al vértice opuesto.");

-- Preguntas para el test 8 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(28, 1, "¿Cuántos lados tiene un hexágono?", '{"respuestas": ["4", "5", "6", "7"], "respuestas_correctas": "6"}', "Un hexágono tiene seis lados."),
(28, 1, "¿Cuál es la fórmula para calcular la circunferencia de un círculo?", '{"respuestas": ["2 x pi x radio", "pi x radio²", "pi x diametro", "pi / radio"], "respuestas_correctas": "2 x pi x radio"}', "La circunferencia de un círculo se calcula como 2 x pi x radio."),
(28, 1, "¿Cuántos grados tiene un ángulo recto?", '{"respuestas": ["45 grados", "90 grados", "180 grados", "360 grados"], "respuestas_correctas": "90 grados"}', "Un ángulo recto mide 90 grados."),
(28, 1, "¿Cuánto es 2 + 2 x 2?", '{"respuestas": ["4", "6", "8", "10"], "respuestas_correctas": "6"}', "La multiplicación tiene prioridad sobre la suma, por lo que primero se multiplica 2 x 2 = 4 y luego se suma 4 + 2 = 6."),
(28, 1, "¿Cuál es la derivada de la función f(x) = sin(x)?", '{"respuestas": ["cos(x)", "tan(x)", "csc(x)", "sec(x)"], "respuestas_correctas": "cos(x)"}', "La derivada de la función seno es coseno."),
(28, 1, "¿Cuál es el resultado de la siguiente operación: 5² + 3²?", '{"respuestas": ["34", "25", "9", "64"], "respuestas_correctas": "34"}', "5² = 25 y 3² = 9, por lo que la suma es 25 + 9 = 34."),
(28, 1, "¿Cuántas diagonales tiene un octágono?", '{"respuestas": ["12", "16", "20", "24"], "respuestas_correctas": "12"}', "Un octágono tiene 12 diagonales."),
(28, 1, "¿Cuál es la fórmula para calcular el volumen de una esfera?", '{"respuestas": ["(4/3) x pi x radio³", "pi x radio²", "2 x pi x radio", "(1/2) x pi x radio²"], "respuestas_correctas": "(4/3) x pi x radio³"}', "El volumen de una esfera se calcula como (4/3) x pi x radio³."),
(28, 1, "¿Cuál es el número irracional más famoso?", '{"respuestas": ["e", "phi", "√(2)", "pi"], "respuestas_correctas": "pi"}', "Pi es un número irracional famoso utilizado en muchas aplicaciones matemáticas."),
(28, 1, "¿Cuál es la regla mnemotécnica para recordar el orden de las operaciones matemáticas?", '{"respuestas": ["PEMDAS", "BEDMAS", "GEMDAS", "CEMDAS"], "respuestas_correctas": "PEMDAS"}', "PEMDAS es la regla mnemotécnica utilizada para recordar el orden de las operaciones matemáticas: paréntesis, exponentes, multiplicación, división, suma y resta (en ese orden).");

-- Preguntas para el test 9 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(29, 1, "¿Cuál es la fórmula para calcular el perímetro de un rectángulo?", '{"respuestas": ["2 x (Base + Altura)", "Base x Altura / 2", "2 x Lado", "4 x Lado"], "respuestas_correctas": "2 x (Base + Altura)"}', "El perímetro de un rectángulo se calcula como 2 x (Base + Altura)."),
(29, 1, "¿Cuál es el número más grande que se puede representar con 8 bits?", '{"respuestas": ["255", "256", "127", "128"], "respuestas_correctas": "255"}', "Con 8 bits se pueden representar números entre 0 y 255, siendo 255 el número más grande."),
(29, 1, "¿Cuántas caras tiene un prisma triangular?", '{"respuestas": ["3", "4", "5", "6"], "respuestas_correctas": "4"}', "Un prisma triangular tiene 4 caras: una base triangular y tres caras rectangulares."),
(29, 1, "¿Cuál es el logaritmo de 1 en cualquier base?", '{"respuestas": ["0", "1", "10", "No tiene solución"], "respuestas_correctas": "0"}', "El logaritmo de 1 en cualquier base es siempre 0."),
(29, 1, "¿Cuál es el nombre de la propiedad distributiva de la multiplicación?", '{"respuestas": ["Propiedad distributiva", "Propiedad asociativa", "Propiedad conmutativa", "Propiedad reflexiva"], "respuestas_correctas": "Propiedad distributiva"}', "La propiedad distributiva de la multiplicación establece que a x (b + c) = a x b + a x c."),
(29, 1, "¿Cuál es la fórmula para calcular la pendiente de una recta?", '{"respuestas": ["(y2 - y1) / (x2 - x1)", "(x2 - x1) / (y2 - y1)", "(y2 + y1) / (x2 + x1)", "(x2 + x1) / (y2 + y1)"], "respuestas_correctas": "(y2 - y1) / (x2 - x1)"}', "La pendiente de una recta se calcula como la diferencia de las coordenadas de y dividido por la diferencia de las coordenadas de x."),
(29, 1, "¿Cuál es la raíz cuadrada de 144?", '{"respuestas": ["12", "13", "14", "15"], "respuestas_correctas": "12"}', "La raíz cuadrada de 144 es 12."),
(29, 1, "¿Cuántos lados tiene un dodecágono?", '{"respuestas": ["10", "12", "14", "16"], "respuestas_correctas": "12"}', "Un dodecágono tiene 12 lados."),
(29, 1, "¿Cuál es la fórmula para calcular el volumen de un cilindro?", '{"respuestas": ["pi x radio² x altura", "2 x pi x radio", "pi x radio x altura", "(4/3) x pi x radio³"], "respuestas_correctas": "pi x radio² x altura"}', "El volumen de un cilindro se calcula como pi x radio² x altura."),
(29, 1, "¿Qué es una función lineal?", '{"respuestas": ["Una función cuya gráfica es una línea recta", "Una función que contiene exponentes", "Una función que contiene raíces cuadradas", "Una función que contiene logaritmos"], "respuestas_correctas": "Una función cuya gráfica es una línea recta"}', "Una función lineal es una función cuya gráfica es una línea recta, es decir, que tiene la forma f(x) = mx + b, donde m es la pendiente de la recta y b es la ordenada al origen.");

-- Preguntas para el test 10 de MATEMÁTICAS
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(30, 1, "¿Cuánto es el resultado de 3 * 4 + 5?", '{"respuestas": ["17", "19", "22", "27"], "respuestas_correctas": "19"}', "El resultado de la operación es 19."),
(30, 1, "¿Cuál es el valor de x en la ecuación 2x + 3 = 7?", '{"respuestas": ["2", "3", "4", "5"], "respuestas_correctas": "2"}', "El valor de x en la ecuación es 2."),
(30, 1, "¿Cuál es la fórmula para calcular el volumen de un cubo?", '{"respuestas": ["lado³", "lado x lado x 6", "lado x lado x lado", "lado x lado x 2"], "respuestas_correctas": "lado³"}', "El volumen de un cubo se calcula elevando el lado a la tercera potencia."),
(30, 1, "¿Cuánto es el resultado de 4!?", '{"respuestas": ["24", "12", "8", "16"], "respuestas_correctas": "24"}', "El resultado de 4! es 24."),
(30, 1, "¿Cuál es el perímetro de un rectángulo con una base de 5 cm y una altura de 8 cm?", '{"respuestas": ["26 cm", "30 cm", "33 cm", "40 cm"], "respuestas_correctas": "26 cm"}', "El perímetro de un rectángulo se calcula sumando todos sus lados, en este caso 2 veces la base más 2 veces la altura, dando como resultado 26 cm."),
(30, 1, "¿Cuánto es la raíz cuadrada de 49?", '{"respuestas": ["7", "6", "5", "4"], "respuestas_correctas": "7"}', "La raíz cuadrada de 49 es 7."),
(30, 1, "¿Cuál es la fórmula para calcular el perímetro de un círculo?", '{"respuestas": ["2 x pi x radio", "pi x diametro", "pi x radio²", "(4/3) x pi x radio³"], "respuestas_correctas": "2 x pi x radio"}', "El perímetro de un círculo se calcula como 2 x pi x radio."),
(30, 1, "¿Cuál es la fórmula para calcular el volumen de una esfera?", '{"respuestas": ["V = (4/3)πr³", "V = πr²h", "V = 2πrh + 2πr²", "V = 4πr²"], "respuestas_correctas": "V = (4/3)πr³"}', "La fórmula para calcular el volumen de una esfera es V = (4/3)πr³, donde r es el radio de la esfera y π es una constante aproximadamente igual a 3.1416."),
(30, 1, "¿Qué es el teorema de Pitágoras?", '{"respuestas": ["Una relación matemática entre los lados de un triángulo rectángulo", "Un método para calcular el perímetro de un triángulo", "Una fórmula para calcular el área de un triángulo equilátero", "Un método para calcular la longitud de una curva"], "respuestas_correctas": "Una relación matemática entre los lados de un triángulo rectángulo"}', "El teorema de Pitágoras es una relación matemática entre los lados de un triángulo rectángulo, que establece que el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos."),
(30, 1, "¿Cuál es la fórmula para calcular el área de un triángulo?", '{"respuestas": ["A = (bh)/2", "A = bh", "A = 2πr", "A = πr²"], "respuestas_correctas": "A = (bh)/2"}', "La fórmula para calcular el área de un triángulo es A = (base x altura)/2, donde la base es la medida de uno de los lados y la altura es la distancia perpendicular a la base desde el otro vértice.");

-- Renumera el id de PREGUNTAS
SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;