-- Datos para la tabla TESTS para los test de Informática del tipo tipo de pregunta con respuesta unica
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(20, 'Informática 01', 'Test 01 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 02', 'Test 02 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 03', 'Test 03 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 04', 'Test 04 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 05', 'Test 05 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 06', 'Test 06 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 07', 'Test 07 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 08', 'Test 08 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 09', 'Test 09 sobre la materia de Informática con respuesta única.', 1),
(20, 'Informática 10', 'Test 10 sobre la materia de Informática con respuesta única.', 1);

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Informática" para el tipo de pregunta con respuesta unica

-- Preguntas para el test 1 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(41, 1, "¿Qué es el software?", '{"respuestas": ["Parte física de la computadora", "Conjunto de programas y aplicaciones informáticas", "Dispositivo de entrada o salida", "Componente de la memoria RAM"], "respuestas_correctas": "Conjunto de programas y aplicaciones informáticas"}', "El software es el conjunto de programas y aplicaciones informáticas que permiten el funcionamiento de una computadora o dispositivo electrónico."),
(41, 1, "¿Qué es la nube?", '{"respuestas": ["Un tipo de almacenamiento físico", "Una red de servidores de terceros", "Un sistema operativo para computadoras", "Un dispositivo de entrada o salida"], "respuestas_correctas": "Una red de servidores de terceros"}', "La nube es una red de servidores de terceros que permiten almacenar y acceder a datos e información a través de internet."),
(41, 1, "¿Qué es un sistema operativo?", '{"respuestas": ["El dispositivo físico de la computadora", "Un conjunto de programas de productividad", "La interfaz gráfica de usuario", "El software que gestiona los recursos y procesos del sistema"], "respuestas_correctas": "El software que gestiona los recursos y procesos del sistema"}', "El sistema operativo es el software que gestiona los recursos y procesos del sistema de una computadora o dispositivo electrónico."),
(41, 1, "¿Qué es un hacker?", '{"respuestas": ["Un experto en seguridad informática", "Un programador de software", "Un usuario avanzado de tecnología", "Un dispositivo para piratear redes Wi-Fi"], "respuestas_correctas": "Un experto en seguridad informática"}', "Un hacker es un experto en seguridad informática que se dedica a explorar y proteger sistemas y redes informáticas."),
(41, 1, "¿Qué es el phishing?", '{"respuestas": ["Un tipo de software malicioso", "Un tipo de ataque informático", "Un dispositivo de almacenamiento externo", "Un tipo de programa antivirus"], "respuestas_correctas": "Un tipo de ataque informático"}', "El phishing es un tipo de ataque informático que utiliza técnicas de ingeniería social para engañar a los usuarios y obtener información confidencial."),
(41, 1, "¿Qué es la inteligencia artificial?", '{"respuestas": ["Un tipo de hardware especializado", "Un tipo de software antivirus", "Un conjunto de algoritmos y técnicas de aprendizaje automático", "Un dispositivo de almacenamiento de datos"], "respuestas_correctas": "Un conjunto de algoritmos y técnicas de aprendizaje automático"}', "La inteligencia artificial es un conjunto de algoritmos y técnicas de aprendizaje automático que permiten a las computadoras y dispositivos electrónicos imitar el comportamiento humano."),
(41, 1, "¿Qué es un archivo XML?", '{"respuestas": ["Un lenguaje de marcas que define un conjunto de reglas para la codificación de documentos en un formato que es legible tanto para humanos como para máquinas", "Un lenguaje de programación utilizado para crear páginas web interactivas", "Un formato de archivo de imagen que utiliza compresión sin pérdida", "Un protocolo de red utilizado para la transmisión de datos entre dispositivos"], "respuestas_correctas": "Un lenguaje de marcas que define un conjunto de reglas para la codificación de documentos en un formato que es legible tanto para humanos como para máquinas"}', "XML es un lenguaje de marcas que define un conjunto de reglas para la codificación de documentos en un formato que es legible tanto para humanos como para máquinas. Es utilizado para compartir información estructurada y datos entre diferentes sistemas y aplicaciones."),
(41, 1, "¿Qué es un virus informático?", '{"respuestas": ["Un programa que se ejecuta en una computadora y tiene como objetivo alterar el funcionamiento normal del sistema", "Un dispositivo de almacenamiento de datos externo utilizado para hacer copias de seguridad de archivos", "Un tipo de software que permite a los usuarios navegar por la web", "Un sistema operativo desarrollado por Microsoft"], "respuestas_correctas": "Un programa que se ejecuta en una computadora y tiene como objetivo alterar el funcionamiento normal del sistema"}', "Un virus informático es un programa malicioso que se ejecuta en una computadora y tiene como objetivo alterar el funcionamiento normal del sistema. Puede causar daños a los datos almacenados en la computadora o permitir el acceso no autorizado a la información."),
(41, 1, "¿Qué es un firewall?", '{"respuestas": ["Un software de seguridad diseñado para proteger una red de computadoras al controlar el tráfico que entra y sale de ella", "Un tipo de virus informático que se propaga a través de dispositivos USB", "Un servicio en línea que permite a los usuarios almacenar y compartir archivos en la nube", "Un programa que se ejecuta en segundo plano en una computadora y monitorea el uso de recursos"], "respuestas_correctas": "Un software de seguridad diseñado para proteger una red de computadoras al controlar el tráfico que entra y sale de ella"}', "Un firewall es un software de seguridad diseñado para proteger una red de computadoras al controlar el tráfico que entra y sale de ella. Puede bloquear el acceso no autorizado a la red y proteger contra ataques de virus y malware."),
(41, 1, "¿Qué significan las siglas USB?", '{"respuestas": ["Universal Serial Bus", "Ultra System Base", "Unit System Board", "Unified Serial Bandwidth"], "respuestas_correctas": "Universal Serial Bus"}', "Las siglas USB significan Universal Serial Bus y se refieren a un estándar de comunicación entre dispositivos, utilizado para la conexión de periféricos a una computadora.");

-- Preguntas para el test 2 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(42, 1, "¿Qué es un firewall?", '{"respuestas": ["Un sistema de seguridad informática", "Un sistema operativo", "Un programa de edición de vídeo", "Un software de diseño gráfico"], "respuestas_correctas": "Un sistema de seguridad informática"}', "Un firewall es un sistema de seguridad informática que se encarga de proteger una red o un dispositivo contra posibles amenazas externas, controlando el tráfico que entra y sale."),
(42, 1, "¿Cuál de las siguientes opciones no es un sistema operativo?", '{"respuestas": ["Microsoft Excel", "Linux", "macOS", "Windows"], "respuestas_correctas": "Microsoft Excel"}', "Microsoft Excel es una aplicación de hojas de cálculo, no un sistema operativo."),
(42, 1, "¿Qué es un archivo ZIP?", '{"respuestas": ["Un archivo comprimido", "Un archivo de audio", "Un archivo de video", "Un archivo de texto"], "respuestas_correctas": "Un archivo comprimido"}', "Un archivo ZIP es un archivo comprimido que se utiliza para reducir el tamaño de un archivo o un conjunto de archivos, facilitando su transferencia o almacenamiento."),
(42, 3, "¿Qué es un procesador de texto?", '{"respuestas": ["Un software para la creación y edición de documentos de texto", "Un componente de hardware que controla el flujo de datos", "Un programa de dibujo y diseño gráfico", "Un sistema para la gestión de bases de datos"], "respuestas_correctas": "Un software para la creación y edición de documentos de texto"}', "Un procesador de texto es un software que se utiliza para la creación y edición de documentos de texto, permitiendo la realización de tareas como la escritura, el formato, la corrección ortográfica, entre otras."),
(42, 3, "¿Qué es un antivirus?", '{"respuestas": ["Un programa que detecta y elimina virus informáticos", "Un dispositivo para la transmisión de datos inalámbrica", "Un componente de hardware para el almacenamiento de datos", "Un software para la creación de páginas web"], "respuestas_correctas": "Un programa que detecta y elimina virus informáticos"}', "Un antivirus es un programa que se utiliza para detectar y eliminar virus informáticos, protegiendo la integridad del sistema y los datos almacenados."),
(42, 1, "¿Qué significa la sigla CPU?", '{"respuestas": ["Central Processing Unit", "Computer Processing Unit", "Central Personal Unit", "Computer Personal Unit"], "respuestas_correctas": "Central Processing Unit"}', "La sigla CPU significa Central Processing Unit."),
(42, 1, "¿Qué es un archivo GIF?", '{"respuestas": ["Una imagen", "Un video", "Un documento de texto", "Un archivo de audio"], "respuestas_correctas": "Una imagen"}', "Un archivo GIF es un tipo de archivo de imagen que permite animaciones y transparencias."),
(42, 1, "¿Qué es una dirección IP?", '{"respuestas": ["Un identificador único para un dispositivo en una red", "Un tipo de archivo de audio", "Un tipo de software", "Un dispositivo de entrada"], "respuestas_correctas": "Un identificador único para un dispositivo en una red"}', "Una dirección IP es un identificador único que se asigna a un dispositivo en una red."),
(42, 1, "¿Qué es el almacenamiento en la nube?", '{"respuestas": ["Un servicio que permite guardar archivos en línea", "Un tipo de disco duro", "Un tipo de procesador", "Un tipo de memoria RAM"], "respuestas_correctas": "Un servicio que permite guardar archivos en línea"}', "El almacenamiento en la nube es un servicio que permite guardar archivos en línea y acceder a ellos desde cualquier dispositivo con conexión a internet."),
(42, 1, "¿Qué es un virus informático?", '{"respuestas": ["Un programa malicioso que se propaga y daña sistemas informáticos", "Un programa útil para mejorar el rendimiento del equipo", "Un tipo de hardware", "Un tipo de sistema operativo"], "respuestas_correctas": "Un programa malicioso que se propaga y daña sistemas informáticos"}', "Un virus informático es un programa malicioso que se propaga y daña sistemas informáticos.");

-- Preguntas para el test 3 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(43, 1, "¿Qué es el software?", '{"respuestas": ["Los programas y aplicaciones que se ejecutan en un dispositivo", "El hardware de un dispositivo", "El sistema operativo de un dispositivo", "La conexión a internet de un dispositivo"], "respuestas_correctas": "Los programas y aplicaciones que se ejecutan en un dispositivo"}', "El software son los programas y aplicaciones que se ejecutan en un dispositivo, incluyendo el sistema operativo y otras aplicaciones."),
(43, 1, "¿Qué es la tecnología NFC?", '{"respuestas": ["Una tecnología de comunicación inalámbrica de corto alcance", "Una tecnología de red de área amplia", "Una tecnología de almacenamiento de datos en línea", "Una tecnología de procesamiento de imágenes"], "respuestas_correctas": "Una tecnología de comunicación inalámbrica de corto alcance"}', "La tecnología NFC es una tecnología de comunicación inalámbrica de corto alcance que se utiliza para realizar pagos móviles y transferir datos."),
(43, 1, "¿Qué es un algoritmo?", '{"respuestas": ["Un conjunto de instrucciones que resuelve un problema", "Un tipo de software para la edición de imágenes", "Un protocolo para la transmisión de datos", "Un dispositivo de almacenamiento"], "respuestas_correctas": "Un conjunto de instrucciones que resuelve un problema"}', "Un algoritmo es un conjunto ordenado de instrucciones que resuelve un problema o realiza una tarea específica."),
(43, 1, "¿Qué es el internet de las cosas (IoT)?", '{"respuestas": ["Un sistema que permite la interconexión de dispositivos cotidianos a Internet", "Un programa de edición de texto", "Un conjunto de protocolos de comunicación de red", "Un dispositivo de almacenamiento"], "respuestas_correctas": "Un sistema que permite la interconexión de dispositivos cotidianos a Internet"}', "El Internet de las cosas (IoT) es un sistema que permite la interconexión de dispositivos cotidianos a Internet, lo que les permite interactuar y compartir datos entre ellos."),
(43, 1, "¿Qué es el almacenamiento en la nube?", '{"respuestas": ["Un servicio de almacenamiento de datos en servidores remotos", "Un sistema de almacenamiento en discos duros físicos", "Un dispositivo de almacenamiento USB", "Un sistema de almacenamiento en CD o DVD"], "respuestas_correctas": "Un servicio de almacenamiento de datos en servidores remotos"}', "El almacenamiento en la nube es un servicio de almacenamiento de datos en servidores remotos, lo que permite a los usuarios acceder a sus archivos y datos desde cualquier dispositivo con acceso a Internet."),
(43, 1, "¿Qué es el software de sistema?", '{"respuestas": ["El conjunto de programas que controla el funcionamiento del hardware de un sistema informático", "El software que se encarga de la creación de documentos y presentaciones", "El software que se encarga del procesamiento de transacciones bancarias", "El software que se encarga de la seguridad en línea"], "respuestas_correctas": "El conjunto de programas que controla el funcionamiento del hardware de un sistema informático"}', "El software de sistema es el conjunto de programas que controla el funcionamiento del hardware de un sistema informático, proporcionando servicios básicos para otros programas y aplicaciones."),
(43, 1, "¿Qué es el hardware?", '{"respuestas": ["Los componentes físicos de un sistema informático", "Los programas y aplicaciones que se ejecutan en un sistema informático", "Un servicio en línea que permite la comunicación entre usuarios", "Un dispositivo de almacenamiento"], "respuestas_correctas": "Los componentes físicos de un sistema informático"}', "El hardware son los componentes físicos de un sistema informático, incluyendo la unidad central de procesamiento (CPU), la memoria, el disco duro, la tarjeta gráfica, entre otros."),
(43, 1, "¿Qué es un virus informático?", '{"respuestas": ["Un programa que se encarga de proteger tu computadora", "Un tipo de malware que daña los archivos del sistema", "Un software que permite la conexión a Internet", "Un tipo de hardware utilizado para almacenar información"], "respuestas_correctas": "Un tipo de malware que daña los archivos del sistema"}', "Un virus informático es un tipo de malware que se propaga a través de archivos o programas y puede dañar o destruir los datos de un sistema informático."),
(43, 1, "¿Qué es un phishing?", '{"respuestas": ["Un tipo de virus informático", "Un ataque informático que se realiza mediante la suplantación de identidad", "Un tipo de software malicioso", "Un tipo de conexión a Internet"], "respuestas_correctas": "Un ataque informático que se realiza mediante la suplantación de identidad"}', "El phishing es un tipo de ataque informático que se realiza mediante la suplantación de identidad, con el objetivo de obtener información confidencial como contraseñas o números de tarjetas de crédito."),
(43, 1, "¿Qué es un backup?", '{"respuestas": ["Un tipo de software antivirus", "Un dispositivo de almacenamiento de datos", "Una copia de seguridad de los archivos importantes", "Un tipo de ataque informático"], "respuestas_correctas": "Una copia de seguridad de los archivos importantes"}', "Un backup o copia de seguridad es una copia de los archivos importantes de un sistema informático que se realiza con el objetivo de poder restaurarlos en caso de pérdida o daño de los mismos.");

-- Preguntas para el test 4 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(44, 1, "¿Qué es un disco duro?", '{"respuestas": ["Un tipo de antivirus", "Un dispositivo de almacenamiento de datos", "Un software de edición de vídeo", "Un tipo de hardware utilizado para procesar la información"], "respuestas_correctas": "Un dispositivo de almacenamiento de datos"}', "Un disco duro es un dispositivo de almacenamiento de datos utilizado en los sistemas informáticos para guardar información, programas y sistemas operativos."),
(44, 1, "¿Qué es la nube?", '{"respuestas": ["Un tipo de hardware utilizado para almacenar información", "Una red de computadoras", "Un sistema operativo", "Un servicio de almacenamiento de datos en línea"], "respuestas_correctas": "Un servicio de almacenamiento de datos en línea"}', "La nube o cloud computing es un servicio de almacenamiento de datos en línea que permite a los usuarios acceder a sus archivos y programas desde cualquier dispositivo con conexión a Internet."),
(44, 1, "¿Qué es un router?", '{"respuestas": ["Un dispositivo de almacenamiento de datos", "Un programa que permite la conexión a Internet", "Un tipo de malware", "Un dispositivo que permite la conexión de varias redes de computadoras"], "respuestas_correctas": "Un dispositivo que permite la conexión de varias redes de computadoras"}', "Un router es un dispositivo que permite la conexión de varias redes de computadoras y el intercambio de datos entre ellas."),
(44, 1, "¿Qué significa HTML?", '{"respuestas": ["HyperText Markup Language", "Hyper Technology Markup Language", "Home Tool Markup Language", "High Tech Machine Learning"], "respuestas_correctas": "HyperText Markup Language"}', "HTML es un lenguaje de marcado que se utiliza para estructurar contenido en la web."),
(44, 1, "¿Qué es un servidor web?", '{"respuestas": ["Un software que proporciona servicios web", "Un hardware que almacena páginas web", "Una herramienta para editar páginas web", "Una técnica para mejorar el SEO"], "respuestas_correctas": "Un software que proporciona servicios web"}', "Un servidor web es un software que se encarga de proveer servicios web, como el alojamiento y distribución de páginas web."),
(44, 1, "¿Qué es un sistema operativo?", '{"respuestas": ["El software que administra los recursos del ordenador", "El software que se encarga de la gestión de archivos", "El software que se encarga de la seguridad", "El software que se encarga de la creación de contenidos"], "respuestas_correctas": "El software que administra los recursos del ordenador"}', "El sistema operativo es el software que se encarga de administrar los recursos del ordenador, como la memoria, el procesador y los dispositivos de entrada/salida."),
(44, 1, "¿Qué es una red de área local (LAN)?", '{"respuestas": ["Una red de ordenadores conectados en un área limitada", "Una red de ordenadores conectados a nivel global", "Una red de ordenadores conectados en una ciudad", "Una red de ordenadores conectados en un edificio"], "respuestas_correctas": "Una red de ordenadores conectados en un área limitada"}', "Una LAN es una red de ordenadores conectados en un área limitada, como una casa, un edificio o una oficina."),
(44, 1, "¿Qué es un archivo PDF?", '{"respuestas": ["Un formato de archivo para documentos digitales", "Un formato de archivo de imagen", "Un formato de archivo de audio", "Un formato de archivo de vídeo"], "respuestas_correctas": "Un formato de archivo para documentos digitales"}', "PDF es un formato de archivo para documentos digitales que permite preservar la estructura y el diseño original del documento."),
(44, 1, "¿Qué es el phishing?", '{"respuestas": ["Una técnica de suplantación de identidad", "Un programa antivirus", "Una red social", "Un lenguaje de programación"], "respuestas_correctas": "Una técnica de suplantación de identidad"}', "El phishing es una técnica de suplantación de identidad utilizada por ciberdelincuentes para obtener información confidencial de sus víctimas."),
(44, 1, "¿Qué es un hacker?", '{"respuestas": ["Una persona que se dedica a vulnerar sistemas informáticos", "Un programa malicioso", "Una herramienta de edición de código", "Un hardware especializado"], "respuestas_correctas": "Una persona que se dedica a vulnerar sistemas informáticos"}', "Un hacker es una persona que se dedica a vulnerar sistemas informáticos con el objetivo de acceder a información confidencial o de realizar algún tipo de sabotaje o robo de datos.");

-- Preguntas para el test 5 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES 
(45, 1, "¿Qué es el ransomware?", '{"respuestas": ["Un tipo de malware que secuestra información", "Un sistema operativo de código abierto", "Un programa de edición de audio", "Una herramienta de análisis de datos"], "respuestas_correctas": "Un tipo de malware que secuestra información"}', "El ransomware es un tipo de malware que se utiliza para secuestrar información en un dispositivo y pedir un rescate a cambio de su liberación."),
(45, 1, "¿Qué es un virus informático?", '{"respuestas": ["Un programa malicioso que se propaga a través de sistemas informáticos", "Un programa antivirus", "Un sistema operativo", "Una red social"], "respuestas_correctas": "Un programa malicioso que se propaga a través de sistemas informáticos"}', "Un virus informático es un programa malicioso diseñado para propagarse a través de sistemas informáticos y causar daños o robar información."),
(45, 1, "¿Qué es la ingeniería social?", '{"respuestas": ["Una técnica de manipulación psicológica", "Un sistema de seguridad informática", "Un programa de edición de vídeo", "Una herramienta de programación"], "respuestas_correctas": "Una técnica de manipulación psicológica"}', "La ingeniería social es una técnica de manipulación psicológica utilizada por ciberdelincuentes para obtener información confidencial de sus víctimas."),
(45, 1, "¿Qué es un keylogger?", '{"respuestas": ["Un programa que registra las pulsaciones de teclado", "Un programa antivirus", "Una herramienta de edición de imágenes", "Un lenguaje de programación"], "respuestas_correctas": "Un programa que registra las pulsaciones de teclado"}', "Un keylogger es un programa que registra las pulsaciones de teclado de un dispositivo para obtener información confidencial como contraseñas o información financiera."),
(45, 1, "¿Qué es un archivo CSV?", '{"respuestas": ["Un archivo de imagen", "Un archivo de audio", "Un archivo de texto", "Un archivo ejecutable"], "respuestas_correctas": "Un archivo de texto"}', "CSV son las siglas de Comma Separated Values, un formato de archivo de texto que se utiliza para almacenar y compartir datos tabulares de manera sencilla y legible por humanos."),
(45, 1, "¿Qué es un programa antivirus?", '{"respuestas": ["Un software que detecta y elimina virus informáticos", "Un editor de texto", "Una red social", "Un sistema operativo"], "respuestas_correctas": "Un software que detecta y elimina virus informáticos"}', "Un programa antivirus es un software que detecta y elimina virus informáticos y otros tipos de malware en un sistema informático."),
(45, 1, "¿Qué es un sistema operativo?", '{"respuestas": ["El software que controla el funcionamiento de un ordenador", "Un programa de edición de vídeo", "Una herramienta de diseño gráfico", "Un software de seguridad"], "respuestas_correctas": "El software que controla el funcionamiento de un ordenador"}', "Un sistema operativo es el software que controla el funcionamiento de un ordenador y permite a los usuarios interactuar con el hardware y los programas instalados en el mismo."),
(45, 1, "¿Qué es la nube?", '{"respuestas": ["Un sistema de almacenamiento y procesamiento de datos en línea", "Un dispositivo de almacenamiento externo", "Un software de gestión de proyectos", "Una herramienta de edición de imágenes"], "respuestas_correctas": "Un sistema de almacenamiento y procesamiento de datos en línea"}', "La nube es un sistema de almacenamiento y procesamiento de datos en línea, que permite a los usuarios acceder a sus archivos y aplicaciones desde cualquier lugar y en cualquier momento."),
(45, 1, "¿Qué es una red de ordenadores?", '{"respuestas": ["Un conjunto de ordenadores interconectados", "Un tipo de software", "Una herramienta de diseño gráfico", "Un programa de edición de vídeo"], "respuestas_correctas": "Un conjunto de ordenadores interconectados"}', "Una red de ordenadores es un conjunto de ordenadores interconectados que se comunican entre sí para compartir recursos y datos."),
(45, 1, "¿Qué es un lenguaje de programación?", '{"respuestas": ["Un conjunto de instrucciones para crear software", "Un editor de texto", "Un software de edición de imágenes", "Una herramienta de diseño gráfico"], "respuestas_correctas": "Un conjunto de instrucciones para crear software"}', "Un lenguaje de programación es un conjunto de instrucciones que permiten a los programadores crear software y aplicaciones informáticas.");

-- Preguntas para el test 6 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(46, 1, "¿Qué comando se utiliza para crear una nueva tabla en MySQL?", '{"respuestas": ["CREATE TABLE", "INSERT INTO", "ALTER TABLE", "UPDATE"], "respuestas_correctas": "CREATE TABLE"}', "El comando CREATE TABLE se utiliza para crear una nueva tabla en MySQL."),
(46, 1, "¿Cuál es la sintaxis correcta para eliminar una tabla en MySQL?", '{"respuestas": ["DROP TABLE nombre_tabla", "REMOVE TABLE nombre_tabla", "DELETE TABLE nombre_tabla", "ERASE TABLE nombre_tabla"], "respuestas_correctas": "DROP TABLE nombre_tabla"}', "La sintaxis correcta para eliminar una tabla en MySQL es DROP TABLE nombre_tabla."),
(46, 1, "¿Qué comando se utiliza para agregar una nueva columna a una tabla existente en MySQL?", '{"respuestas": ["ALTER TABLE", "UPDATE TABLE", "ADD COLUMN", "CREATE COLUMN"], "respuestas_correctas": "ALTER TABLE"}', "El comando ALTER TABLE se utiliza para agregar una nueva columna a una tabla existente en MySQL."),
(46, 1, "¿Qué comando se utiliza para seleccionar datos de una tabla en MySQL?", '{"respuestas": ["SELECT", "FIND", "SEARCH", "GET"], "respuestas_correctas": "SELECT"}', "El comando SELECT se utiliza para seleccionar datos de una tabla en MySQL."),
(46, 1, "¿Cuál es la sintaxis correcta para actualizar datos en una tabla en MySQL?", '{"respuestas": ["UPDATE nombre_tabla SET columna1 = valor1 WHERE condicion", "ALTER nombre_tabla SET columna1 = valor1 WHERE condicion", "MODIFY nombre_tabla SET columna1 = valor1 WHERE condicion", "CHANGE nombre_tabla SET columna1 = valor1 WHERE condicion"], "respuestas_correctas": "UPDATE nombre_tabla SET columna1 = valor1 WHERE condicion"}', "La sintaxis correcta para actualizar datos en una tabla en MySQL es UPDATE nombre_tabla SET columna1 = valor1 WHERE condicion."),
(46, 1, "¿Qué comando se utiliza para insertar datos en una tabla en MySQL?", '{"respuestas": ["INSERT INTO", "INSERT DATA", "INSERT VALUES", "ADD TO"], "respuestas_correctas": "INSERT INTO"}', "El comando INSERT INTO se utiliza para insertar datos en una tabla en MySQL."),
(46, 1, "¿Qué comando se utiliza para eliminar datos de una tabla en MySQL?", '{"respuestas": ["DELETE FROM", "REMOVE FROM", "DROP FROM", "ERASE FROM"], "respuestas_correctas": "DELETE FROM"}', "El comando DELETE FROM se utiliza para eliminar datos de una tabla en MySQL."),
(46, 1, "¿Qué comando se utiliza para unir datos de dos o más tablas en MySQL?", '{"respuestas": ["JOIN", "UNION", "MERGE", "CONCATENATE"], "respuestas_correctas": "JOIN"}', "El comando JOIN se utiliza para unir datos de dos o más tablas en MySQL."),
(46, 1, "¿Qué comando se utiliza para crear una nueva tabla en MySQL?", '{"respuestas": ["INSERT", "CREATE", "SELECT", "UPDATE"], "respuestas_correctas": "CREATE"}', "El comando CREATE se utiliza para crear una nueva tabla en MySQL, seguido del nombre de la tabla y sus columnas correspondientes."),
(46, 1, "¿Qué es un índice en MySQL?", '{"respuestas": ["Un valor único que identifica una fila de una tabla", "Una clave externa que establece una relación entre dos tablas", "Una estructura de datos que mejora la velocidad de búsqueda de registros", "Un tipo de dato que almacena valores numéricos"], "respuestas_correctas": "Una estructura de datos que mejora la velocidad de búsqueda de registros"}', "Un índice en MySQL es una estructura de datos que mejora la velocidad de búsqueda de registros en una tabla. Los índices se crean en una o varias columnas de la tabla y permiten acelerar las consultas que utilizan esas columnas como criterio de búsqueda.");

-- Preguntas para el test 7 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(47, 1, "¿Qué es un archivo PDF?", '{"respuestas": ["Un formato de archivo para documentos digitales", "Un formato de imagen", "Un programa de edición de texto", "Una red social"], "respuestas_correctas": "Un formato de archivo para documentos digitales"}', "Un archivo PDF es un formato de archivo para documentos digitales que se utiliza para compartir información de manera segura y fiable."),
(47, 1, "¿Qué es el código fuente?", '{"respuestas": ["El programa escrito en un lenguaje de programación", "Un tipo de software", "Un sistema operativo", "Una herramienta de diseño gráfico"], "respuestas_correctas": "El programa escrito en un lenguaje de programación"}', "El código fuente es el programa escrito en un lenguaje de programación que se utiliza como base para crear software y aplicaciones."),
(47, 1, "¿Qué es un sistema operativo?", '{"respuestas": ["Un programa que controla el hardware y los recursos de un dispositivo", "Un conjunto de hardware en una red de computadoras", "Un software de diseño gráfico", "Un tipo de virus informático"], "respuestas_correctas": "Un programa que controla el hardware y los recursos de un dispositivo"}', "Un sistema operativo es un programa que se encarga de controlar el hardware y los recursos de un dispositivo, permitiendo que otros programas puedan interactuar con él."),
(47, 1, "¿Qué es la memoria RAM?", '{"respuestas": ["Un tipo de procesador", "Un tipo de almacenamiento de datos", "Un tipo de pantalla", "Un tipo de software"], "respuestas_correctas": "Un tipo de almacenamiento de datos"}', "La memoria RAM es un tipo de almacenamiento de datos que se utiliza para cargar y ejecutar programas en un dispositivo."),
(47, 1, "¿Qué es un archivo?", '{"respuestas": ["Un conjunto de datos almacenados en un dispositivo de almacenamiento", "Un tipo de virus informático", "Un hardware utilizado para la visualización de imágenes", "Un software de diseño gráfico"], "respuestas_correctas": "Un conjunto de datos almacenados en un dispositivo de almacenamiento"}', "Un archivo es un conjunto de datos almacenados en un dispositivo de almacenamiento, como un disco duro o una memoria USB."),
(47, 1, "¿Qué es un programa?", '{"respuestas": ["Un conjunto de instrucciones que realizan una tarea específica en un dispositivo", "Un tipo de virus informático", "Un tipo de hardware utilizado para la visualización de imágenes", "Un software de diseño gráfico"], "respuestas_correctas": "Un conjunto de instrucciones que realizan una tarea específica en un dispositivo"}', "Un programa es un conjunto de instrucciones que realizan una tarea específica en un dispositivo, como procesar datos o mostrar información en una pantalla."),
(47, 1, "¿Qué es un navegador web?", '{"respuestas": ["Un programa que permite acceder a páginas web en Internet", "Un tipo de virus informático", "Un hardware utilizado para la visualización de imágenes", "Un software de diseño gráfico"], "respuestas_correctas": "Un programa que permite acceder a páginas web en Internet"}', "Un navegador web es un programa que permite acceder a páginas web en Internet, como Google Chrome o Mozilla Firefox."),
(47, 1, "¿Qué es un archivo comprimido?", '{"respuestas": ["Un archivo que ha sido reducido de tamaño mediante la eliminación de datos redundantes", "Un tipo de virus informático", "Un hardware utilizado para la visualización de imágenes", "Un software de diseño gráfico"], "respuestas_correctas": "Un archivo que ha sido reducido de tamaño mediante la eliminación de datos redundantes"}', "Un archivo comprimido es un archivo que ha sido reducido de tamaño mediante la eliminación de datos redundantes, lo que permite ahorrar espacio de almacenamiento."),
(47, 1, "¿Qué es un sistema operativo?", '{"respuestas": ["Un programa para editar imágenes", "Un conjunto de herramientas para desarrollar software", "Un software que gestiona los recursos del sistema", "Un lenguaje de programación"], "respuestas_correctas": "Un software que gestiona los recursos del sistema"}', "Un sistema operativo es un software que gestiona los recursos de hardware y software de un ordenador y proporciona servicios comunes para programas de aplicaciones."),
(47, 1, "¿Qué es una base de datos?", '{"respuestas": ["Un dispositivo de almacenamiento de datos", "Un software para crear presentaciones", "Un conjunto de hardware y software", "Un programa para navegar por internet"], "respuestas_correctas": "Un conjunto de hardware y software"}', "Una base de datos es un conjunto de hardware y software que se utiliza para almacenar y gestionar grandes cantidades de información de forma estructurada y organizada.");

-- Preguntas para el test 8 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(48, 1, "¿Qué es la virtualización?", '{"respuestas": ["La creación de una versión virtual de un sistema operativo o una aplicación", "La creación de una red privada virtual", "La emulación de un sistema operativo en otro", "La creación de una máquina virtual"], "respuestas_correctas": "La creación de una versión virtual de un sistema operativo o una aplicación"}', "La virtualización es la creación de una versión virtual de un sistema operativo o una aplicación que se ejecuta en un entorno aislado del sistema principal."),
(48, 1, "¿Qué es el almacenamiento en la nube?", '{"respuestas": ["El almacenamiento de datos en discos duros externos", "El almacenamiento de datos en servidores remotos accesibles a través de internet", "El almacenamiento de datos en la memoria RAM", "El almacenamiento de datos en la memoria caché"], "respuestas_correctas": "El almacenamiento de datos en servidores remotos accesibles a través de internet"}', "El almacenamiento en la nube es el almacenamiento de datos en servidores remotos accesibles a través de internet, en lugar de en dispositivos locales como discos duros o USB."),
(48, 1, "¿Qué es un servidor web?", '{"respuestas": ["Un ordenador personal", "Un tipo de software de edición de texto", "Un programa de navegación por internet", "Un ordenador que aloja páginas web accesibles desde internet"], "respuestas_correctas": "Un ordenador que aloja páginas web accesibles desde internet"}', "Un servidor web es un ordenador que aloja páginas web accesibles desde internet y que responde a solicitudes de los clientes que desean acceder a ellas."),
(48, 1, "¿Qué es un sistema de archivos distribuido?", '{"respuestas": ["Un sistema de almacenamiento en línea", "Un sistema que permite acceder a archivos desde diferentes dispositivos", "Un sistema que permite compartir archivos en línea", "Un sistema que organiza los archivos en carpetas"], "respuestas_correctas": "Un sistema que permite acceder a archivos desde diferentes dispositivos"}', "Un sistema de archivos distribuido es una tecnología de almacenamiento que permite acceder a los archivos desde diferentes dispositivos y ubicaciones geográficas, a través de una red."),
(48, 1, "¿Qué es un cluster de servidores?", '{"respuestas": ["Un grupo de servidores conectados en red", "Un servidor que almacena varios clusters", "Un software que permite la gestión de servidores", "Un tipo de servidor web"], "respuestas_correctas": "Un grupo de servidores conectados en red"}', "Un cluster de servidores es un conjunto de servidores conectados en red que trabajan juntos para proporcionar servicios de alta disponibilidad, escalabilidad y fiabilidad. Los servidores en un cluster están sincronizados y pueden distribuir la carga de trabajo entre ellos."),
(48, 1, '¿Qué es un índice en MySQL?', '{"respuestas": ["Un objeto que mejora la velocidad de búsqueda de registros en una tabla", "Un tipo de dato utilizado para almacenar valores numéricos", "Un conjunto de instrucciones utilizadas para modificar una tabla", "Un valor que identifica de forma única a cada registro en una tabla"], "respuestas_correctas": "Un objeto que mejora la velocidad de búsqueda de registros en una tabla."}', 'Un índice en MySQL es un objeto que mejora la velocidad de búsqueda de registros en una tabla.'),
(48, 1, "¿Qué es un sistema de control de versiones?", '{"respuestas": ["Un software que permite el control de acceso a los archivos", "Un sistema de seguridad informática", "Un software que permite la gestión de servidores", "Un sistema que permite el seguimiento de los cambios en el código fuente"], "respuestas_correctas": "Un sistema que permite el seguimiento de los cambios en el código fuente"}', "Un sistema de control de versiones es una herramienta de software que permite el seguimiento de los cambios en el código fuente de un proyecto. Esto permite a los desarrolladores trabajar en equipo en el mismo código fuente y mantener un historial de todos los cambios realizados."),
(48, 1, "¿Qué es un servidor web?", '{"respuestas": ["Un software que permite la gestión de servidores", "Un servidor que almacena varios clusters", "Un tipo de servidor de bases de datos", "Un programa que sirve contenido web"], "respuestas_correctas": "Un programa que sirve contenido web"}', "Un servidor web es un programa que se ejecuta en un servidor y que se utiliza para servir contenido web a través de la red. El servidor web procesa las solicitudes de los clientes y envía las respuestas correspondientes."),
(48, 1, "¿Qué es un índice en una base de datos?", '{"respuestas": ["Una estructura de datos que permite la búsqueda y recuperación de registros de manera más rápida", "Un archivo de registro de transacciones", "Una secuencia de comandos que automatiza tareas repetitivas", "Un lenguaje de programación para el desarrollo web"], "respuestas_correctas": "Una estructura de datos que permite la búsqueda y recuperación de registros de manera más rápida"}', "Un índice es una estructura de datos que se utiliza para acelerar la búsqueda y recuperación de registros en una base de datos."),
(48, 1, "¿Qué es la normalización de una base de datos?", '{"respuestas": ["El proceso de organizar los datos en una base de datos para evitar la redundancia y mejorar la integridad de los datos", "El proceso de hacer una copia de seguridad de una base de datos", "El proceso de agregar nuevos campos a una tabla existente", "El proceso de eliminar datos antiguos de una base de datos"], "respuestas_correctas": "El proceso de organizar los datos en una base de datos para evitar la redundancia y mejorar la integridad de los datos"}', "La normalización de una base de datos es el proceso de organizar los datos en una base de datos de manera que se evite la redundancia y se mejore la integridad de los datos.");

-- Preguntas para el test 9 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(49, 1, "¿Qué es una clave foránea en una base de datos?", '{"respuestas": ["Un campo o conjunto de campos en una tabla que se relaciona con el campo o conjunto de campos de otra tabla", "Un campo que identifica de manera única a cada registro en una tabla", "Un campo que se utiliza para ordenar los registros en una tabla", "Un campo que indica el tipo de datos que se almacenan en una columna de una tabla"], "respuestas_correctas": "Un campo o conjunto de campos en una tabla que se relaciona con el campo o conjunto de campos de otra tabla"}', "Una clave foránea en una base de datos es un campo o conjunto de campos en una tabla que se relaciona con el campo o conjunto de campos de otra tabla."),
(49, 1, "¿Qué es un firewall?", '{"respuestas": ["Un sistema de seguridad informática", "Un sistema operativo", "Un programa de edición de vídeo", "Un software de diseño gráfico"], "respuestas_correctas": "Un sistema de seguridad informática"}', "Un firewall es un sistema de seguridad informática que se encarga de proteger una red o un dispositivo contra posibles amenazas externas, controlando el tráfico que entra y sale."),
(49, 1, "¿Qué es una clave primaria?", '{"respuestas": ["Una columna que identifica de manera única cada registro en una tabla", "Un campo que permite almacenar valores de texto", "Una función que realiza operaciones aritméticas", "Una herramienta de optimización de consultas"], "respuestas_correctas": "Una columna que identifica de manera única cada registro en una tabla"}', "Una clave primaria es una columna o conjunto de columnas que identifican de manera única cada registro en una tabla."),
(49, 1, "¿Qué es una vista en MySQL?", '{"respuestas": ["Una tabla virtual que se crea a partir de otra tabla o tablas", "Una función de agregación que devuelve el valor máximo", "Una herramienta para la administración de usuarios", "Una función que realiza cálculos aritméticos"], "respuestas_correctas": "Una tabla virtual que se crea a partir de otra tabla o tablas"}', "Una vista en MySQL es una tabla virtual que se crea a partir de otra tabla o tablas."),
(49, 1, "¿Qué es un balanceador de carga?", '{"respuestas": ["Un dispositivo que equilibra la carga de trabajo en una red", "Un software de gestión de servidores", "Un dispositivo que protege la red contra ataques DDoS", "Un software de administración de bases de datos"], "respuestas_correctas": "Un dispositivo que equilibra la carga de trabajo en una red"}', "Un balanceador de carga es un dispositivo que se utiliza para distribuir el tráfico de red de manera uniforme entre varios servidores, para evitar que un solo servidor se sobrecargue y se convierta en un cuello de botella."),
(49, 1, "¿Qué es una clave foránea?", '{"respuestas": ["Una columna que referencia a otra tabla", "Un tipo de dato numérico", "Una función de agrupamiento", "Una herramienta de respaldo"], "respuestas_correctas": "Una columna que referencia a otra tabla"}', "Una clave foránea es una columna o conjunto de columnas que se utilizan para establecer una relación entre dos tablas."),
(49, 1, "¿Qué es una transacción en MySQL?", '{"respuestas": ["Un conjunto de operaciones que se realizan como una única unidad lógica", "Un tipo de dato que permite almacenar valores binarios", "Una función de agregación que retorna el valor mínimo", "Una herramienta para la optimización del rendimiento"], "respuestas_correctas": "Un conjunto de operaciones que se realizan como una única unidad lógica"}', "Una transacción en MySQL es un conjunto de operaciones que se realizan como una única unidad lógica."),
(49, 1, "¿Qué es un índice en MySQL?", '{"respuestas": ["Una estructura de datos que mejora la velocidad de las búsquedas en una tabla", "Una función que devuelve la longitud de una cadena de texto", "Un tipo de dato que almacena valores monetarios", "Una herramienta para el control de versiones"], "respuestas_correctas": "Una estructura de datos que mejora la velocidad de las búsquedas en una tabla"}', "Un índice en MySQL es una estructura de datos que se utiliza para mejorar la velocidad de las búsquedas en una tabla."),
(49, 1, '¿Qué es una clave primaria en MySQL?', '{"respuestas": ["Un índice que garantiza la unicidad de los valores de una columna o conjunto de columnas", "Un conjunto de reglas que especifican cómo se deben relacionar las tablas", "Un tipo de dato utilizado para almacenar valores numéricos", "Un objeto que mejora la velocidad de búsqueda de registros en una tabla"], "respuestas_correctas": "Un índice que garantiza la unicidad de los valores de una columna o conjunto de columnas."}', 'Una clave primaria en MySQL es un índice que garantiza la unicidad de los valores de una columna o conjunto de columnas.'),
(49, 1, '¿Qué es una transacción en MySQL?', '{"respuestas": ["Un conjunto de operaciones que deben realizarse como una sola unidad lógica de trabajo", "Un objeto que mejora la velocidad de búsqueda de registros en una tabla", "Un tipo de dato utilizado para almacenar valores numéricos", "Un conjunto de reglas que especifican cómo se deben relacionar las tablas"], "respuestas_correctas": "Un conjunto de operaciones que deben realizarse como una sola unidad lógica de trabajo."}', 'Una transacción en MySQL es un conjunto de operaciones que deben realizarse como una sola unidad lógica de trabajo.');

-- Preguntas para el test 10 de Informática
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(50, 1, "¿Qué es una dirección IP?", '{"respuestas": ["Un número que identifica un dispositivo en una red", "Un software para navegar por internet", "Un programa de edición de imagen", "Un dispositivo de red"], "respuestas_correctas": "Un número que identifica un dispositivo en una red"}', "Una dirección IP es un número que identifica de manera única a un dispositivo en una red."),
(50, 1, '¿Qué es una vista en MySQL?', '{"respuestas": ["Un objeto que representa una tabla virtual basada en los resultados de una consulta SQL", "Un conjunto de reglas que especifican cómo se deben relacionar las tablas", "Un tipo de dato utilizado para almacenar valores numéricos", "Un objeto que mejora la velocidad de búsqueda de registros en una tabla"], "respuestas_correctas": "Un objeto que representa una tabla virtual basada en los resultados de una consulta SQL."}', 'Una vista en MySQL es un objeto que representa una tabla virtual basada en los resultados de una consulta SQL.'),
(50, 1, "¿Qué es un enrutador?", '{"respuestas": ["Un dispositivo que conecta varias redes de computadoras", "Un tipo de cable de red", "Un programa de gestión de base de datos", "Una herramienta para medir la velocidad de internet"], "respuestas_correctas": "Un dispositivo que conecta varias redes de computadoras"}', "Un enrutador es un dispositivo que conecta varias redes de computadoras y dirige el tráfico de datos entre ellas."),
(50, 1, "¿Qué es un servidor DNS?", '{"respuestas": ["Un servidor que traduce nombres de dominio en direcciones IP", "Un servidor que almacena archivos de un sitio web", "Un software para crear páginas web", "Un dispositivo que permite conectarse a una red inalámbrica"], "respuestas_correctas": "Un servidor que traduce nombres de dominio en direcciones IP"}', "Un servidor DNS es un servidor que se encarga de traducir nombres de dominio en direcciones IP para que los usuarios puedan acceder a los sitios web por su nombre."),
(50, 1, '¿Qué es la normalización de datos en MySQL?', '{"respuestas": ["Un proceso que se utiliza para organizar los datos en una tabla y reducir la redundancia", "Un objeto que mejora la velocidad de búsqueda de registros en una tabla", "Un tipo de dato utilizado para almacenar valores numéricos", "Un conjunto de reglas que especifican cómo se deben relacionar las tablas"], "respuestas_correctas": "Un proceso que se utiliza para organizar los datos en una tabla y reducir la redundancia."}', 'La normalización de datos en MySQL es un proceso que se utiliza para organizar los datos en una tabla y reducir la redundancia.'),
(50, 1, "¿Qué es un protocolo de red?", '{"respuestas": ["Un conjunto de reglas que rigen la comunicación entre dispositivos en una red", "Un tipo de dispositivo de red", "Un software de seguridad informática", "Un programa de edición de video"], "respuestas_correctas": "Un conjunto de reglas que rigen la comunicación entre dispositivos en una red"}', "Un protocolo de red es un conjunto de reglas que rigen la comunicación entre dispositivos en una red."),
(50, 1, "¿Qué es el protocolo TCP/IP?", '{"respuestas": ["Un conjunto de protocolos que se utilizan para la comunicación en internet", "Un tipo de dispositivo de red", "Un programa de edición de imagen", "Un software para crear páginas web"], "respuestas_correctas": "Un conjunto de protocolos que se utilizan para la comunicación en internet"}', "El protocolo TCP/IP es un conjunto de protocolos que se utilizan para la comunicación en internet."),
(50, 1, "¿Qué es un cortafuegos?", '{"respuestas": ["Un sistema de seguridad que controla el tráfico de red", "Un software para programar en PHP", "Un dispositivo de red que amplifica la señal", "Un programa para gestionar bases de datos"], "respuestas_correctas": "Un sistema de seguridad que controla el tráfico de red"}', "Un cortafuegos es un sistema de seguridad que controla el tráfico de red para proteger una red o un dispositivo contra posibles amenazas externas."),
(50, 1, "¿Qué es NAT?", '{"respuestas": ["Una técnica de enrutamiento", "Un tipo de cable de red", "Una aplicación de mensajería instantánea", "Un protocolo de seguridad"], "respuestas_correctas": "Una técnica de enrutamiento"}', "NAT (Network Address Translation) es una técnica de enrutamiento que se utiliza para permitir que los dispositivos en una red privada se conecten a Internet utilizando una única dirección IP pública."),
(50, 1, "¿Qué es un switch?", '{"respuestas": ["Un dispositivo de red que permite conectar varios dispositivos", "Un dispositivo de almacenamiento de datos", "Un programa para crear páginas web", "Un dispositivo para controlar el flujo de datos"], "respuestas_correctas": "Un dispositivo de red que permite conectar varios dispositivos"}', "Un switch es un dispositivo de red que se utiliza para conectar varios dispositivos, como computadoras, impresoras, cámaras de seguridad, etc. a una red. El switch se encarga de controlar el flujo de datos entre los dispositivos conectados.");

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;
