-- Datos para la tabla TESTS para los test de Artes Visuales del tipo de pregunta 2 multiples respuestas
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(3, 'Artes Visuales 01', 'Test 01 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 02', 'Test 02 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 03', 'Test 03 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 04', 'Test 04 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 05', 'Test 05 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 06', 'Test 06 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 07', 'Test 07 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 08', 'Test 08 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 09', 'Test 09 sobre la materia de Artes Visuales de formas verbales.', 1),
(3, 'Artes Visuales 10', 'Test 10 sobre la materia de Artes Visuales de formas verbales.', 1);

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Artes Visuales" para el tipo de pregunta 2 multiples respuestas

-- Preguntas para el test 1 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(111, 2, '¿Quiénes son los actores principales de la serie "The Walking Dead"?', '{"respuestas": ["Andrew Lincoln", "Norman Reedus", "Danai Gurira", "Melissa McBride"], "respuestas_correctas": ["Andrew Lincoln", "Norman Reedus", "Danai Gurira", "Melissa McBride"]}', 'Andrew Lincoln interpreta a Rick Grimes, Norman Reedus interpreta a Daryl Dixon, Danai Gurira interpreta a Michonne y Melissa McBride interpreta a Carol Peletier en la serie "The Walking Dead".'),
(111, 2, '¿Cuáles son los actores que interpretaron a Sherlock Holmes en la película "Sherlock Holmes" de 2009?', '{"respuestas": ["Robert Downey Jr.", "Jude Law", "Benedict Cumberbatch", "Martin Freeman"], "respuestas_correctas": ["Robert Downey Jr.", "Jude Law"]}', 'Robert Downey Jr. interpretó a Sherlock Holmes y Jude Law interpretó al Dr. John Watson en la película "Sherlock Holmes".'),
(111, 2, '¿Quiénes son los protagonistas de la serie "Breaking Bad"?', '{"respuestas": ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"], "respuestas_correctas": ["Bryan Cranston", "Aaron Paul"]}', 'Bryan Cranston interpreta a Walter White y Aaron Paul interpreta a Jesse Pinkman en la serie "Breaking Bad".'),
(111, 2, '¿Cuáles son los actores principales de la película "Pulp Fiction"?', '{"respuestas": ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"], "respuestas_correctas": ["John Travolta", "Samuel L. Jackson"]}', 'John Travolta interpreta a Vincent Vega y Samuel L. Jackson interpreta a Jules Winnfield en la película "Pulp Fiction".'),
(111, 2, '¿Quiénes son los actores que protagonizan la serie "Stranger Things"?', '{"respuestas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"], "respuestas_correctas": ["Millie Bobby Brown", "Finn Wolfhard"]}', 'Millie Bobby Brown interpreta a Eleven y Finn Wolfhard interpreta a Mike Wheeler en la serie "Stranger Things".'),
(111, 2, '¿Cuáles son los actores que protagonizan la película "Titanic"?', '{"respuestas": ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"], "respuestas_correctas": ["Leonardo DiCaprio", "Kate Winslet"]}', 'Leonardo DiCaprio interpreta a Jack Dawson y Kate Winslet interpreta a Rose DeWitt Bukater en la película "Titanic".'),
(111, 2, '¿Quiénes son los actores principales de la serie "Friends"?', '{"respuestas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matthew Perry"], "respuestas_correctas": ["Jennifer Aniston", "Courteney Cox"]}', 'Jennifer Aniston interpreta a Rachel Green y Courteney Cox interpreta a Monica Geller en la serie "Friends".'),
(111, 2, '¿Cuáles son los actores que protagonizan la trilogía original de "Star Wars"?', '{"respuestas": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "James Earl Jones"], "respuestas_correctas": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"]}', 'Mark Hamill interpreta a Luke Skywalker, Harrison Ford interpreta a Han Solo y Carrie Fisher interpreta a Leia Organa en la trilogía original de "Star Wars".'),
(111, 2, '¿Quiénes son los actores principales de la serie "The Big Bang Theory"?', '{"respuestas": ["Jim Parsons", "Johnny Galecki", "Kaley Cuoco", "Simon Helberg"], "respuestas_correctas": ["Jim Parsons", "Johnny Galecki", "Kaley Cuoco"]}', 'Jim Parsons interpreta a Sheldon Cooper, Johnny Galecki interpreta a Leonard Hofstadter y Kaley Cuoco interpreta a Penny en la serie "The Big Bang Theory".'),
(111, 2, '¿Cuáles son los actores que protagonizan la película "Batman: El Caballero Oscuro"?', '{"respuestas": ["Christian Bale", "Heath Ledger", "Gary Oldman", "Morgan Freeman"], "respuestas_correctas": ["Christian Bale", "Heath Ledger"]}', 'Christian Bale interpreta a Batman y Heath Ledger interpreta a The Joker en la película "The Dark Knight".');

-- Preguntas para el test 2 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(112, 2, '¿Quiénes son los actores principales de la serie "Stranger Things"?', '{"respuestas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"], "respuestas_correctas": ["Millie Bobby Brown", "Finn Wolfhard"]}', 'Millie Bobby Brown interpreta a Eleven y Finn Wolfhard interpreta a Mike Wheeler en la serie "Stranger Things".'),
(112, 2, '¿Cuáles son los actores que protagonizan la película "El Señor de los Anillos: La Comunidad del Anillo"?', '{"respuestas": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Orlando Bloom"], "respuestas_correctas": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"]}', 'Elijah Wood interpreta a Frodo Baggins, Ian McKellen interpreta a Gandalf y Viggo Mortensen interpreta a Aragorn en la película "The Lord of the Rings: The Fellowship of the Ring".'),
(112, 2, '¿Quiénes son los actores principales de la serie "Breaking Bad"?', '{"respuestas": ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"], "respuestas_correctas": ["Bryan Cranston", "Aaron Paul"]}', 'Bryan Cranston interpreta a Walter White y Aaron Paul interpreta a Jesse Pinkman en la serie "Breaking Bad".'),
(112, 2, '¿Quiénes son los actores principales de la serie "Friends"?', '{"respuestas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matthew Perry"], "respuestas_correctas": ["Jennifer Aniston", "Courteney Cox"]}', 'Jennifer Aniston interpreta a Rachel Green y Courteney Cox interpreta a Monica Geller en la serie "Friends".'),
(112, 2, '¿Cuáles son los actores que protagonizan la película "Los Vengadores"?', '{"respuestas": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Scarlett Johansson"], "respuestas_correctas": ["Robert Downey Jr.", "Chris Evans"]}', 'Robert Downey Jr. interpreta a Iron Man y Chris Evans interpreta a Captain America en la película "The Avengers".'),
(112, 2, '¿Quiénes son los actores principales de la serie "Juego de Tronos"?', '{"respuestas": ["Kit Harington", "Emilia Clarke", "Peter Dinklage", "Maisie Williams"], "respuestas_correctas": ["Kit Harington", "Emilia Clarke"]}', 'Kit Harington interpreta a Jon Snow y Emilia Clarke interpreta a Daenerys Targaryen en la serie "Game of Thrones".'),
(112, 2, '¿Cuáles son los actores que protagonizan la película "El Gran Gatsby"?', '{"respuestas": ["Leonardo DiCaprio", "Tobey Maguire", "Carey Mulligan", "Joel Edgerton"], "respuestas_correctas": ["Leonardo DiCaprio", "Tobey Maguire", "Carey Mulligan"]}', 'Leonardo DiCaprio interpreta a Jay Gatsby, Tobey Maguire interpreta a Nick Carraway y Carey Mulligan interpreta a Daisy Buchanan en la película "The Great Gatsby".'),
(112, 2, '¿Cuáles son los actores que protagonizan la película "Matrix"?', '{"respuestas": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"], "respuestas_correctas": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]}', 'Keanu Reeves interpreta a Neo, Laurence Fishburne interpreta a Morpheus y Carrie-Anne Moss interpreta a Trinity en la película "The Matrix".'),
(112, 2, '¿Quiénes son los actores principales de la serie "The Walking Dead"?', '{"respuestas": ["Andrew Lincoln", "Norman Reedus", "Danai Gurira", "Melissa McBride"], "respuestas_correctas": ["Andrew Lincoln", "Norman Reedus"]}', 'Andrew Lincoln interpreta a Rick Grimes y Norman Reedus interpreta a Daryl Dixon en la serie "The Walking Dead".'),
(112, 2, '¿Cuáles son los actores que protagonizan la película "La La Land"?', '{"respuestas": ["Ryan Gosling", "Emma Stone", "John Legend", "J.K. Simmons"], "respuestas_correctas": ["Ryan Gosling", "Emma Stone"]}', 'Ryan Gosling interpreta a Sebastian y Emma Stone interpreta a Mia en la película "La La Land".');

-- Preguntas para el test 3 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(113, 2, '¿Cuáles son los actores que protagonizan la película "Los Vengadores: Endgame"?', '{"respuestas": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Scarlett Johansson"], "respuestas_correctas": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Scarlett Johansson"]}', 'Robert Downey Jr. interpreta a Iron Man, Chris Evans interpreta a Captain America, Chris Hemsworth interpreta a Thor y Scarlett Johansson interpreta a Black Widow en la película "The Avengers: Endgame".'),
(113, 2, '¿Quiénes son los actores principales de la serie "The Crown"?', '{"respuestas": ["Olivia Colman", "Tobias Menzies", "Helena Bonham Carter", "Josh O''Connor"], "respuestas_correctas": ["Olivia Colman", "Tobias Menzies", "Helena Bonham Carter", "Josh O''Connor"]}', 'Olivia Colman interpreta a la Reina Isabel II, Tobias Menzies interpreta al Príncipe Felipe, Helena Bonham Carter interpreta a la Princesa Margarita y Josh O''Connor interpreta al Príncipe Carlos en la serie "The Crown".'),
(113, 2, '¿Quiénes son los actores principales de la serie "Anatomía de Grey"?', '{"respuestas": ["Ellen Pompeo", "Patrick Dempsey", "Sandra Oh", "Katherine Heigl"], "respuestas_correctas": ["Ellen Pompeo", "Patrick Dempsey", "Sandra Oh"]}', 'Ellen Pompeo interpreta a Meredith Grey, Patrick Dempsey interpreta a Derek Shepherd y Sandra Oh interpreta a Cristina Yang en la serie "Anatomía de Grey".'),
(113, 2, '¿Cuáles son los actores que protagonizan la película "Cadena Perpetua"?', '{"respuestas": ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"], "respuestas_correctas": ["Tim Robbins", "Morgan Freeman"]}', 'Tim Robbins interpreta a Andy Dufresne y Morgan Freeman interpreta a Ellis Boyd "Red" Redding en la película "The Shawshank Redemption".'),
(113, 2, '¿Cuáles son los actores que protagonizan la película "El Club de la Lucha"?', '{"respuestas": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Jared Leto"], "respuestas_correctas": ["Brad Pitt", "Edward Norton"]}', 'Brad Pitt interpreta a Tyler Durden y Edward Norton interpreta al narrador sin nombre en la película "El Club de la Lucha".'),
(113, 2, '¿Cuáles son los actores que protagonizan la película "Pulp Fiction"?', '{"respuestas": ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"], "respuestas_correctas": ["John Travolta", "Samuel L. Jackson", "Uma Thurman"]}', 'John Travolta interpreta a Vincent Vega, Samuel L. Jackson interpreta a Jules Winnfield y Uma Thurman interpreta a Mia Wallace en la película "Pulp Fiction".'),
(113, 2, '¿Quiénes son los actores principales de la serie "The Office" (US)?', '{"respuestas": ["Steve Carell", "John Krasinski", "Rainn Wilson", "Jenna Fischer"], "respuestas_correctas": ["Steve Carell", "John Krasinski", "Rainn Wilson", "Jenna Fischer"]}', 'Steve Carell interpreta a Michael Scott, John Krasinski interpreta a Jim Halpert, Rainn Wilson interpreta a Dwight Schrute y Jenna Fischer interpreta a Pam Beesly en la serie "The Office" (US).'),
(113, 2, '¿Quiénes son los actores principales de la serie "Breaking Bad"?', '{"respuestas": ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"], "respuestas_correctas": ["Bryan Cranston", "Aaron Paul"]}', 'Bryan Cranston interpreta a Walter White y Aaron Paul interpreta a Jesse Pinkman en la serie "Breaking Bad".'),
(113, 2, '¿Cuáles son los actores que protagonizan la película "El Lobo de Wall Street"?', '{"respuestas": ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"], "respuestas_correctas": ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"]}', 'Leonardo DiCaprio interpreta a Jordan Belfort, Jonah Hill interpreta a Donnie Azoff y Margot Robbie interpreta a Naomi Lapaglia en la película "The Wolf of Wall Street".'),
(113, 2, '¿Quiénes son los actores principales de la serie "Stranger Things"?', '{"respuestas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"], "respuestas_correctas": ["Millie Bobby Brown", "Finn Wolfhard"]}', 'Millie Bobby Brown interpreta a Eleven y Finn Wolfhard interpreta a Mike Wheeler en la serie "Stranger Things".');


-- Preguntas para el test 4 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(114, 2, '¿Cuáles son los actores que protagonizan la película "Matrix"?', '{"respuestas": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"], "respuestas_correctas": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]}', 'Keanu Reeves interpreta a Neo, Laurence Fishburne interpreta a Morpheus y Carrie-Anne Moss interpreta a Trinity en la película "The Matrix".'),
(114, 2, '¿Quiénes son los actores principales de la serie "Friends"?', '{"respuestas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc"], "respuestas_correctas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc"]}', 'Jennifer Aniston interpreta a Rachel Green, Courteney Cox interpreta a Monica Geller, Lisa Kudrow interpreta a Phoebe Buffay y Matt LeBlanc interpreta a Joey Tribbiani en la serie "Friends".'),
(114, 2, '¿Cuáles son los actores que protagonizan la película "Los Infiltrados"?', '{"respuestas": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"], "respuestas_correctas": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"]}', 'Leonardo DiCaprio interpreta a Billy Costigan, Matt Damon interpreta a Colin Sullivan y Jack Nicholson interpreta a Frank Costello en la película "The Departed".'),
(114, 2, '¿Quiénes son los actores principales de la serie "Juego de Tronos"?', '{"respuestas": ["Emilia Clarke", "Kit Harington", "Peter Dinklage", "Lena Headey"], "respuestas_correctas": ["Emilia Clarke", "Kit Harington", "Peter Dinklage", "Lena Headey"]}', 'Emilia Clarke interpreta a Daenerys Targaryen, Kit Harington interpreta a Jon Snow, Peter Dinklage interpreta a Tyrion Lannister y Lena Headey interpreta a Cersei Lannister en la serie "Game of Thrones".'),
(114, 2, '¿Cuáles son los actores que protagonizan la película "La La Land"?', '{"respuestas": ["Ryan Gosling", "Emma Stone", "John Legend", "J.K. Simmons"], "respuestas_correctas": ["Ryan Gosling", "Emma Stone"]}', 'Ryan Gosling interpreta a Sebastian Wilder y Emma Stone interpreta a Mia Dolan en la película "La La Land".'),
(114, 2, '¿Quiénes son los actores principales de la serie "Breaking Bad"?', '{"respuestas": ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"], "respuestas_correctas": ["Bryan Cranston", "Aaron Paul"]}', 'Bryan Cranston interpreta a Walter White y Aaron Paul interpreta a Jesse Pinkman en la serie "Breaking Bad".'),
(114, 2, '¿Cuáles son los actores que protagonizan la película "Los Vengadores"?', '{"respuestas": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Scarlett Johansson"], "respuestas_correctas": ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Scarlett Johansson"]}', 'Robert Downey Jr. interpreta a Tony Stark/Iron Man, Chris Evans interpreta a Steve Rogers/Capitán América, Chris Hemsworth interpreta a Thor y Scarlett Johansson interpreta a Natasha Romanoff/Viuda Negra en la película "The Avengers".'),
(114, 2, '¿Cuáles son los actores principales de la película "Regreso al Futuro" (1985)?', '{"respuestas": ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"], "respuestas_correctas": ["Michael J. Fox", "Christopher Lloyd"]}', 'Michael J. Fox interpreta a Marty McFly y Christopher Lloyd interpreta al Dr. Emmett Brown en la película "Back to the Future".'),
(114, 2, '¿Quiénes son los actores principales de la película "El Club de los Cinco" (1985)?', '{"respuestas": ["Emilio Estevez", "Judd Nelson", "Molly Ringwald", "Anthony Michael Hall"], "respuestas_correctas": ["Emilio Estevez", "Judd Nelson", "Molly Ringwald", "Anthony Michael Hall"]}', 'Emilio Estevez interpreta a Andrew Clark, Judd Nelson interpreta a John Bender, Molly Ringwald interpreta a Claire Standish y Anthony Michael Hall interpreta a Brian Johnson en la película "El Club de los Cinco".'),
(114, 2, '¿Cuáles son los actores que protagonizan la película "Cazafantasmas" (1984)?', '{"respuestas": ["Bill Murray", "Dan Aykroyd", "Harold Ramis", "Sigourney Weaver"], "respuestas_correctas": ["Bill Murray", "Dan Aykroyd", "Harold Ramis"]}', 'Bill Murray interpreta a Peter Venkman, Dan Aykroyd interpreta a Ray Stantz y Harold Ramis interpreta a Egon Spengler en la película "Ghostbusters".');


-- Preguntas para el test 5 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(115, 2, '¿Cuáles son los actores principales de la película "Pulp Fiction" (1994)?', '{"respuestas": ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"], "respuestas_correctas": ["John Travolta", "Samuel L. Jackson", "Uma Thurman"]}', 'John Travolta interpreta a Vincent Vega, Samuel L. Jackson interpreta a Jules Winnfield y Uma Thurman interpreta a Mia Wallace en la película "Pulp Fiction".'),
(115, 2, '¿Quiénes son los actores principales de la película "Titanic" (1997)?', '{"respuestas": ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"], "respuestas_correctas": ["Leonardo DiCaprio", "Kate Winslet"]}', 'Leonardo DiCaprio interpreta a Jack Dawson y Kate Winslet interpreta a Rose DeWitt Bukater en la película "Titanic".'),
(115, 2, '¿Quiénes son los actores principales de la película "Forrest Gump" (1994)?', '{"respuestas": ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"], "respuestas_correctas": ["Tom Hanks", "Robin Wright"]}', 'Tom Hanks interpreta a Forrest Gump y Robin Wright interpreta a Jenny Curran en la película "Forrest Gump".'),
(115, 2, '¿Quiénes son los actores principales de la película "El Indomable Will Hunting" (1997)?', '{"respuestas": ["Matt Damon", "Robin Williams", "Ben Affleck", "Minnie Driver"], "respuestas_correctas": ["Matt Damon", "Robin Williams"]}', 'Matt Damon interpreta a Will Hunting y Robin Williams interpreta a Sean Maguire en la película "Good Will Hunting".'),
(115, 2, '¿Cuál es el actor principal de la película "El Padrino" lanzada en 1972?', '{"respuestas": ["Al Pacino", "Robert De Niro", "Marlon Brando", "Joe Pesci"], "respuestas_correctas": ["Marlon Brando"]}', 'Marlon Brando fue el actor principal de la película "El Padrino".'),
(115, 2, '¿Quiénes son los actores principales de la serie de televisión "Friends" que se emitió entre 1994 y 2004?', '{"respuestas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matthew Perry"], "respuestas_correctas": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matthew Perry"]}', 'Los actores principales de la serie "Friends" son Jennifer Aniston, Courteney Cox, Lisa Kudrow y Matthew Perry.'),
(115, 2, '¿Cuál es el nombre del personaje principal de la película "El Rey León" lanzada en 1994?', '{"respuestas": ["Simba", "Mufasa", "Scar", "Nala"], "respuestas_correctas": ["Simba"]}', 'El personaje principal de la película "El Rey León" es Simba.'),
(115, 2, '¿Quiénes son los personajes principales de la serie de anime "Dragon Ball Z" que se emitió entre 1989 y 1996?', '{"respuestas": ["Goku", "Vegeta", "Gohan", "Piccolo"], "respuestas_correctas": ["Goku", "Vegeta", "Gohan", "Piccolo"]}', 'Los personajes principales de la serie de anime "Dragon Ball Z" son Goku, Vegeta, Gohan y Piccolo.'),
(115, 2, '¿Quiénes son los actores principales de la película "E.T. the Extraterrestre" (1982)?', '{"respuestas": ["Henry Thomas", "Drew Barrymore", "Dee Wallace", "Peter Coyote"], "respuestas_correctas": ["Henry Thomas", "Drew Barrymore"]}', 'Henry Thomas interpreta a Elliott y Drew Barrymore interpreta a Gertie en la película "E.T. the Extra-Terrestrial".'),
(115, 2, '¿Quiénes son los personajes principales de la serie de televisión "Los Simpson" que se estrenó en 1989?', '{"respuestas": ["Homer Simpson", "Marge Simpson", "Bart Simpson", "Lisa Simpson"], "respuestas_correctas": ["Homer Simpson", "Marge Simpson", "Bart Simpson", "Lisa Simpson"]}', 'Los personajes principales de la serie "Los Simpson" son Homer Simpson, Marge Simpson, Bart Simpson y Lisa Simpson.');

-- Preguntas para el test 6 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(116, 2, '¿Cuál es el nombre del actor principal de la película "Forrest Gump" lanzada en 1994?', '{"respuestas": ["Tom Hanks", "Brad Pitt", "Leonardo DiCaprio", "Johnny Depp"], "respuestas_correctas": ["Tom Hanks"]}', 'El actor principal de la película "Forrest Gump" es Tom Hanks.'),
(116, 2, '¿Cuáles son los actores que protagonizan la película "The Princesa Prometida" (1987)?', '{"respuestas": ["Cary Elwes", "Robin Wright", "Mandy Patinkin", "Billy Crystal"], "respuestas_correctas": ["Cary Elwes", "Robin Wright"]}', 'Cary Elwes interpreta a Westley y Robin Wright interpreta a Buttercup en la película "The Princess Bride".'),
(116, 2, '¿Quiénes son los actores principales de la película "Jungla de Cristal" (1988)?', '{"respuestas": ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia", "Reginald VelJohnson"], "respuestas_correctas": ["Bruce Willis", "Alan Rickman"]}', 'Bruce Willis interpreta a John McClane y Alan Rickman interpreta a Hans Gruber en la película "Die Hard".'),
(116, 2, '¿Cuál es el nombre del actor principal de la película "Indiana Jones y los Cazadores del Arca Perdida" lanzada en 1981?', '{"respuestas": ["Harrison Ford", "Sean Connery", "Michael Douglas", "Mel Gibson"], "respuestas_correctas": ["Harrison Ford"]}', 'Harrison Ford es el actor principal de la película "Indiana Jones y los cazadores del arca perdida".'),
(116, 2, '¿Quiénes son los actores principales de la serie de televisión "El Príncipe de Bel-Air" que se emitió entre 1990 y 1996?', '{"respuestas": ["Will Smith", "Alfonso Ribeiro", "James Avery", "Tatyana Ali"], "respuestas_correctas": ["Will Smith", "Alfonso Ribeiro", "James Avery", "Tatyana Ali"]}', 'Los actores principales de la serie "El Príncipe del Rap" son Will Smith, Alfonso Ribeiro, James Avery y Tatyana Ali.'),
(116, 2, '¿Cuál es el nombre del personaje principal de la película "Blade Runner" lanzada en 1982?', '{"respuestas": ["Rick Deckard", "Roy Batty", "Pris Stratton", "Rachael"], "respuestas_correctas": ["Rick Deckard"]}', 'El personaje principal de la película "Blade Runner" es Rick Deckard.'),
(116, 2, '¿Quiénes son los personajes principales de la serie de anime "Sailor Moon" que se emitió entre 1992 y 1997?', '{"respuestas": ["Usagi Tsukino", "Ami Mizuno", "Rei Hino", "Makoto Kino"], "respuestas_correctas": ["Usagi Tsukino", "Ami Mizuno", "Rei Hino", "Makoto Kino"]}', 'Los personajes principales de la serie de anime "Sailor Moon" son Usagi Tsukino, Ami Mizuno, Rei Hino y Makoto Kino.'),
(116, 2, '¿Cuál es el nombre del actor principal de la película "Top Gun" lanzada en 1986?', '{"respuestas": ["Tom Cruise", "Val Kilmer", "Charlie Sheen", "Kevin Costner"], "respuestas_correctas": ["Tom Cruise"]}', 'El actor principal de la película "Top Gun" es Tom Cruise.'),
(116, 2, '¿Que actores protagonizaron la película de "Regreso al Futuro" de 1985?', '{"respuestas": ["Michael J. Fox", "Julia Roberts", "Christopher Lloyd", "Tom Hanks"], "respuestas_correctas": ["Michael J. Fox", "Christopher Lloyd"]}', 'Michael J. Fox - Interpretó al personaje principal, Marty McFly. Christopher Lloyd - Interpretó al Dr. Emmett Brown.'),
(116, 2, '¿Quiénes son los personajes principales de la serie de televisión "MASH" que se emitió entre 1972 y 1983?', '{"respuestas": ["Hawkeye Pierce", "Trapper John McIntyre", "Radar O''Reilly", "Margaret Houlihan"], "respuestas_correctas": ["Hawkeye Pierce", "Trapper John McIntyre", "Radar O''Reilly", "Margaret Houlihan"]}', 'Los personajes principales de la serie "MASH" son Hawkeye Pierce, Trapper John McIntyre, Radar O''Reilly y Margaret Houlihan.');

-- Preguntas para el test 7 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(117, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la película "Origen" lanzada en 2010?', '{"respuestas": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Tom Hardy", "Ellen Page"], "respuestas_correctas": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Tom Hardy"]}', 'Los actores Leonardo DiCaprio, Joseph Gordon-Levitt y Tom Hardy interpretaron a los personajes principales en la película "Inception".'),
(117, 2, 'En la serie de anime "Attack on Titan" emitida entre 2013 y 2021, ¿cuáles de los siguientes personajes son miembros del Escuadrón de Exploración?', '{"respuestas": ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman"], "respuestas_correctas": ["Eren Yeager", "Mikasa Ackerman", "Armin Arlert", "Levi Ackerman"]}', 'Los personajes Eren Yeager, Mikasa Ackerman, Armin Arlert y Levi Ackerman son miembros del Escuadrón de Exploración en la serie de anime "Attack on Titan".'),
(117, 2, '¿Cuáles de los siguientes actores protagonizaron la serie de televisión "Stranger Things" que se estrenó en 2016?', '{"respuestas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"], "respuestas_correctas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"]}', 'Los actores Millie Bobby Brown, Finn Wolfhard y Winona Ryder protagonizaron la serie de televisión "Stranger Things".'),
(117, 2, '¿Cuál de las siguientes películas ganó el premio a la Mejor Película en los Premios de la Academia (Oscar) en el año 2019?', '{"respuestas": ["Parásitos", "1917", "Joker", "Érase una vez en... Hollywood"], "respuestas_correctas": ["Parásitos"]}', 'La película "Parásitos" ganó el premio a la Mejor Película en los Premios de la Academia en 2019.'),
(117, 2, 'En la serie de televisión "Friends", ¿cuál es el nombre del café al que los personajes suelen reunirse?', '{"respuestas": ["Central Perk", "Central Park", "Coffee Central", "Perk Central"], "respuestas_correctas": ["Central Perk"]}', 'El café al que los personajes de "Friends" suelen reunirse se llama "Central Perk".'),
(117, 2, '¿Cuál de las siguientes series de anime fue adaptada de un manga creado por Hajime Isayama?', '{"respuestas": ["Attack on Titan", "One Punch Man", "Naruto", "Death Note"], "respuestas_correctas": ["Attack on Titan"]}', 'La serie de anime "Attack on Titan" fue adaptada del manga creado por Hajime Isayama.'),
(117, 2, '¿Cuál de los siguientes actores interpretó al icónico personaje de Harry Potter en la serie de películas basadas en los libros de J.K. Rowling?', '{"respuestas": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Tom Felton"], "respuestas_correctas": ["Daniel Radcliffe"]}', 'El actor Daniel Radcliffe interpretó al personaje de Harry Potter en la serie de películas basadas en los libros de J.K. Rowling.'),
(117, 2, 'En la serie de televisión "Breaking Bad", ¿cuál es el nombre del personaje principal que se convierte en un fabricante y distribuidor de metanfetaminas?', '{"respuestas": ["Walter White", "Jesse Pinkman", "Saul Goodman", "Hank Schrader"], "respuestas_correctas": ["Walter White"]}', 'El nombre del personaje principal en "Breaking Bad" que se convierte en un fabricante y distribuidor de metanfetaminas es Walter White.'),
(117, 2, '¿Cuál de las siguientes películas fue dirigida por Christopher Nolan?', '{"respuestas": ["Origen", "Los Vengadores", "La La Land", "Batman: El Caballero Oscuro"], "respuestas_correctas": ["Origen", "Batman: El Caballero Oscuro"]}', 'Christopher Nolan dirigió las películas "Origen" y "Batman: El Caballero Oscuro".'),
(117, 2, 'En la serie de anime "One Piece", ¿cuál es el nombre del protagonista que busca el tesoro conocido como "One Piece"?', '{"respuestas": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Sanji"], "respuestas_correctas": ["Monkey D. Luffy"]}', 'El nombre del protagonista en "One Piece" que busca el tesoro "One Piece" es Monkey D. Luffy.');


-- Preguntas para el test 8 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(118, 2, '¿Cuáles son los actores que protagonizan la serie "Stranger Things"?', '{"respuestas": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"], "respuestas_correctas": ["Millie Bobby Brown", "Finn Wolfhard"]}', 'Millie Bobby Brown interpreta a Eleven y Finn Wolfhard interpreta a Mike Wheeler en la serie "Stranger Things".'),
(118, 2, '¿Cuáles son los actores que protagonizan la película "El Club de la Lucha"?', '{"respuestas": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"], "respuestas_correctas": ["Brad Pitt", "Edward Norton"]}', 'Brad Pitt interpreta a Tyler Durden y Edward Norton interpreta al Narrador en la película "El Club de la Lucha".'),
(118, 2, '¿Cuáles son los actores que protagonizan la película "Cadena Perpetua"?', '{"respuestas": ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"], "respuestas_correctas": ["Tim Robbins", "Morgan Freeman"]}', 'Tim Robbins interpreta a Andy Dufresne y Morgan Freeman interpreta a Ellis Boyd "Red" Redding en la película "The Shawshank Redemption".'),
(118, 2, '¿Cuáles de las siguientes películas forman parte del Universo Cinematográfico de Marvel (MCU)?', '{"respuestas": ["Iron Man", "Batman: El Caballero Oscuro", "Spider-Man: Homecoming", "Wonder Woman"], "respuestas_correctas": ["Iron Man", "Spider-Man: Homecoming"]}', 'Las películas "Iron Man" y "Spider-Man: Homecoming" forman parte del Universo Cinematográfico de Marvel.'),
(118, 2, 'En la serie de televisión "Game of Thrones", ¿cuáles de los siguientes personajes son miembros de la Casa Stark?', '{"respuestas": ["Jon Snow", "Daenerys Targaryen", "Tyrion Lannister", "Arya Stark"], "respuestas_correctas": ["Jon Snow", "Arya Stark"]}', 'Los personajes Jon Snow y Arya Stark son miembros de la Casa Stark en la serie "Game of Thrones".'),
(118, 2, '¿Cuáles de las siguientes series de anime fueron adaptadas de mangas creados por Masashi Kishimoto?', '{"respuestas": ["Naruto", "Attack on Titan", "Dragon Ball", "One Piece"], "respuestas_correctas": ["Naruto"]}', 'La serie de anime "Naruto" fue adaptada del manga creado por Masashi Kishimoto.'),
(118, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la serie de películas de "El Señor de los Anillos"?', '{"respuestas": ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom"], "respuestas_correctas": ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"]}', 'Los actores Elijah Wood, Viggo Mortensen e Ian McKellen interpretaron a los personajes principales en la serie de películas de "The Lord of the Rings".'),
(118, 2, 'En la serie de televisión "Stranger Things", ¿cuáles de los siguientes personajes son parte del grupo de amigos conocido como "Los Chicos"?', '{"respuestas": ["Mike Wheeler", "Eleven", "Joyce Byers", "Max Mayfield"], "respuestas_correctas": ["Mike Wheeler", "Eleven"]}', 'Los personajes Mike Wheeler y Eleven son parte del grupo de amigos conocido como "Los Chicos" en la serie "Stranger Things".'),
(118, 2, '¿Cuáles de las siguientes películas fueron dirigidas por Quentin Tarantino?', '{"respuestas": ["Pulp Fiction", "Cadena Perpetua", "Matrix", "El Club de la Lucha"], "respuestas_correctas": ["Pulp Fiction"]}', 'La película "Pulp Fiction" fue dirigida por Quentin Tarantino.'),
(118, 2, '¿Cuáles de las siguientes series de anime se basan en mangas creados por Rumiko Takahashi?', '{"respuestas": ["Inuyasha", "Attack on Titan", "Naruto", "One Piece"], "respuestas_correctas": ["Inuyasha"]}', 'La serie de anime "Inuyasha" se basa en el manga creado por Rumiko Takahashi.');

-- Preguntas para el test 9 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(119, 2, '¿Cuáles de las siguientes películas ganaron el premio a la Mejor Película en los Premios de la Academia (Oscar) en los últimos 10 años?', '{"respuestas": ["La Forma del Agua", "La La Land", "Moonlight", "Birdman"], "respuestas_correctas": ["La Forma del Agua", "Moonlight"]}', 'Las películas "La Forma del Agua" y "Moonlight" ganaron el premio a la Mejor Película en los Premios de la Academia en los últimos 10 años.'),
(119, 2, 'En la serie de televisión "Stranger Things", ¿cuáles de los siguientes personajes tienen habilidades sobrenaturales?', '{"respuestas": ["Eleven", "Mike Wheeler", "Joyce Byers", "Nancy Wheeler"], "respuestas_correctas": ["Eleven"]}', 'El personaje Eleven es el único que tiene habilidades sobrenaturales en la serie "Stranger Things".'),
(119, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la serie de películas de "The Hunger Games"?', '{"respuestas": ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Emma Stone"], "respuestas_correctas": ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"]}', 'Los actores Jennifer Lawrence, Josh Hutcherson y Liam Hemsworth interpretaron a los personajes principales en la serie de películas de "The Hunger Games".'),
(119, 2, 'En la serie de televisión "The Walking Dead", ¿cuáles de los siguientes personajes son líderes de diferentes grupos de sobrevivientes?', '{"respuestas": ["Rick Grimes", "Daryl Dixon", "Carol Peletier", "Maggie Greene"], "respuestas_correctas": ["Rick Grimes", "Carol Peletier", "Maggie Greene"]}', 'Los personajes Rick Grimes, Carol Peletier y Maggie Greene son líderes de diferentes grupos de sobrevivientes en la serie "The Walking Dead".'),
(119, 2, '¿Cuáles de las siguientes películas fueron dirigidas por Steven Spielberg?', '{"respuestas": ["Jurassic Park", "Los Vengadores", "Batman: El Caballero Oscuro", "Titanic"], "respuestas_correctas": ["Jurassic Park"]}', 'La película "Jurassic Park" fue dirigida por Steven Spielberg.'),
(119, 2, '¿Cuál de las siguientes películas ganó el premio a la Mejor Película en los Premios de la Academia (Oscar) en el año 2000?', '{"respuestas": ["Gladiator", "El Señor de los Anillos: La Comunidad del Anillo", "Una Mente Maravillosa", "Chicago"], "respuestas_correctas": ["Gladiator"]}', 'La película "Gladiator" ganó el premio a la Mejor Película en los Premios de la Academia en el año 2000.'),
(119, 2, 'En la serie de televisión "Friends", ¿cuáles de los siguientes personajes están hermanados por matrimonio?', '{"respuestas": ["Monica Geller y Chandler Bing", "Rachel Green y Ross Geller", "Joey Tribbiani y Phoebe Buffay", "Gunther y Janice"], "respuestas_correctas": ["Monica Geller y Chandler Bing"]}', 'Los personajes Monica Geller y Chandler Bing están hermanados por matrimonio en la serie "Friends".'),
(119, 2, '¿Cuál de las siguientes series de anime fue adaptada de un manga creado por Eiichiro Oda?', '{"respuestas": ["One Piece", "Attack on Titan", "Naruto", "Death Note"], "respuestas_correctas": ["One Piece"]}', 'La serie de anime "One Piece" fue adaptada del manga creado por Eiichiro Oda.'),
(119, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la serie de películas de "Matrix"?', '{"respuestas": ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne", "Hugo Weaving"], "respuestas_correctas": ["Keanu Reeves", "Carrie-Anne Moss", "Laurence Fishburne"]}', 'Los actores Keanu Reeves, Carrie-Anne Moss y Laurence Fishburne interpretaron a los personajes principales en la serie de películas de "The Matrix".'),
(119, 2, 'En la serie de televisión "Friends", ¿cuáles de los siguientes personajes son vecinos de los protagonistas en el edificio de enfrente?', '{"respuestas": ["Janice", "Ursula", "Emily", "Gunther"], "respuestas_correctas": ["Janice", "Ursula"]}', 'Los personajes Janice y Ursula son vecinos de los protagonistas en el edificio de enfrente en la serie "Friends".');

-- Preguntas para el test 10 de Artes Visuales
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(120, 2, '¿Cuál de las siguientes películas fue dirigida por Martin Scorsese?', '{"respuestas": ["Uno de los Nuestros", "Los Vengadores", "La La Land", "Titanic"], "respuestas_correctas": ["Uno de los Nuestros"]}', 'La película "Uno de los Nuestros" fue dirigida por Martin Scorsese.'),
(120, 2, '¿Cuál de las siguientes películas ganó el premio a la Mejor Película en los Premios de la Academia (Oscar) en el año 1994?', '{"respuestas": ["Forrest Gump", "Pulp Fiction", "Cadena Perpetua", "Braveheart"], "respuestas_correctas": ["Forrest Gump"]}', 'La película "Forrest Gump" ganó el premio a la Mejor Película en los Premios de la Academia en el año 1994.'),
(120, 2, 'En la serie de televisión "Breaking Bad", ¿cuáles de los siguientes personajes son miembros del cartel de drogas de Juarez?', '{"respuestas": ["Gustavo Fring", "Hector Salamanca", "Tuco Salamanca", "Walter White"], "respuestas_correctas": ["Gustavo Fring", "Hector Salamanca", "Tuco Salamanca"]}', 'Los personajes Gustavo Fring, Hector Salamanca y Tuco Salamanca son miembros del cartel de drogas de Juarez en la serie "Breaking Bad".'),
(120, 2, '¿Cuál de las siguientes series de anime fue adaptada de un manga creado por Gosho Aoyama?', '{"respuestas": ["Detective Conan", "One Piece", "Attack on Titan", "Naruto"], "respuestas_correctas": ["Detective Conan"]}', 'La serie de anime "Detective Conan" fue adaptada del manga creado por Gosho Aoyama.'),
(120, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la serie de películas de "Regreso al Futuro"?', '{"respuestas": ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Tom Cruise"], "respuestas_correctas": ["Michael J. Fox", "Christopher Lloyd"]}', 'Los actores Michael J. Fox y Christopher Lloyd interpretaron a los personajes principales en la serie de películas de "Back to the Future".'),
(120, 2, 'En la serie de televisión "The Big Bang Theory", ¿cuáles de los siguientes personajes son científicos?', '{"respuestas": ["Sheldon Cooper", "Leonard Hofstadter", "Rajesh Koothrappali", "Penny"], "respuestas_correctas": ["Sheldon Cooper", "Leonard Hofstadter", "Rajesh Koothrappali"]}', 'Los personajes Sheldon Cooper, Leonard Hofstadter y Rajesh Koothrappali son científicos en la serie "The Big Bang Theory".'),
(120, 2, '¿Cuál de las siguientes películas fue dirigida por Stanley Kubrick?', '{"respuestas": ["A Clockwork Orange", "The Avengers", "La La Land", "Titanic"], "respuestas_correctas": ["A Clockwork Orange"]}', 'La película "A Clockwork Orange" fue dirigida por Stanley Kubrick.'),
(120, 2, '¿Cuál de las siguientes películas ganó el premio a la Mejor Película en los Premios de la Academia (Oscar) en el año 1985?', '{"respuestas": ["Amadeus", "El Color Púrpura", "Memorias de Africa", "Platoon"], "respuestas_correctas": ["Amadeus"]}', 'La película "Amadeus" ganó el premio a la Mejor Película en los Premios de la Academia en el año 1985.'),
(120, 2, 'En la serie de televisión "The Office" (versión estadounidense), ¿cuáles de los siguientes personajes son miembros del departamento de ventas?', '{"respuestas": ["Jim Halpert", "Pam Beesly", "Dwight Schrute", "Ryan Howard"], "respuestas_correctas": ["Jim Halpert", "Ryan Howard"]}', 'Los personajes Jim Halpert y Ryan Howard son miembros del departamento de ventas en la serie "The Office".'),
(120, 2, '¿Cuáles de los siguientes actores interpretaron a los personajes principales en la serie de películas de "Harry Potter"?', '{"respuestas": ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Tom Hanks"], "respuestas_correctas": ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"]}', 'Los actores Daniel Radcliffe, Emma Watson y Rupert Grint interpretaron a los personajes principales en la serie de películas de "Harry Potter".');

-- Renumera el id de PREGUNTAS
SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;