-- Datos para la tabla TESTS para los test de Filosofía del tipo tipo de pregunta 2 multiples respuestas
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(10, 'Filosofía 01', 'Test 01 sobre la materia de Filosofía de multiples respuestas.', 1),
(10, 'Filosofía 02', 'Test 02 sobre la materia de Filosofía de multiples respuestas.', 1),
(10, 'Filosofía 03', 'Test 03 sobre la materia de Filosofía de multiples respuestas.', 1),
(10, 'Filosofía 04', 'Test 04 sobre la materia de Filosofía de multiples respuestas.', 1),
(10, 'Filosofía 05', 'Test 05 sobre la materia de Filosofía de multiples respuestas.', 1);

-- Datos para la tabla TESTS para los test de Filosofía del tipo tipo de pregunta 1 respuesta única
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(10, 'Filosofía 06', 'Test 06 sobre la materia de Filosofía de respuesta única.', 1),
(10, 'Filosofía 07', 'Test 07 sobre la materia de Filosofía de respuesta única.', 1),
(10, 'Filosofía 08', 'Test 08 sobre la materia de Filosofía de respuesta única.', 1),
(10, 'Filosofía 09', 'Test 09 sobre la materia de Filosofía de respuesta única.', 1),
(10, 'Filosofía 10', 'Test 10 sobre la materia de Filosofía de respuesta única.', 1);

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Filosofía" para el tipo de pregunta 2 multiples respuestas

-- Preguntas para el test 1 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(141, 2, '¿Cuáles de los siguientes filósofos pertenecieron a la corriente del existencialismo?', '{"respuestas": ["Søren Kierkegaard", "Friedrich Nietzsche", "Immanuel Kant", "John Locke"], "respuestas_correctas": ["Søren Kierkegaard", "Friedrich Nietzsche"]}', 'Los filósofos que pertenecieron a la corriente del existencialismo son Søren Kierkegaard y Friedrich Nietzsche.'),
(141, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la ética?', '{"respuestas": ["Utilitarismo", "Escepticismo", "Positivismo lógico", "Materialismo dialéctico"], "respuestas_correctas": ["Utilitarismo", "Escepticismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la ética son el Utilitarismo y el Escepticismo.'),
(141, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la realidad y la percepción?', '{"respuestas": ["Idealismo", "Existencialismo", "Pragmatismo", "Escepticismo"], "respuestas_correctas": ["Idealismo", "Escepticismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la realidad y la percepción son el Idealismo y el Escepticismo.'),
(141, 2, '¿Cuáles de los siguientes filósofos son considerados precursores del pensamiento político?', '{"respuestas": ["Platón", "Aristóteles", "Sócrates", "Epicuro"], "respuestas_correctas": ["Platón", "Aristóteles", "Sócrates"]}', 'Los filósofos considerados precursores del pensamiento político son Platón, Aristóteles y Sócrates.'),
(141, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento político?', '{"respuestas": ["Thomas Hobbes", "John Locke", "Jean-Jacques Rousseau", "Immanuel Kant"], "respuestas_correctas": ["Thomas Hobbes", "John Locke", "Jean-Jacques Rousseau"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento político son Thomas Hobbes, John Locke y Jean-Jacques Rousseau.'),
(141, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento nihilista?', '{"respuestas": ["Friedrich Nietzsche", "Arthur Schopenhauer", "Søren Kierkegaard", "Jean-Paul Sartre"], "respuestas_correctas": ["Friedrich Nietzsche", "Arthur Schopenhauer"]}', 'Los filósofos considerados representantes del pensamiento nihilista son Friedrich Nietzsche y Arthur Schopenhauer.'),
(141, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento feminista?', '{"respuestas": ["Simone de Beauvoir", "Judith Butler", "John Locke", "René Descartes"], "respuestas_correctas": ["Simone de Beauvoir", "Judith Butler"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento feminista son Simone de Beauvoir y Judith Butler.'),
(141, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la verdad y el conocimiento?', '{"respuestas": ["Racionalismo", "Pragmatismo", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": ["Racionalismo", "Escepticismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la verdad y el conocimiento son el Racionalismo y el Escepticismo.'),
(141, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento humanista?', '{"respuestas": ["Jean-Paul Sartre", "Albert Camus", "Martin Heidegger", "Friedrich Nietzsche"], "respuestas_correctas": ["Jean-Paul Sartre", "Albert Camus"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento humanista son Jean-Paul Sartre y Albert Camus.'),
(141, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la razón y el conocimiento?', '{"respuestas": ["Racionalismo", "Empirismo", "Positivismo lógico", "Materialismo dialéctico"], "respuestas_correctas": ["Racionalismo", "Empirismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la razón y el conocimiento son el Racionalismo y el Empirismo.');

-- Preguntas para el test 2 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(142, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento humanista?', '{"respuestas": ["Jean-Paul Sartre", "Albert Camus", "Martin Heidegger", "Friedrich Nietzsche"], "respuestas_correctas": ["Jean-Paul Sartre", "Albert Camus"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento humanista son Jean-Paul Sartre y Albert Camus.'),
(142, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la razón y el conocimiento?', '{"respuestas": ["Racionalismo", "Empirismo", "Positivismo lógico", "Materialismo dialéctico"], "respuestas_correctas": ["Racionalismo", "Empirismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la razón y el conocimiento son el Racionalismo y el Empirismo.'),
(142, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento existencialista?', '{"respuestas": ["Friedrich Nietzsche", "Jean-Paul Sartre", "Søren Kierkegaard", "Albert Camus"], "respuestas_correctas": ["Jean-Paul Sartre", "Søren Kierkegaard", "Albert Camus"]}', 'Los filósofos considerados representantes del pensamiento existencialista son Jean-Paul Sartre, Søren Kierkegaard y Albert Camus.'),
(142, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la ética y la moralidad?', '{"respuestas": ["Ética normativa", "Utilitarismo", "Positivismo lógico", "Escepticismo"], "respuestas_correctas": ["Ética normativa", "Utilitarismo"]}', 'Las corrientes filosóficas que se centran en el estudio de la ética y la moralidad son la Ética normativa y el Utilitarismo.'),
(142, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento postestructuralista?', '{"respuestas": ["Michel Foucault", "Jacques Derrida", "Gilles Deleuze", "Simone de Beauvoir"], "respuestas_correctas": ["Michel Foucault", "Jacques Derrida", "Gilles Deleuze"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento postestructuralista son Michel Foucault, Jacques Derrida y Gilles Deleuze.'),
(142, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la realidad y la percepción?', '{"respuestas": ["Fenomenología", "Idealismo", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": ["Fenomenología", "Idealismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la realidad y la percepción son la Fenomenología y el Idealismo.'),
(142, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento pragmático?', '{"respuestas": ["William James", "John Dewey", "Charles Sanders Peirce", "Friedrich Nietzsche"], "respuestas_correctas": ["William James", "John Dewey", "Charles Sanders Peirce"]}', 'Los filósofos considerados representantes del pensamiento pragmático son William James, John Dewey y Charles Sanders Peirce.'),
(142, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento utilitarista?', '{"respuestas": ["John Stuart Mill", "Jeremy Bentham", "Immanuel Kant"], "respuestas_correctas": ["John Stuart Mill", "Jeremy Bentham"]}', 'Los filósofos considerados representantes del pensamiento utilitarista son John Stuart Mill y Jeremy Bentham.'),
(142, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento fenomenológico?', '{"respuestas": ["Edmund Husserl", "Martin Heidegger", "Jean-Paul Sartre"], "respuestas_correctas": ["Edmund Husserl", "Martin Heidegger"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento fenomenológico son Edmund Husserl y Martin Heidegger.'),
(142, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento estructuralista?', '{"respuestas": ["Ferdinand de Saussure", "Claude Lévi-Strauss", "Jacques Lacan"], "respuestas_correctas": ["Ferdinand de Saussure", "Claude Lévi-Strauss"]}', 'Los filósofos considerados representantes del pensamiento estructuralista son Ferdinand de Saussure y Claude Lévi-Strauss.');

-- Preguntas para el test 3 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(143, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento postmodernista?', '{"respuestas": ["Jean-François Lyotard", "Michel Foucault", "Immanuel Kant", "Georg Wilhelm Friedrich Hegel"], "respuestas_correctas": ["Jean-François Lyotard", "Michel Foucault"]}', 'Los filósofos considerados representantes del pensamiento postmodernista son Jean-François Lyotard y Michel Foucault.'),
(143, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento dialéctico?', '{"respuestas": ["Georg Wilhelm Friedrich Hegel", "Karl Marx", "Friedrich Nietzsche"], "respuestas_correctas": ["Georg Wilhelm Friedrich Hegel", "Karl Marx"]}', 'Los filósofos considerados representantes del pensamiento dialéctico son Georg Wilhelm Friedrich Hegel y Karl Marx.'),
(143, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento feminista?', '{"respuestas": ["Simone de Beauvoir", "Judith Butler", "Gloria Anzaldúa"], "respuestas_correctas": ["Simone de Beauvoir", "Judith Butler"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento feminista son Simone de Beauvoir y Judith Butler.'),
(143, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la realidad y la apariencia?', '{"respuestas": ["Fenomenalismo", "Escepticismo", "Idealismo"], "respuestas_correctas": ["Fenomenalismo", "Idealismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la realidad y la apariencia son el Fenomenalismo y el Idealismo.'),
(143, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento hermenéutico?', '{"respuestas": ["Hans-Georg Gadamer", "Paul Ricoeur", "Martin Heidegger"], "respuestas_correctas": ["Hans-Georg Gadamer", "Paul Ricoeur"]}', 'Los filósofos considerados representantes del pensamiento hermenéutico son Hans-Georg Gadamer y Paul Ricoeur.'),
(143, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento existencialista?', '{"respuestas": ["Friedrich Nietzsche", "Jean-Paul Sartre", "Søren Kierkegaard", "Albert Camus"], "respuestas_correctas": ["Jean-Paul Sartre", "Søren Kierkegaard", "Albert Camus"]}', 'Los filósofos considerados representantes del pensamiento existencialista son Jean-Paul Sartre, Søren Kierkegaard y Albert Camus.'),
(143, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la ética y la moralidad?', '{"respuestas": ["Ética normativa", "Utilitarismo", "Positivismo lógico", "Escepticismo"], "respuestas_correctas": ["Ética normativa", "Utilitarismo"]}', 'Las corrientes filosóficas que se centran en el estudio de la ética y la moralidad son la Ética normativa y el Utilitarismo.'),
(143, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento postestructuralista?', '{"respuestas": ["Michel Foucault", "Jacques Derrida", "Gilles Deleuze", "Simone de Beauvoir"], "respuestas_correctas": ["Michel Foucault", "Jacques Derrida", "Gilles Deleuze"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento postestructuralista son Michel Foucault, Jacques Derrida y Gilles Deleuze.'),
(143, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la realidad y la percepción?', '{"respuestas": ["Fenomenología", "Idealismo", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": ["Fenomenología", "Idealismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la realidad y la percepción son la Fenomenología y el Idealismo.'),
(143, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento pragmático?', '{"respuestas": ["William James", "John Dewey", "Charles Sanders Peirce", "Friedrich Nietzsche"], "respuestas_correctas": ["William James", "John Dewey", "Charles Sanders Peirce"]}', 'Los filósofos considerados representantes del pensamiento pragmático son William James, John Dewey y Charles Sanders Peirce.');

-- Preguntas para el test 4 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(144, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento empirista?', '{"respuestas": ["John Locke", "David Hume", "Immanuel Kant", "René Descartes"], "respuestas_correctas": ["John Locke", "David Hume"]}', 'Los filósofos considerados representantes del pensamiento empirista son John Locke y David Hume.'),
(144, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio del conocimiento y la verdad?', '{"respuestas": ["Epistemología", "Escepticismo", "Hermenéutica", "Idealismo"], "respuestas_correctas": ["Epistemología", "Escepticismo"]}', 'Las corrientes filosóficas que se centran en el estudio del conocimiento y la verdad son la Epistemología y el Escepticismo.'),
(144, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento filosófico oriental?', '{"respuestas": ["Confucio", "Lao-Tsé", "Buda", "Aristóteles"], "respuestas_correctas": ["Confucio", "Lao-Tsé", "Buda"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento filosófico oriental son Confucio, Lao-Tsé y Buda.'),
(144, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la naturaleza humana y la conducta moral?', '{"respuestas": ["Ética deontológica", "Ética teleológica", "Nihilismo", "Determinismo"], "respuestas_correctas": ["Ética deontológica", "Ética teleológica"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la naturaleza humana y la conducta moral son la Ética deontológica y la Ética teleológica.'),
(144, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento racionalista?', '{"respuestas": ["René Descartes", "Baruch Spinoza", "John Locke", "Friedrich Nietzsche"], "respuestas_correctas": ["René Descartes", "Baruch Spinoza"]}', 'Los filósofos considerados representantes del pensamiento racionalista son René Descartes y Baruch Spinoza.'),
(144, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento dialéctico?', '{"respuestas": ["Georg Wilhelm Friedrich Hegel", "Karl Marx", "Friedrich Nietzsche", "Arthur Schopenhauer"], "respuestas_correctas": ["Georg Wilhelm Friedrich Hegel", "Karl Marx"]}', 'Los filósofos considerados representantes del pensamiento dialéctico son Georg Wilhelm Friedrich Hegel y Karl Marx.'),
(144, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la conciencia y la mente?', '{"respuestas": ["Filosofía de la mente", "Idealismo", "Existencialismo", "Escepticismo"], "respuestas_correctas": ["Filosofía de la mente", "Idealismo"]}', 'Las corrientes filosóficas que se centran en el estudio de la conciencia y la mente son la Filosofía de la mente y el Idealismo.'),
(144, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento feminista?', '{"respuestas": ["Simone de Beauvoir", "Judith Butler", "Mary Wollstonecraft", "Rosa Luxemburgo"], "respuestas_correctas": ["Simone de Beauvoir", "Judith Butler", "Mary Wollstonecraft"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento feminista son Simone de Beauvoir, Judith Butler y Mary Wollstonecraft.'),
(144, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la razón y el conocimiento?', '{"respuestas": ["Racionalismo", "Empirismo", "Pragmatismo", "Positivismo lógico"], "respuestas_correctas": ["Racionalismo", "Empirismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la razón y el conocimiento son el Racionalismo y el Empirismo.'),
(144, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento postmodernista?', '{"respuestas": ["Jean-François Lyotard", "Jacques Derrida", "Michel Foucault", "Friedrich Nietzsche"], "respuestas_correctas": ["Jean-François Lyotard", "Jacques Derrida", "Michel Foucault"]}', 'Los filósofos considerados representantes del pensamiento postmodernista son Jean-François Lyotard, Jacques Derrida y Michel Foucault.');

-- Preguntas para el test 5 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(145, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento existencialista?', '{"respuestas": ["Søren Kierkegaard", "Friedrich Nietzsche", "Jean-Paul Sartre", "Albert Camus"], "respuestas_correctas": ["Søren Kierkegaard", "Jean-Paul Sartre"]}', 'Los filósofos considerados representantes del pensamiento existencialista son Søren Kierkegaard y Jean-Paul Sartre.'),
(145, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la justicia y la equidad?', '{"respuestas": ["Ética de la justicia", "Utilitarismo", "Nihilismo", "Positivismo lógico"], "respuestas_correctas": ["Ética de la justicia", "Utilitarismo"]}', 'Las corrientes filosóficas que se centran en el estudio de la justicia y la equidad son la Ética de la justicia y el Utilitarismo.'),
(145, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento político?', '{"respuestas": ["Platón", "Aristóteles", "Maquiavelo", "John Stuart Mill"], "respuestas_correctas": ["Platón", "Aristóteles", "Maquiavelo"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento político son Platón, Aristóteles y Maquiavelo.'),
(145, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la libertad y la autonomía?', '{"respuestas": ["Libertarismo", "Determinismo", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": ["Libertarismo", "Determinismo"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la libertad y la autonomía son el Libertarismo y el Determinismo.'),
(145, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento pragmático?', '{"respuestas": ["William James", "John Dewey", "Charles Sanders Peirce", "Immanuel Kant"], "respuestas_correctas": ["William James", "John Dewey", "Charles Sanders Peirce"]}', 'Los filósofos considerados representantes del pensamiento pragmático son William James, John Dewey y Charles Sanders Peirce.'),
(145, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento posmodernista?', '{"respuestas": ["Jean-François Lyotard", "Michel Foucault", "Jacques Derrida", "Gilles Deleuze"], "respuestas_correctas": ["Jean-François Lyotard", "Michel Foucault", "Jacques Derrida"]}', 'Los filósofos considerados representantes del pensamiento posmodernista son Jean-François Lyotard, Michel Foucault y Jacques Derrida.'),
(145, 2, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la moral y la ética?', '{"respuestas": ["Ética de la virtud", "Utilitarismo", "Deontología", "Nihilismo"], "respuestas_correctas": ["Ética de la virtud", "Deontología"]}', 'Las corrientes filosóficas que se centran en el estudio de la moral y la ética son la Ética de la virtud y la Deontología.'),
(145, 2, '¿Cuáles de los siguientes filósofos son conocidos por sus contribuciones al pensamiento feminista?', '{"respuestas": ["Simone de Beauvoir", "Judith Butler", "Luce Irigaray", "Gloria Anzaldúa"], "respuestas_correctas": ["Simone de Beauvoir", "Judith Butler", "Luce Irigaray"]}', 'Los filósofos conocidos por sus contribuciones al pensamiento feminista son Simone de Beauvoir, Judith Butler y Luce Irigaray.'),
(145, 2, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la realidad y la existencia?', '{"respuestas": ["Existencialismo", "Fenomenología", "Escepticismo", "Positivismo lógico"], "respuestas_correctas": ["Existencialismo", "Fenomenología"]}', 'Las corrientes filosóficas que se enfocan en el estudio de la realidad y la existencia son el Existencialismo y la Fenomenología.'),
(145, 2, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento hermenéutico?', '{"respuestas": ["Hans-Georg Gadamer", "Paul Ricoeur", "Gadamer Ricoeur", "Ricoeur Gadamer"], "respuestas_correctas": ["Hans-Georg Gadamer", "Paul Ricoeur"]}', 'Los filósofos considerados representantes del pensamiento hermenéutico son Hans-Georg Gadamer y Paul Ricoeur.');

/********************************************************************************************************/
/********************************************************************************************************/

-- Datos para la tabla PREGUNTAS de la MATERIA "Filosofía" para el tipo de pregunta 1 respuesta única

/********************************************************************************************************/
/********************************************************************************************************/

-- Preguntas para el test 6 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la naturaleza y el universo?', '{"respuestas": ["Cosmología", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": "Cosmología"}', 'La corriente filosófica que se centra en el estudio de la naturaleza y el universo es la Cosmología.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la realidad y la existencia?', '{"respuestas": ["Ontología", "Idealismo", "Materialismo dialéctico"], "respuestas_correctas": "Ontología"}', 'La corriente filosófica que se centra en el estudio de la realidad y la existencia es la Ontología.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la belleza y el arte?', '{"respuestas": ["Estética", "Pragmatismo", "Positivismo lógico", "Materialismo dialéctico"], "respuestas_correctas": "Estética"}', 'La corriente filosófica que se centra en el estudio de la belleza y el arte es la Estética.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la mente y la conciencia?', '{"respuestas": ["Filosofía de la mente", "Materialismo dialéctico", "Escepticismo", "Positivismo lógico"], "respuestas_correctas": "Filosofía de la mente"}', 'La corriente filosófica que se enfoca en el estudio de la mente y la conciencia es la Filosofía de la mente.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la voluntad y el poder?', '{"respuestas": ["Voluntarismo", "Nihilismo", "Escepticismo"], "respuestas_correctas": "Voluntarismo"}', 'La corriente filosófica que se centra en el estudio de la voluntad y el poder es el Voluntarismo.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la realidad y la existencia?', '{"respuestas": ["Ontología", "Pragmatismo", "Materialismo dialéctico", "Escepticismo"], "respuestas_correctas": "Ontología"}', 'La corriente filosófica que se centra en el estudio de la realidad y la existencia es la Ontología.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la moralidad y la ética?', '{"respuestas": ["Ética normativa", "Existencialismo", "Materialismo dialéctico", "Positivismo lógico"], "respuestas_correctas": "Ética normativa"}', 'La corriente filosófica que se enfoca en el estudio de la moralidad y la ética es la Ética normativa.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la belleza y el arte?', '{"respuestas": ["Estética", "Existencialismo", "Materialismo dialéctico", "Pragmatismo"], "respuestas_correctas": "Estética"}', 'La corriente filosófica que se centra en el estudio de la belleza y el arte es la Estética.'),
(146, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la libertad y la responsabilidad individual?', '{"respuestas": ["Existencialismo", "Materialismo dialéctico", "Positivismo lógico", "Racionalismo"], "respuestas_correctas": "Existencialismo"}', 'La corriente filosófica que se centra en el estudio de la libertad y la responsabilidad individual es el Existencialismo.'),
(146, 1, '¿Cuáles de los siguientes filósofos son considerados empiristas?', '{"respuestas": ["John Locke", "René Descartes", "Georg Wilhelm Friedrich Hegel", "Immanuel Kant"], "respuestas_correctas": "John Locke"}', 'El filósofo considerado empirista es John Locke.');

-- Preguntas para el test 7 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(147, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la justicia y el bienestar social?', '{"respuestas": ["Utilitarismo", "Racionalismo", "Existencialismo", "Idealismo"], "respuestas_correctas": "Utilitarismo"}', 'La corriente filosófica que se centra en el estudio de la justicia y el bienestar social es el Utilitarismo.'),
(147, 1, '¿Cuáles de los siguientes filósofos pertenecieron a la corriente del racionalismo?', '{"respuestas": ["René Descartes", "David Hume", "Friedrich Nietzsche", "Jean-Paul Sartre"], "respuestas_correctas": "René Descartes"}', 'El filósofo que perteneció a la corriente del racionalismo es René Descartes.'),
(147, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la libertad y la responsabilidad?', '{"respuestas": ["Existencialismo", "Determinismo", "Escepticismo"], "respuestas_correctas": "Existencialismo"}', 'La corriente filosófica que se centra en el estudio de la libertad y la responsabilidad es el Existencialismo.'),
(147, 1, '¿Cuáles de las siguientes corrientes filosóficas se enfocan en el estudio de la verdad y la interpretación?', '{"respuestas": ["Hermenéutica", "Positivismo lógico", "Pragmatismo"], "respuestas_correctas": "Hermenéutica"}', 'La corriente filosófica que se enfoca en el estudio de la verdad y la interpretación es la Hermenéutica.'),
(147, 1, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento marxista?', '{"respuestas": ["Karl Marx", "Friedrich Nietzsche", "Immanuel Kant", "René Descartes"], "respuestas_correctas": "Karl Marx"}', 'El filósofo considerado representante del pensamiento marxista es Karl Marx.'),
(147, 1, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento hermenéutico?', '{"respuestas": ["Hans-Georg Gadamer", "Martin Heidegger", "Michel Foucault", "Gilles Deleuze"], "respuestas_correctas": "Hans-Georg Gadamer"}', 'El filósofo considerado representante del pensamiento hermenéutico es Hans-Georg Gadamer.'),
(147, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la verdad y la interpretación?', '{"respuestas": ["Hermenéutica", "Existencialismo", "Pragmatismo", "Idealismo"], "respuestas_correctas": "Hermenéutica"}', 'La corriente filosófica que se centra en el estudio de la verdad y la interpretación es la Hermenéutica.'),
(147, 1, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento marxista?', '{"respuestas": ["Karl Marx", "Friedrich Nietzsche", "Immanuel Kant", "René Descartes"], "respuestas_correctas": "Karl Marx"}', 'El filósofo considerado representante del pensamiento marxista es Karl Marx.'),
(147, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la moral y la conducta humana?', '{"respuestas": ["Ética", "Existencialismo", "Pragmatismo", "Escepticismo"], "respuestas_correctas": "Ética"}', 'La corriente filosófica que se centra en el estudio de la moral y la conducta humana es la Ética.'),
(147, 1, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento hermenéutico?', '{"respuestas": ["Hans-Georg Gadamer", "Martin Heidegger", "Michel Foucault", "Gilles Deleuze"], "respuestas_correctas": "Hans-Georg Gadamer"}', 'El filósofo considerado representante del pensamiento hermenéutico es Hans-Georg Gadamer.');

-- Preguntas para el test 8 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(148, 1, '¿Cuáles de los siguientes filósofos son considerados representantes del pensamiento postestructuralista?', '{"respuestas": ["Jacques Derrida", "Friedrich Nietzsche", "Martin Heidegger", "Simone de Beauvoir"], "respuestas_correctas": "Jacques Derrida"}', 'El filósofo considerado representante del pensamiento postestructuralista es Jacques Derrida.'),
(148, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la verdad y la interpretación?', '{"respuestas": ["Hermenéutica", "Existencialismo", "Pragmatismo", "Idealismo"], "respuestas_correctas": "Hermenéutica"}', 'La corriente filosófica que se centra en el estudio de la verdad y la interpretación es la Hermenéutica.'),
(148, 1, '¿Cuáles de las siguientes corrientes filosóficas se centran en el estudio de la moral y la conducta humana?', '{"respuestas": ["Ética", "Existencialismo", "Pragmatismo", "Escepticismo"], "respuestas_correctas": "Ética"}', 'La corriente filosófica que se centra en el estudio de la moral y la conducta humana es la Ética.'),
(148, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "eterno retorno"?', '{"respuestas": ["Friedrich Nietzsche", "Søren Kierkegaard", "Immanuel Kant", "Jean-Paul Sartre"], "respuestas_correctas": "Friedrich Nietzsche"}', 'Friedrich Nietzsche es conocido por su teoría del "eterno retorno".'),
(148, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en el estudio de la felicidad como el bien supremo?', '{"respuestas": ["Eudemonismo", "Utilitarismo", "Hedonismo", "Nihilismo"], "respuestas_correctas": "Eudemonismo"}', 'La corriente filosófica que se enfoca en el estudio de la felicidad como el bien supremo es el Eudemonismo.'),
(148, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "cogito, ergo sum"?', '{"respuestas": ["René Descartes", "David Hume", "John Locke", "Baruch Spinoza"], "respuestas_correctas": "René Descartes"}', 'René Descartes es conocido por su teoría del "cogito, ergo sum".'),
(148, 1, '¿Cuál de las siguientes corrientes filosóficas se centra en la búsqueda de la sabiduría y el conocimiento?', '{"respuestas": ["Filosofía", "Epistemología", "Ontología", "Metafísica"], "respuestas_correctas": "Filosofía"}', 'La corriente filosófica que se centra en la búsqueda de la sabiduría y el conocimiento es la Filosofía.'),
(148, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de las ideas y la teoría de las formas?', '{"respuestas": ["Platón", "Aristóteles", "Sócrates", "Heráclito"], "respuestas_correctas": "Platón"}', 'Platón es conocido por su teoría de las ideas y la teoría de las formas.'),
(148, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la negación de la existencia de la verdad absoluta?', '{"respuestas": ["Escepticismo", "Relativismo", "Nihilismo", "Hermenéutica"], "respuestas_correctas": "Escepticismo"}', 'La corriente filosófica que se enfoca en la negación de la existencia de la verdad absoluta es el Escepticismo.'),
(148, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "eterno retorno" y la "voluntad de poder"?', '{"respuestas": ["Friedrich Nietzsche", "Søren Kierkegaard", "Immanuel Kant", "Jean-Paul Sartre"], "respuestas_correctas": "Friedrich Nietzsche"}', 'Friedrich Nietzsche es conocido por su teoría del "eterno retorno" y la "voluntad de poder".');

-- Preguntas para el test 9 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(149, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la búsqueda de la felicidad y el placer como fines últimos?', '{"respuestas": ["Hedonismo", "Eudemonismo", "Utilitarismo", "Existencialismo"], "respuestas_correctas": "Hedonismo"}', 'La corriente filosófica que se enfoca en la búsqueda de la felicidad y el placer como fines últimos es el Hedonismo.'),
(149, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo?', '{"respuestas": ["René Descartes", "David Hume", "John Locke", "Baruch Spinoza"], "respuestas_correctas": "René Descartes"}', 'René Descartes es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo.'),
(149, 1, '¿Cuál de las siguientes corrientes filosóficas se centra en el estudio de la realidad y la existencia individual?', '{"respuestas": ["Existencialismo", "Racionalismo", "Empirismo", "Idealismo"], "respuestas_correctas": "Existencialismo"}', 'La corriente filosófica que se centra en el estudio de la realidad y la existencia individual es el Existencialismo.'),
(149, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de las ideas y la teoría de la reminiscencia?', '{"respuestas": ["Platón", "Aristóteles", "Sócrates", "Heráclito"], "respuestas_correctas": "Platón"}', 'Platón es conocido por su teoría de las ideas y la teoría de la reminiscencia.'),
(149, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la negación de la existencia de verdades absolutas y la importancia de la interpretación?', '{"respuestas": ["Hermenéutica", "Escepticismo", "Relativismo", "Nihilismo"], "respuestas_correctas": "Hermenéutica"}', 'La corriente filosófica que se enfoca en la negación de la existencia de verdades absolutas y la importancia de la interpretación es la Hermenéutica.'),
(149, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "eterno retorno" y la "voluntad de poder"?', '{"respuestas": ["Friedrich Nietzsche", "Søren Kierkegaard", "Immanuel Kant", "Jean-Paul Sartre"], "respuestas_correctas": "Friedrich Nietzsche"}', 'Friedrich Nietzsche es conocido por su teoría del "eterno retorno" y la "voluntad de poder".'),
(149, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la búsqueda de la felicidad y el placer como fines últimos?', '{"respuestas": ["Hedonismo", "Eudemonismo", "Utilitarismo", "Existencialismo"], "respuestas_correctas": "Hedonismo"}', 'La corriente filosófica que se enfoca en la búsqueda de la felicidad y el placer como fines últimos es el Hedonismo.'),
(149, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo?', '{"respuestas": ["René Descartes", "David Hume", "John Locke", "Baruch Spinoza"], "respuestas_correctas": "René Descartes"}', 'René Descartes es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo.'),
(149, 1, '¿Cuál de las siguientes corrientes filosóficas se centra en el estudio de la realidad y la existencia individual?', '{"respuestas": ["Existencialismo", "Racionalismo", "Empirismo", "Idealismo"], "respuestas_correctas": "Existencialismo"}', 'La corriente filosófica que se centra en el estudio de la realidad y la existencia individual es el Existencialismo.'),
(149, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de las ideas y la teoría de la reminiscencia?', '{"respuestas": ["Platón", "Aristóteles", "Sócrates", "Heráclito"], "respuestas_correctas": "Platón"}', 'Platón es conocido por su teoría de las ideas y la teoría de la reminiscencia.');

-- Preguntas para el test 10 de Filosofía
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(150, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la negación de la existencia de verdades absolutas y la importancia de la interpretación?', '{"respuestas": ["Hermenéutica", "Escepticismo", "Relativismo", "Nihilismo"], "respuestas_correctas": "Hermenéutica"}', 'La corriente filosófica que se enfoca en la negación de la existencia de verdades absolutas y la importancia de la interpretación es la Hermenéutica.'),
(150, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "eterno retorno" y la "voluntad de poder"?', '{"respuestas": ["Friedrich Nietzsche", "Søren Kierkegaard", "Immanuel Kant", "Jean-Paul Sartre"], "respuestas_correctas": "Friedrich Nietzsche"}', 'Friedrich Nietzsche es conocido por su teoría del "eterno retorno" y la "voluntad de poder".'),
(150, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en la búsqueda de la felicidad y el placer como fines últimos?', '{"respuestas": ["Hedonismo", "Eudemonismo", "Utilitarismo", "Existencialismo"], "respuestas_correctas": "Hedonismo"}', 'La corriente filosófica que se enfoca en la búsqueda de la felicidad y el placer como fines últimos es el Hedonismo.'),
(150, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo?', '{"respuestas": ["René Descartes", "David Hume", "John Locke", "Baruch Spinoza"], "respuestas_correctas": "René Descartes"}', 'René Descartes es conocido por su teoría del "cogito, ergo sum" y el dualismo mente-cuerpo.'),
(150, 1, '¿Cuál de las siguientes corrientes filosóficas se centra en el estudio de la realidad y la existencia individual?', '{"respuestas": ["Existencialismo", "Racionalismo", "Empirismo", "Idealismo"], "respuestas_correctas": "Existencialismo"}', 'La corriente filosófica que se centra en el estudio de la realidad y la existencia individual es el Existencialismo.'),
(150, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de las ideas y la teoría de la reminiscencia?', '{"respuestas": ["Platón", "Aristóteles", "Sócrates", "Heráclito"], "respuestas_correctas": "Platón"}', 'Platón es conocido por su teoría de las ideas y la teoría de la reminiscencia.'),
(150, 1, '¿Cuál de las siguientes corrientes filosóficas sostiene que el universo es un sistema ordenado y armonioso?', '{"respuestas": ["Cosmismo", "Determinismo", "Estoicismo", "Existencialismo"], "respuestas_correctas": "Cosmismo"}', 'La corriente filosófica que sostiene que el universo es un sistema ordenado y armonioso es el Cosmismo.'),
(150, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de la "voluntad de vivir" y el pesimismo metafísico?', '{"respuestas": ["Arthur Schopenhauer", "John Locke", "René Descartes", "David Hume"], "respuestas_correctas": "Arthur Schopenhauer"}', 'Arthur Schopenhauer es conocido por su teoría de la "voluntad de vivir" y el pesimismo metafísico.'),
(150, 1, '¿Cuál de las siguientes corrientes filosóficas se enfoca en el estudio de la moral y la ética?', '{"respuestas": ["Ética de la Virtud", "Utilitarismo", "Hedonismo", "Empirismo"], "respuestas_correctas": "Ética de la Virtud"}', 'La corriente filosófica que se enfoca en el estudio de la moral y la ética es la Ética de la Virtud.'),
(150, 1, '¿Cuál de los siguientes filósofos es conocido por su teoría de la "duda metódica" y la búsqueda de conocimiento a través de la razón?', '{"respuestas": ["René Descartes", "Platón", "Aristóteles", "Sócrates"], "respuestas_correctas": "René Descartes"}', 'René Descartes es conocido por su teoría de la "duda metódica" y la búsqueda de conocimiento a través de la razón.');

-- Renumera el id de PREGUNTAS
SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;
