-- Datos para la tabla TESTS para los test de Física del tipo tipo de pregunta 1 respuesta única
INSERT INTO tests (id_materia, nombre_test, descripcion, id_usuario_creador) VALUES
(8, 'Física 01', 'Test 01 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 02', 'Test 02 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 03', 'Test 03 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 04', 'Test 04 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 05', 'Test 05 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 06', 'Test 06 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 07', 'Test 07 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 08', 'Test 08 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 09', 'Test 09 sobre la materia de Física de respuesta única.', 1),
(8, 'Física 10', 'Test 10 sobre la materia de Física de respuesta única.', 1);

SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE tests SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;

-- Datos para la tabla PREGUNTAS de la MATERIA "Física" para el tipo de pregunta 1 respuesta única

-- Preguntas para el test 1 de Física Fórmulas
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(211, 1, '¿Cuál es la fórmula para calcular la velocidad?', '{"respuestas": ["v = d/t", "v = m/a", "v = F/m", "v = P/A"], "respuesta_correcta": "v = d/t"}', null),
(211, 1, '¿Cuál es la unidad de medida de la resistencia eléctrica?', '{"respuestas": ["Voltio", "Amperio", "Ohmio", "Watio"], "respuesta_correcta": "Ohmio"}', null),
(211, 1, '¿Cuál es la fórmula para calcular la fuerza resultante?', '{"respuestas": ["F = m × a", "F = P × A", "F = d × t", "F = ρ × V × g"], "respuesta_correcta": "F = m × a"}', null),
(211, 1, '¿Cuál es la unidad de medida de la energía?', '{"respuestas": ["Vatio", "Joule", "Ohmio", "Coulomb"], "respuesta_correcta": "Joule"}', null),
(211, 1, '¿Cuál es la fórmula para calcular la densidad?', '{"respuestas": ["ρ = m/V", "ρ = P/A", "ρ = F/m", "ρ = d/t"], "respuesta_correcta": "ρ = m/V"}', null),
(211, 1, '¿Cuál es la unidad de medida del trabajo?', '{"respuestas": ["Joule", "Voltio", "Watio", "Amperio"], "respuesta_correcta": "Joule"}', null),
(211, 1, '¿Cuál es la fórmula para calcular la potencia eléctrica?', '{"respuestas": ["P = V × I", "P = m × a", "P = F × d", "P = ρ × V × g"], "respuesta_correcta": "P = V × I"}', null),
(211, 1, '¿Cuál es la unidad de medida del voltaje?', '{"respuestas": ["Voltio", "Amperio", "Ohmio", "Watio"], "respuesta_correcta": "Voltio"}', null),
(211, 1, '¿Cuál es la fórmula para calcular el trabajo?', '{"respuestas": ["W = F × d", "W = P × A", "W = m × a", "W = ρ × V × g"], "respuesta_correcta": "W = F × d"}', null),
(211, 1, '¿Cuál es la unidad de medida de la corriente eléctrica?', '{"respuestas": ["Amperio", "Voltio", "Ohmio", "Watio"], "respuesta_correcta": "Amperio"}', null);

-- Preguntas para el test 2 de Física Fórmulas
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(212, 1, '¿Cuál es la ley de Newton que describe la conservación de la cantidad de movimiento?', '{"respuestas": ["Primera ley de Newton", "Segunda ley de Newton", "Tercera ley de Newton", "Ley de la gravitación universal"], "respuesta_correcta": "Primera ley de Newton"}', null),
(212, 1, '¿Cuál es la unidad de medida de la presión?', '{"respuestas": ["Pascal", "Newton", "Joule", "Amperio"], "respuesta_correcta": "Pascal"}', null),
(212, 1, '¿Cuál es la fórmula para calcular la aceleración?', '{"respuestas": ["a = Δv/Δt", "a = F/m", "a = P/A", "a = ρ × V × g"], "respuesta_correcta": "a = Δv/Δt"}', null),
(212, 1, '¿Cuál es la unidad de medida de la fuerza?', '{"respuestas": ["Newton", "Joule", "Watio", "Amperio"], "respuesta_correcta": "Newton"}', null),
(212, 1, '¿Cuál es la fórmula para calcular la energía cinética?', '{"respuestas": ["Ec = (1/2) × m × v^2", "Ec = F × d", "Ec = P × A", "Ec = ρ × V × g"], "respuesta_correcta": "Ec = (1/2) × m × v^2"}', null),
(212, 1, '¿Cuál es la unidad de medida de la energía potencial?', '{"respuestas": ["Joule", "Voltio", "Watio", "Amperio"], "respuesta_correcta": "Joule"}', null),
(212, 1, '¿Cuál es la fórmula para calcular la resistencia eléctrica?', '{"respuestas": ["R = V/I", "R = m × a", "R = F × d", "R = ρ × V × g"], "respuesta_correcta": "R = V/I"}', null),
(212, 1, '¿Cuál es la unidad de medida de la frecuencia?', '{"respuestas": ["Hertz", "Newton", "Joule", "Amperio"], "respuesta_correcta": "Hertz"}', null),
(212, 1, '¿Cuál es la fórmula para calcular la potencia?', '{"respuestas": ["P = W/t", "P = F × d", "P = m × a", "P = ρ × V × g"], "respuesta_correcta": "P = W/t"}', null),
(212, 1, '¿Cuál es la unidad de medida de la carga eléctrica?', '{"respuestas": ["Coulomb", "Voltio", "Ohmio", "Watio"], "respuesta_correcta": "Coulomb"}', null);

-- Preguntas para el test 3 de Física Conceptos
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(213, 1, '¿Qué es la Ley de Ohm?', '{"respuestas": ["Relación entre la corriente eléctrica, la resistencia y la diferencia de potencial", "Relación entre la masa y la aceleración de un objeto", "Relación entre la fuerza y la aceleración de un objeto", "Relación entre la presión y el volumen de un gas"], "respuesta_correcta": "Relación entre la corriente eléctrica, la resistencia y la diferencia de potencial"}', null),
(213, 1, '¿Qué es la Ley de la Gravitación Universal?', '{"respuestas": ["Ley que describe la fuerza de atracción entre dos objetos debido a su masa", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica", "Ley que describe la relación entre la presión y el volumen de un gas"], "respuesta_correcta": "Ley que describe la fuerza de atracción entre dos objetos debido a su masa"}', null),
(213, 1, '¿Qué es el Principio de Conservación de la Energía?', '{"respuestas": ["La energía total de un sistema aislado se mantiene constante", "La energía cinética de un objeto es proporcional a su masa y velocidad", "La energía potencial elástica se almacena en objetos deformables", "La energía térmica se transfiere de un objeto a otro debido a una diferencia de temperatura"], "respuesta_correcta": "La energía total de un sistema aislado se mantiene constante"}', null),
(213, 1, '¿Qué es la Ley de Conservación del Momento Lineal?', '{"respuestas": ["El momento lineal total de un sistema aislado se mantiene constante", "La aceleración de un objeto es directamente proporcional a la fuerza neta aplicada sobre él", "La fuerza de fricción es proporcional a la normal entre dos superficies en contacto", "La resistencia eléctrica es inversamente proporcional a la corriente eléctrica"], "respuesta_correcta": "El momento lineal total de un sistema aislado se mantiene constante"}', null),
(213, 1, '¿Qué es el Principio de Arquímedes?', '{"respuestas": ["Un objeto sumergido en un fluido experimenta una fuerza hacia arriba igual al peso del fluido desplazado", "La fuerza ejercida por un objeto es igual y opuesta a la fuerza ejercida sobre él", "La aceleración de un objeto es directamente proporcional a la fuerza neta aplicada sobre él", "La resistencia eléctrica es inversamente proporcional a la corriente eléctrica"], "respuesta_correcta": "Un objeto sumergido en un fluido experimenta una fuerza hacia arriba igual al peso del fluido desplazado"}', null),
(213, 1, '¿Qué es la Ley de Newton de la Gravitación Universal?', '{"respuestas": ["Ley que describe la fuerza de atracción entre dos objetos debido a su masa", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica", "Ley que describe la relación entre la presión y el volumen de un gas"], "respuesta_correcta": "Ley que describe la fuerza de atracción entre dos objetos debido a su masa"}', null),
(213, 1, '¿Qué es la Ley de Coulomb?', '{"respuestas": ["Ley que describe la fuerza eléctrica entre dos cargas", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "Ley que describe la fuerza eléctrica entre dos cargas"}', null),
(213, 1, '¿Qué es la Ley de Faraday?', '{"respuestas": ["Ley que describe la inducción electromagnética", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "Ley que describe la inducción electromagnética"}', null),
(213, 1, '¿Qué es el Principio de Pascal?', '{"respuestas": ["La presión ejercida en un fluido se transmite de manera uniforme en todas las direcciones", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "La presión ejercida en un fluido se transmite de manera uniforme en todas las direcciones"}', null),
(213, 1, '¿Qué es la Ley de Conservación de la Carga Eléctrica?', '{"respuestas": ["La carga eléctrica total en un sistema aislado se mantiene constante", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "La carga eléctrica total en un sistema aislado se mantiene constante"}', null);

-- Preguntas para el test 4 de Física Conceptos
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(214, 1, '¿Qué es el Principio de Conservación de la Energía Mecánica?', '{"respuestas": ["La energía mecánica total de un sistema aislado se mantiene constante", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía térmica"], "respuesta_correcta": "La energía mecánica total de un sistema aislado se mantiene constante"}', null),
(214, 1, '¿Qué es el Principio de la Conservación del Momento Lineal?', '{"respuestas": ["El momento lineal total de un sistema aislado se mantiene constante", "La aceleración de un objeto es directamente proporcional a la fuerza neta aplicada sobre él", "La resistencia eléctrica es inversamente proporcional a la corriente eléctrica", "La presión de un gas es inversamente proporcional a su volumen"], "respuesta_correcta": "El momento lineal total de un sistema aislado se mantiene constante"}', null),
(214, 1, '¿Qué es la Ley de Conservación de la Energía?', '{"respuestas": ["La energía total de un sistema aislado se mantiene constante", "La energía cinética de un objeto es proporcional a su masa y velocidad", "La energía potencial elástica se almacena en objetos deformables", "La energía térmica se transfiere de un objeto a otro debido a una diferencia de temperatura"], "respuesta_correcta": "La energía total de un sistema aislado se mantiene constante"}', null),
(214, 1, '¿Qué es el Principio de Arquímedes?', '{"respuestas": ["Un objeto sumergido en un fluido experimenta una fuerza hacia arriba igual al peso del fluido desplazado", "La fuerza ejercida por un objeto es igual y opuesta a la fuerza ejercida sobre él", "La aceleración de un objeto es directamente proporcional a la fuerza neta aplicada sobre él", "La resistencia eléctrica es inversamente proporcional a la corriente eléctrica"], "respuesta_correcta": "Un objeto sumergido en un fluido experimenta una fuerza hacia arriba igual al peso del fluido desplazado"}', null),
(214, 1, '¿Qué es la Ley de Snell?', '{"respuestas": ["Ley que describe la refracción de la luz al pasar de un medio a otro", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación del momento angular"], "respuesta_correcta": "Ley que describe la refracción de la luz al pasar de un medio a otro"}', null),
(214, 1, '¿Qué es la Ley de Hooke?', '{"respuestas": ["Ley que describe la relación entre la fuerza aplicada a un resorte y su deformación", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe la relación entre la corriente eléctrica y la resistencia", "Ley que describe el desplazamiento de un objeto en función del tiempo"], "respuesta_correcta": "Ley que describe la relación entre la fuerza aplicada a un resorte y su deformación"}', null),
(214, 1, '¿Qué es la Ley de Conservación de la Cantidad de Movimiento?', '{"respuestas": ["La cantidad de movimiento total de un sistema aislado se mantiene constante", "La aceleración de un objeto es directamente proporcional a la fuerza neta aplicada sobre él", "La resistencia eléctrica es inversamente proporcional a la corriente eléctrica", "La presión de un gas es inversamente proporcional a su volumen"], "respuesta_correcta": "La cantidad de movimiento total de un sistema aislado se mantiene constante"}', null),
(214, 1, '¿Qué es la Ley de Gauss?', '{"respuestas": ["Ley que describe el flujo eléctrico a través de una superficie cerrada", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "Ley que describe el flujo eléctrico a través de una superficie cerrada"}', null),
(214, 1, '¿Qué es la Ley de Ampère?', '{"respuestas": ["Ley que describe el campo magnético creado por una corriente eléctrica", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "Ley que describe el campo magnético creado por una corriente eléctrica"}', null),
(214, 1, '¿Qué es el Principio de Conservación de la Carga Eléctrica?', '{"respuestas": ["La carga eléctrica total en un sistema aislado se mantiene constante", "Ley que describe la relación entre la presión y el volumen de un gas", "Ley que describe el desplazamiento de un objeto en función del tiempo", "Ley que describe la conservación de la energía mecánica"], "respuesta_correcta": "La carga eléctrica total en un sistema aislado se mantiene constante"}', null);

-- Preguntas para el test 5 de Física Científicos
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(215, 1, '¿Quién propuso la Teoría de la Relatividad?', '{"respuestas": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie"], "respuesta_correcta": "Albert Einstein"}', null),
(215, 1, '¿Quién formuló las Leyes del Movimiento?', '{"respuestas": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], "respuesta_correcta": "Isaac Newton"}', null),
(215, 1, '¿Quién desarrolló la Teoría Cuántica?', '{"respuestas": ["Max Planck", "Albert Einstein", "Erwin Schrödinger", "Niels Bohr"], "respuesta_correcta": "Max Planck"}', null),
(215, 1, '¿Quién descubrió la Radiactividad?', '{"respuestas": ["Marie Curie", "Isaac Newton", "Galileo Galilei", "Albert Einstein"], "respuesta_correcta": "Marie Curie"}', null),
(215, 1, '¿Quién enunció la Ley de Conservación de la Energía?', '{"respuestas": ["Hermann von Helmholtz", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], "respuesta_correcta": "Hermann von Helmholtz"}', null),
(215, 1, '¿Quién postuló la Teoría del Big Bang?', '{"respuestas": ["Georges Lemaître", "Albert Einstein", "Stephen Hawking", "Edwin Hubble"], "respuesta_correcta": "Georges Lemaître"}', null),
(215, 1, '¿Quién desarrolló la Teoría de la Relatividad General?', '{"respuestas": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie"], "respuesta_correcta": "Albert Einstein"}', null),
(215, 1, '¿Quién formuló la Ley de la Conservación de la Carga Eléctrica?', '{"respuestas": ["Charles-Augustin de Coulomb", "Isaac Newton", "Galileo Galilei", "James Clerk Maxwell"], "respuesta_correcta": "Charles-Augustin de Coulomb"}', null),
(215, 1, '¿Quién propuso el Principio de Incertidumbre?', '{"respuestas": ["Werner Heisenberg", "Albert Einstein", "Erwin Schrödinger", "Niels Bohr"], "respuesta_correcta": "Werner Heisenberg"}', null),
(215, 1, '¿Quién descubrió la Ley de la Gravitación Universal?', '{"respuestas": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], "respuesta_correcta": "Isaac Newton"}', null);

-- Preguntas para el test 6 de Física Científicos
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(216, 1, '¿Quién descubrió los rayos X?', '{"respuestas": ["Wilhelm Conrad Roentgen", "Albert Einstein", "Marie Curie", "Max Planck"], "respuesta_correcta": "Wilhelm Conrad Roentgen"}', null),
(216, 1, '¿Quién formuló la Ley de la Termodinámica?', '{"respuestas": ["Sadi Carnot", "Isaac Newton", "James Prescott Joule", "Rudolf Clausius"], "respuesta_correcta": "Sadi Carnot"}', null),
(216, 1, '¿Quién desarrolló la Teoría de la Relatividad Especial?', '{"respuestas": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie"], "respuesta_correcta": "Albert Einstein"}', null),
(216, 1, '¿Quién descubrió la Radiación Electromagnética?', '{"respuestas": ["James Clerk Maxwell", "Isaac Newton", "Galileo Galilei", "Albert Einstein"], "respuesta_correcta": "James Clerk Maxwell"}', null),
(216, 1, '¿Quién enunció la Ley de la Conservación de la Cantidad de Movimiento?', '{"respuestas": ["Isaac Newton", "Galileo Galilei", "Nikola Tesla", "Albert Einstein"], "respuesta_correcta": "Isaac Newton"}', null),
(216, 1, '¿Quién postuló la Ley de la Conservación de la Energía Mecánica?', '{"respuestas": ["Hermann von Helmholtz", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], "respuesta_correcta": "Hermann von Helmholtz"}', null),
(216, 1, '¿Quién desarrolló la Teoría de la Gravedad Cuántica de Bucles?', '{"respuestas": ["Carlo Rovelli", "Albert Einstein", "Stephen Hawking", "Edward Witten"], "respuesta_correcta": "Carlo Rovelli"}', null),
(216, 1, '¿Quién formuló la Ley de Ampère?', '{"respuestas": ["André-Marie Ampère", "Isaac Newton", "Galileo Galilei", "James Clerk Maxwell"], "respuesta_correcta": "André-Marie Ampère"}', null),
(216, 1, '¿Quién propuso la Teoría de las Cuerdas?', '{"respuestas": ["Leonard Susskind", "Albert Einstein", "Erwin Schrödinger", "Niels Bohr"], "respuesta_correcta": "Leonard Susskind"}', null),
(216, 1, '¿Quién descubrió el Efecto Compton?', '{"respuestas": ["Arthur H. Compton", "Isaac Newton", "Galileo Galilei", "Albert Einstein"], "respuesta_correcta": "Arthur H. Compton"}', null);

-- Preguntas para el test 7 de Física Cuántica
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(217, 1, '¿Cuál de los siguientes científicos formuló el principio de incertidumbre?', '{"respuestas": ["Werner Heisenberg", "Max Planck", "Erwin Schrödinger", "Albert Einstein"], "respuesta_correcta": "Werner Heisenberg"}', null),
(217, 1, '¿Cuál de los siguientes fenómenos es característico de la dualidad onda-partícula?', '{"respuestas": ["Interferencia", "Difracción", "Entrelazamiento", "Túnel cuántico"], "respuesta_correcta": "Interferencia"}', null),
(217, 1, '¿Cuál es la unidad fundamental de la energía en la física cuántica?', '{"respuestas": ["Fotón", "Electrón", "Bosón", "Quark"], "respuesta_correcta": "Fotón"}', null),
(217, 1, '¿Qué postula el principio de superposición en la mecánica cuántica?', '{"respuestas": ["Un sistema puede estar en múltiples estados al mismo tiempo", "La energía de un sistema está cuantizada", "El estado de un sistema cambia de manera continua", "La posición y el momento de una partícula no se pueden conocer simultáneamente con precisión"], "respuesta_correcta": "Un sistema puede estar en múltiples estados al mismo tiempo"}', null),
(217, 1, '¿Cuál de los siguientes conceptos está asociado al entrelazamiento cuántico?', '{"respuestas": ["Teletransportación cuántica", "Colapso de la función de onda", "Efecto túnel", "Principio de exclusión"], "respuesta_correcta": "Teletransportación cuántica"}', null),
(217, 1, '¿Qué es un qubit?', '{"respuestas": ["La unidad básica de información cuántica", "Una partícula elemental", "Un estado de superposición", "Una partícula subatómica"], "respuesta_correcta": "La unidad básica de información cuántica"}', null),
(217, 1, '¿Cuál de los siguientes experimentos demuestra el entrelazamiento cuántico?', '{"respuestas": ["Experimento de Bell", "Experimento de doble rendija", "Experimento de la caja negra", "Experimento de la doble rendija cuántica"], "respuesta_correcta": "Experimento de Bell"}', null),
(217, 1, '¿Cuál de las siguientes partículas tiene espín 1/2?', '{"respuestas": ["Electrón", "Fotón", "Bosón", "Neutrino"], "respuesta_correcta": "Electrón"}', null),
(217, 1, '¿Cuál de los siguientes efectos está relacionado con la desintegración radiactiva?', '{"respuestas": ["Decaimiento exponencial", "Efecto fotoeléctrico", "Efecto Compton", "Interferencia cuántica"], "respuesta_correcta": "Decaimiento exponencial"}', null),
(217, 1, '¿Qué es la dualidad onda-partícula en la física cuántica?', '{"respuestas": ["La capacidad de las partículas de comportarse tanto como partículas como ondas", "La interacción entre dos partículas entrelazadas", "La superposición de estados cuánticos", "El efecto de tunelamiento de las partículas"], "respuesta_correcta": "La capacidad de las partículas de comportarse tanto como partículas como ondas"}', null);

-- Preguntas para el test 8 de Física Cuántica
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(218, 1, '¿Qué es el entrelazamiento cuántico?', '{"respuestas": ["Una correlación instantánea entre dos partículas entrelazadas", "La capacidad de una partícula de atravesar una barrera de potencial", "La probabilidad de encontrar una partícula en un estado determinado", "La influencia de la gravedad en los sistemas cuánticos"], "respuesta_correcta": "Una correlación instantánea entre dos partículas entrelazadas"}', null),
(218, 1, '¿Qué es la superposición cuántica?', '{"respuestas": ["La combinación de múltiples estados cuánticos en un sistema", "La desintegración radiactiva de un núcleo atómico", "La capacidad de medir con precisión la posición y el momento de una partícula", "La interacción entre partículas cargadas eléctricamente"], "respuesta_correcta": "La combinación de múltiples estados cuánticos en un sistema"}', null),
(218, 1, '¿Qué es el principio de exclusión de Pauli?', '{"respuestas": ["Dos fermiones idénticos no pueden ocupar el mismo estado cuántico simultáneamente", "La probabilidad de encontrar una partícula en una posición determinada", "La influencia de la gravedad en los sistemas cuánticos", "La capacidad de una partícula de atravesar una barrera de potencial"], "respuesta_correcta": "Dos fermiones idénticos no pueden ocupar el mismo estado cuántico simultáneamente"}', null),
(218, 1, '¿Qué es la teletransportación cuántica?', '{"respuestas": ["La transferencia instantánea de información cuántica entre dos ubicaciones distantes", "La propagación de una onda a través de un medio material", "El proceso de crear partículas a partir de la energía", "La interacción entre partículas cargadas eléctricamente"], "respuesta_correcta": "La transferencia instantánea de información cuántica entre dos ubicaciones distantes"}', null),
(218, 1, '¿Qué es la decoherencia cuántica?', '{"respuestas": ["La pérdida de coherencia y superposición de estados cuánticos debido a la interacción con el entorno", "La propagación de una onda a través de un medio material", "El proceso de crear partículas a partir de la energía", "La interacción entre partículas cargadas eléctricamente"], "respuesta_correcta": "La pérdida de coherencia y superposición de estados cuánticos debido a la interacción con el entorno"}', null),
(218, 1, '¿Cuál de las siguientes afirmaciones describe mejor el principio de superposición en la física cuántica?', '{"respuestas": ["Un sistema cuántico puede estar en múltiples estados al mismo tiempo", "La posición y el momento de una partícula se pueden conocer con precisión simultáneamente", "La energía de un sistema cuántico está cuantizada", "La interacción entre partículas cuánticas produce un entrelazamiento"], "respuesta_correcta": "Un sistema cuántico puede estar en múltiples estados al mismo tiempo"}', null),
(218, 1, '¿Qué es la entropía cuántica?', '{"respuestas": ["Una medida de la cantidad de información contenida en un sistema cuántico", "La capacidad de un sistema cuántico para realizar cálculos complejos", "La probabilidad de encontrar una partícula en un estado cuántico determinado", "La influencia de la gravedad en los sistemas cuánticos"], "respuesta_correcta": "Una medida de la cantidad de información contenida en un sistema cuántico"}', null),
(218, 1, '¿Cuál de las siguientes partículas es un bosón?', '{"respuestas": ["Fotón", "Electrón", "Neutrino", "Quark"], "respuesta_correcta": "Fotón"}', null),
(218, 1, '¿Cuál de las siguientes teorías describe mejor la física cuántica?', '{"respuestas": ["Mecánica cuántica", "Relatividad general", "Teoría electromagnética", "Termodinámica"], "respuesta_correcta": "Mecánica cuántica"}', null),
(218, 1, '¿Qué es el efecto túnel en la física cuántica?', '{"respuestas": ["La capacidad de una partícula cuántica de atravesar una barrera de potencial", "La propagación de una onda a través de un medio material", "La transferencia instantánea de información cuántica entre dos ubicaciones distantes", "La interacción entre partículas cargadas eléctricamente"], "respuesta_correcta": "La capacidad de una partícula cuántica de atravesar una barrera de potencial"}', null);

-- Preguntas para el test 9 de Física Nuclear
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(219, 1, '¿Qué es la energía de enlace nuclear?', '{"respuestas": ["La energía necesaria para romper el núcleo de un átomo", "La energía liberada durante una reacción nuclear", "La energía que mantiene unidos los nucleones en el núcleo", "La energía total de un átomo"], "respuesta_correcta": "La energía que mantiene unidos los nucleones en el núcleo"}', null),
(219, 1, '¿Cuál de las siguientes partículas tiene carga eléctrica positiva en el núcleo atómico?', '{"respuestas": ["Protón", "Electrón", "Neutrón", "Positrón"], "respuesta_correcta": "Protón"}', null),
(219, 1, '¿Cuál de las siguientes partículas es responsable de la estabilidad del núcleo atómico?', '{"respuestas": ["Neutrón", "Electrón", "Positrón", "Protón"], "respuesta_correcta": "Neutrón"}', null),
(219, 1, '¿Qué es la desintegración alfa?', '{"respuestas": ["La emisión de partículas alfa por un núcleo inestable", "La fusión de dos núcleos atómicos para formar uno más pesado", "La división de un núcleo atómico en dos o más fragmentos", "La transformación de un neutrón en un protón"], "respuesta_correcta": "La emisión de partículas alfa por un núcleo inestable"}', null),
(219, 1, '¿Cuál de las siguientes fuerzas es responsable de la repulsión entre los protones en el núcleo atómico?', '{"respuestas": ["Fuerza electromagnética", "Fuerza nuclear fuerte", "Fuerza nuclear débil", "Fuerza gravitatoria"], "respuesta_correcta": "Fuerza electromagnética"}', null),
(219, 1, '¿Qué es la desintegración beta?', '{"respuestas": ["La emisión de partículas beta por un núcleo inestable", "La unión de dos núcleos atómicos para formar uno más pesado", "La división de un núcleo atómico en dos o más fragmentos", "La transformación de un protón en un neutrón"], "respuesta_correcta": "La emisión de partículas beta por un núcleo inestable"}', null),
(219, 1, '¿Qué es la radiactividad gamma?', '{"respuestas": ["La emisión de fotones por un núcleo atómico", "La desintegración espontánea de núcleos atómicos inestables", "La liberación de energía durante una reacción nuclear", "La formación de nuevos elementos en un reactor nuclear"], "respuesta_correcta": "La emisión de fotones por un núcleo atómico"}', null),
(219, 1, '¿Cuál es la masa del neutrón en el núcleo atómico?', '{"respuestas": ["Aproximadamente igual a la masa del protón", "Casi igual a la masa del electrón", "Casi igual a la masa del positrón", "Despreciable en comparación con la masa del protón"], "respuesta_correcta": "Aproximadamente igual a la masa del protón"}', null),
(219, 1, '¿Cuál es la carga eléctrica del neutrón en el núcleo atómico?', '{"respuestas": ["Neutro (0)", "Positiva (+1)", "Negativa (-1)", "Variable"], "respuesta_correcta": "Neutro (0)"}', null),
(219, 1, '¿Qué es la emisión de positrones?', '{"respuestas": ["La transformación de un protón en un positrón", "La división de un núcleo atómico en dos o más fragmentos", "La fusión de dos núcleos atómicos para formar uno más pesado", "La emisión de partículas alfa por un núcleo inestable"], "respuesta_correcta": "La transformación de un protón en un positrón"}', null);

-- Preguntas para el test 10 de Física Nuclear
INSERT INTO preguntas (id_test, tipo_pregunta, nombre_pregunta, datos_pregunta, retroalimentacion) VALUES
(220, 1, '¿Qué es la fisión nuclear?', '{"respuestas": ["La división de un núcleo atómico en dos o más fragmentos", "La fusión de dos núcleos atómicos para formar uno más pesado", "La emisión de partículas alfa por un núcleo inestable", "La transformación de un neutrón en un protón"], "respuesta_correcta": "La división de un núcleo atómico en dos o más fragmentos"}', null),
(220, 1, '¿Cuál de las siguientes partículas no se encuentra en el núcleo atómico?', '{"respuestas": ["Electrón", "Protón", "Neutrón", "Positrón"], "respuesta_correcta": "Electrón"}', null),
(220, 1, '¿Cuál es la fuerza responsable de mantener unidos los nucleones en el núcleo atómico?', '{"respuestas": ["Fuerza nuclear fuerte", "Fuerza electromagnética", "Fuerza nuclear débil", "Fuerza gravitatoria"], "respuesta_correcta": "Fuerza nuclear fuerte"}', null),
(220, 1, '¿Qué es la radiactividad?', '{"respuestas": ["La desintegración espontánea de núcleos atómicos inestables", "La emisión de fotones por un núcleo atómico", "La liberación de energía durante una reacción nuclear", "La formación de nuevos elementos en un reactor nuclear"], "respuesta_correcta": "La desintegración espontánea de núcleos atómicos inestables"}', null),
(220, 1, '¿Cuál de las siguientes partículas es un nucleón?', '{"respuestas": ["Protón", "Electrón", "Neutrino", "Positrón"], "respuesta_correcta": "Protón"}', null),
(220, 1, '¿Qué es la fusión nuclear?', '{"respuestas": ["La unión de dos núcleos atómicos para formar uno más pesado", "La división de un núcleo atómico en dos o más fragmentos", "La emisión de partículas beta por un núcleo inestable", "La transformación de un protón en un neutrón"], "respuesta_correcta": "La unión de dos núcleos atómicos para formar uno más pesado"}', null),
(220, 1, '¿Qué es la masa atómica?', '{"respuestas": ["La masa total de un átomo, incluyendo protones, neutrones y electrones", "La masa de los protones y neutrones en el núcleo atómico", "La masa de los electrones en un átomo", "La masa del núcleo atómico"], "respuesta_correcta": "La masa total de un átomo, incluyendo protones, neutrones y electrones"}', null),
(220, 1, '¿Qué es la desintegración gamma?', '{"respuestas": ["La emisión de radiación electromagnética de alta energía por un núcleo atómico", "La emisión de partículas beta por un núcleo inestable", "La emisión de partículas alfa por un núcleo inestable", "La fusión de dos núcleos atómicos para formar uno más pesado"], "respuesta_correcta": "La emisión de radiación electromagnética de alta energía por un núcleo atómico"}', null),
(220, 1, '¿Cuál de las siguientes fuerzas es responsable de la desintegración de un núcleo inestable?', '{"respuestas": ["Fuerza nuclear débil", "Fuerza electromagnética", "Fuerza nuclear fuerte", "Fuerza gravitatoria"], "respuesta_correcta": "Fuerza nuclear débil"}', null),
(220, 1, '¿Cuál es la masa atómica relativa de un isótopo?', '{"respuestas": ["La masa del isótopo dividida por la masa del carbono-12", "La masa del isótopo multiplicada por la masa del hidrógeno-1", "La masa del isótopo dividida por la masa del oxígeno-16", "La masa del isótopo sumada a la masa del neutrón"], "respuesta_correcta": "La masa del isótopo dividida por la masa del carbono-12"}', null);

-- Renumera el id de PREGUNTAS
SET foreign_key_checks = 0;

SET @newid := 0;
UPDATE preguntas SET id = (@newid := @newid + 1) ORDER BY id;

SET foreign_key_checks = 1;